### PR TITLE
Fixes #769. Do form validation on page load

### LINKED ISSUE #769: Buggy form validation
If you fill out the bug form and reload the page the submit buttons are disabled.

### PR DESCRIPTION
**Pull request by miketaylr**
This has annoyed me a few times in the past. :beetle: 

r? @magsout

### CODE REVIEW

**Comment by miketaylr** [comment]
Oops, didn't notice the failure.

**Comment by miketaylr** [comment]
OK, passing now @magsout

**Comment by magsout** [comment]
@miketaylr I'll take a look tomorrow ;)!

**Comment by miketaylr** [comment]
Thanks! (no rush)

**Pull request merged**
