### PR TITLE
#1933 - Adds content, routes and unittests to contributors section

### PR DESCRIPTION
**Pull request by karlcow**

### CODE REVIEW

**Comment by karlcow** [comment]
@zoepage content added for Issue #1933 

```
→ nosetests
..................................................................................
----------------------------------------------------------------------
Ran 82 tests in 2.198s

OK
```

**Comment by zoepage** [comment]
Awesome, thank you! :)
Could you please rename the branch to `issues/1933` before I add the comments? Just so we follow our conventions?

(Gonna start the review on paper and add the comments after rename)

**Comment by miketaylr** [comment]
> Could you please rename the branch to issues/1933 before I add the comments? Just so we follow our conventions?

(IMHO, branch names aren't worth enforcing or caring about, especially when they come from forks (like karl's PR))

**Comment by karlcow** [comment]
The current branch name is "refactor on karlcow" from the point of view of webcompat, I can rename it to "1933/1 on karlcow" if you prefer. Note that it will delete this pull request. :)

**Comment by karlcow** [comment]
Done in #2057

**Pull request closed without merging**
