### PR TITLE
Fix message requesting multiple browser selection

### PR DESCRIPTION
**Pull request by tagawa**
This PR avoids confusion caused by issue #3046 

## Proposed PR background

The issue form asks for multiple browsers to be selected but only one selection can be made. This change indicates that one browser should be selected.

### CODE REVIEW

**Comment by karlcow** [comment]
@tagawa Could you open an issue and then change the commit messages to link to that issue. :) Thanks

**Comment by tagawa** [comment]
@karlcow Not sure I understand – I linked to the existing issue #3046 in the PR.

**Comment by tagawa** [comment]
@karlcow Oh, maybe you mean you want a dedicated issue for the for message itself, so it can be closed leaving #3046 open? I can do that. Seems a bit bureaucratic though.

**Comment by karlcow** [comment]
It's because the scope of #3046 is different. 
#3046 is about adding the multi-browser feature.
Fixing #3046 will mean removing your commit :)

**Comment by tagawa** [comment]
Thanks for the explanation – I'll follow your instructions.

**Pull request closed without merging**
