### PR TITLE
Fixes #2098 - fixed position of search-bar

### LINKED ISSUE #2098: Search form on home page is out of view
1. Go to home page
2. Click on search.

The search area disappears outside of the page.

capture d ecran 2018-02-16 a 12 25 20 2

### PR DESCRIPTION
**Pull request by magsout**
r @zoepage for css fix
r @karlcow to be sure the bug is fix ;)

fixes #2098

### CODE REVIEW

**Comment by zoepage** [comment]
screen shot 2018-02-19 at 10 41 11 am

screen shot 2018-02-19 at 10 41 55 am

I still can reproduce. 🤔

**Comment by magsout** [comment]
@zoepage sorry for this bad PR.. I'll check, thanks.

**Comment by magsout** [comment]
@zoepage new commit.

**Comment by zoepage** [comment]
I can still reproduce on mobile and the closing SVG is also still a bit off. Am I missing something? 🤔
Happy to help where ever you need anything! :)

**Comment by magsout** [comment]
What I see, is different from you?

screen recording 2018-02-21 at 06 31 pm

**Comment by zoepage** [comment]
Probably same issue with the caching again. SORRY!

Thank you!!!

**Pull request merged**
