### PR TITLE
#1425 - join team icon display

### PR DESCRIPTION
**Pull request by bastianalbers**
This addresses some of the issues in https://github.com/webcompat/webcompat.com/issues/1425

- removed the text from the svg icons
- fixed issues with flex display and incosistent sizes of icon box by adding an extra wc-Threesteps-item-icon class

Probably still needs to be adjusted with design eye: icon/box sizes.

### CODE REVIEW

**Comment by karlcow** [comment]
The modified 3 icons.
capture d ecran 2017-03-28 a 07 40 45

The current PR is trying to adjust the icons through CSS, but not by remaking the SVG (to make them regular). I wonder if it will bite us in the future. We need to check how it looks too.

**Comment by bastianalbers** [comment]
Yes, the SVGs themselves need some work. I tried to Provide a fix for now as the boxes were varying heavily, but i lack the actual SVG editing skills (and tools) to properly modify those paths. I'll try to have another look on those though.

**Comment by zoepage** [comment]
I feel like this is already an improvement to the actual state. 
As long as we keep this is mind and an issue open for this, we should be good, I guess?

@bastianalbers 
screen shot 2017-03-28 at 1 36 42 pm

Did you check Safari? Seems something is not right there. :/

**Comment by miketaylr** [comment]
> As long as we keep this is mind and an issue open for this, we should be good, I guess?

I think that sounds like a good way forward.

**Comment by zoepage** [comment]
As this is not solving #1425, but improving the actual state and we agreed on merging, I did edit the title to not close the bug. This still needs to be improved. 

Thanks @bastianalbers for your help :)

**Pull request merged**
