### PR TITLE
Issue #3113 - Improved config/environment.py - by avoiding import *

### PR DESCRIPTION
**Pull request by apsychogirl**
Fixes - #3113

### CODE REVIEW

**Comment by miketaylr** [comment]
Thanks for the patch! @apsychogirl -- the python unit tests are failing now after making this change. https://github.com/webcompat/webcompat.com/blob/master/docs/tests.md#running-tests has directions for how to run tests locally, which will be helpful when fixing them. :)

(likely the failures mean more needs to be namespaced against `cfg`)

**Comment by apsychogirl** [comment]
Hi, while running tests locally, I am getting this one issue
image

**Comment by karlcow** [comment]
@apsychogirl yes this is one of the errors. It says KeyError. The config is a big [python dictionary](https://docs.python.org/2/tutorial/datastructures.html#dictionaries). So it says it can't find `GITHUB_CLIENT_ID`.

Did you do this?
https://github.com/webcompat/webcompat.com/blob/master/docs/dev-env-setup.md#store-your-settings


Try to fix the other errors first.

**Comment by apsychogirl** [comment]
@karlcow I have resolved other errors. For this [https://github.com/webcompat/webcompat.com/blob/master/docs/dev-env-setup.md#store-your-settings] , I am unable to find .env file. And if I try to modify flask_github.py, the error persists even if I put client Id secret and auth token.

**Comment by karlcow** [comment]
@apsychogirl about `.env`, you need to create it yourself. This is where the private stuff is kept. And it will not be committed if you kept the `.gitignore`.

> And if I try to modify flask_github.py

do not. 🚫 This is part of the external libraries and should not be touched in anyways. 

>  Also while creating my local application, what HOMEPAGE URL should be mentioned?

You do not need to modify most the things. What do you mean by HOMEPAGE URL


> I have resolved other errors.

Could you push your new modifications, so I can see what remains to be fixed. It would be easier to help you. no worries, you will not break anything. Thanks!

**Comment by apsychogirl** [comment]
> > Also while creating my local application, what HOMEPAGE URL should be mentioned?
> 
> >You do not need to modify most the things. What do you mean by HOMEPAGE URL
>
>This was in the regard of trying to run the application on my localhost as mentioned in the second step of (https://github.com/webcompat/webcompat.com/blob/master/docs/dev-env-setup.md#store-your-settings)

**Comment by apsychogirl** [comment]
Closing this PR and opening a fresh one.

**Comment by miketaylr** [comment]
@apsychogirl it looks like your latest push just failed on linting:

```
config/__init__.py:55:80: E501 line too long (82 > 79 characters)
```

If you run the command `pycodestyle --ignore=E402,W504 webcompat/ tests/ config/` you should be able to see and fix these locally.

(I think the answer to your question about HOMEPAGE_URL is probably `http://localhost:5000/callback`, if you are referring to step 2 of https://github.com/webcompat/webcompat.com/blob/master/docs/dev-env-setup.md#store-your-settings)

**Pull request closed without merging**
