### PR TITLE
Fixes #1044. Request max of 100 comments per issue.

### LINKED ISSUE #1044: Only 30 comments shown for an issue on the webcompat site
Compare the number of comments shown here: 
https://github.com/webcompat/web-bugs/issues/1470
and here:
https://webcompat.com/issues/1470

The webcompat site seems to show only the first 30 or so.

### PR DESCRIPTION
**Pull request by miketaylr**
r? @hallvors 

I'll file a follow up to do this "the right way".

### CODE REVIEW

**Comment by miketaylr** [comment]
Filed https://github.com/webcompat/webcompat.com/issues/1058 as a follow up.

**Comment by miketaylr** [comment]
Huh, this breaks tests. Will investigate later.

**Comment by hallvors** [comment]
Tests break because the patch changes the URL we ask for - so we need to also update file names of some mockup fixtures..

**Comment by hallvors** [comment]
3 files to rename:

```
127.0.0.1 - - [20/May/2016 16:11:05] "GET /api/issues/100/comments?per_page=100 HTTP/1.1" 500 -
IOError: [Errno 2] No such file or directory: u'/home/travis/build/webcompat/webcompat.com/tests/fixtures/api/issues/100/comments.6665c4820456e6a813dcbbdddd690ffc.json'


127.0.0.1 - - [20/May/2016 16:11:18] "GET /api/issues/101/comments?per_page=100 HTTP/1.1" 500 -
IOError: [Errno 2] No such file or directory: u'/home/travis/build/webcompat/webcompat.com/tests/fixtures/api/issues/101/comments.6665c4820456e6a813dcbbdddd690ffc.json'

127.0.0.1 - - [20/May/2016 16:12:36] "GET /api/issues/252/comments?per_page=100 HTTP/1.1" 500 -
IOError: [Errno 2] No such file or directory: u'/home/travis/build/webcompat/webcompat.com/tests/fixtures/api/issues/252/comments.6665c4820456e6a813dcbbdddd690ffc.json'
```

**Comment by hallvors** [comment]
(apart from that r+ of course - aiming for a better fix later)

**Comment by miketaylr** [comment]
Oh right, Fixtures. 📦 
Thx @hallvors, will update then merge.

**Pull request merged**
