### PR TITLE
Fixes #1268 - fix functional tests about MD markup when uploading images

### LINKED ISSUE #1268: Fix failing image upload tests
Busted from merging https://github.com/webcompat/webcompat.com/pull/1266

https://travis-ci.org/webcompat/webcompat.com/builds/189375239

https://github.com/webcompat/webcompat.com/blob/master/tests/functional/image-uploads-non-auth.js (fixing this would effectively fix half of https://github.com/webcompat/webcompat.com/issues/1267.

cc @karlcow

### PR DESCRIPTION
**Pull request by karlcow**
And that's one part fixed.

### CODE REVIEW

**Comment by miketaylr** [comment]
Hmm, still failing when I run these locally.

`[Screenshot Description]()`

```
× firefox 49.0 on MAC 15.6.0 - Image Uploads (non-auth) - postMessaged dataURI image upload worked
AssertionError: The data URI was correctly uploaded and its URL was copied to the bug description.: expected '1. Navigate to: Site URL\n2. …\n\nExpected Behavior:\n\nActual Behavior:\n\n\n[![Screenshot Description]()]()' to include '[![Screenshot Description](http://localhost:5000/uploads/'
  at Function.assert.include  <node_modules/intern/node_modules/chai/chai.js:2977:45>
  at CompatCommand.<anonymous>  <tests/functional/image-uploads-non-auth.js:76:18>
  at runCallback  <node_modules/leadfoot/Command.js:509:31>
  at CompatCommand.<anonymous>  <node_modules/leadfoot/Command.js:526:11>                       
  at <node_modules/leadfoot/node_modules/dojo/Promise.js:235:37>
  at runCallbacks  <node_modules/leadfoot/node_modules/dojo/Promise.js:11:18>
  at <node_modules/leadfoot/node_modules/dojo/Promise.js:188:17>
  at run  <node_modules/leadfoot/node_modules/dojo/Promise.js:131:29>
  at <node_modules/leadfoot/node_modules/dojo/nextTick.js:30:13>
  at nextTickCallbackWith0Args  <node.js:420:9>
  at new CompatCommand  <node_modules/intern/runner.js:213:14>
  at CompatCommand.Command.then  <node_modules/leadfoot/Command.js:525:10>
  at Test.registerSuite.postMessaged dataURI image upload worked [as test]  <tests/functional/image-uploads-non-auth.js:75:10>
  at Test.run  <node_modules/intern/lib/Test.js:169:19>
  at <node_modules/intern/lib/Suite.js:237:13>
  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>
  at Promise.then.promise.then  <node_modules/intern/node_modules/dojo/Deferred.js:258:5>
  at runTest  <node_modules/intern/lib/Suite.js:236:46>
  at <node_modules/intern/lib/Suite.js:249:7>
  at nextTickCallbackWith0Args  <node.js:420:9>
  at new CompatCommand  <node_modules/intern/runner.js:213:14>
  at CompatCommand.Command.end  <node_modules/leadfoot/Command.js:475:10>
  at Test.registerSuite.postMessaged dataURI image upload worked [as test]  <tests/functional/image-uploads-non-auth.js:78:10>
  at Test.run  <node_modules/intern/lib/Test.js:169:19>
  at <node_modules/intern/lib/Suite.js:237:13>
  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>
  at Promise.then.promise.then  <node_modules/intern/node_modules/dojo/Deferred.js:258:5>
  at runTest  <node_modules/intern/lib/Suite.js:236:46>
  at <node_modules/intern/lib/Suite.js:249:7>
  at nextTickCallbackWith0Args  <node.js:420:9>
× firefox 49.0 on MAC 15.6.0 - Image Uploads (non-auth) - postMessaged blob image upload worked
AssertionError: The data URI was correctly uploaded and its URL was copied to the bug description.: expected '1. Navigate to: Site URL\n2. …\n\nExpected Behavior:\n\nActual Behavior:\n\n\n[![Screenshot Description]()]()' to include '[![Screenshot Description](http://localhost:5000/uploads/'
  at Function.assert.include  <node_modules/intern/node_modules/chai/chai.js:2977:45>
  at CompatCommand.<anonymous>  <tests/functional/image-uploads-non-auth.js:108:18>
  at runCallback  <node_modules/leadfoot/Command.js:509:31>
  at CompatCommand.<anonymous>  <node_modules/leadfoot/Command.js:526:11>
  at <node_modules/leadfoot/node_modules/dojo/Promise.js:235:37>
  at runCallbacks  <node_modules/leadfoot/node_modules/dojo/Promise.js:11:18>
  at <node_modules/leadfoot/node_modules/dojo/Promise.js:188:17>
  at run  <node_modules/leadfoot/node_modules/dojo/Promise.js:131:29>
  at <node_modules/leadfoot/node_modules/dojo/nextTick.js:30:13>
  at nextTickCallbackWith0Args  <node.js:420:9>
  at new CompatCommand  <node_modules/intern/runner.js:213:14>
  at CompatCommand.Command.then  <node_modules/leadfoot/Command.js:525:10>
  at Test.registerSuite.postMessaged blob image upload worked [as test]  <tests/functional/image-uploads-non-auth.js:107:10>
  at Test.run  <node_modules/intern/lib/Test.js:169:19>
  at <node_modules/intern/lib/Suite.js:237:13>
  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>
  at Promise.then.promise.then  <node_modules/intern/node_modules/dojo/Deferred.js:258:5>
  at runTest  <node_modules/intern/lib/Suite.js:236:46>
  at <node_modules/intern/lib/Suite.js:249:7>
  at nextTickCallbackWith0Args  <node.js:420:9>
  at new CompatCommand  <node_modules/intern/runner.js:213:14>
  at CompatCommand.Command.end  <node_modules/leadfoot/Command.js:475:10>
  at Test.registerSuite.postMessaged blob image upload worked [as test]  <tests/functional/image-uploads-non-auth.js:110:10>
  at Test.run  <node_modules/intern/lib/Test.js:169:19>
  at <node_modules/intern/lib/Suite.js:237:13>
  at signalListener  <node_modules/intern/node_modules/dojo/Deferred.js:37:21>
  at Promise.then.promise.then  <node_modules/intern/node_modules/dojo/Deferred.js:258:5>
  at runTest  <node_modules/intern/lib/Suite.js:236:46>
  at <node_modules/intern/lib/Suite.js:249:7>
  at nextTickCallbackWith0Args  <node.js:420:9>
```

**Comment by miketaylr** [comment]
To reproduce the test locally, you can just paste the following into the console:

`postMessage("data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAABkAAAAZCAIAAABLixI0AAAACXBIWXMAAA7DAAAOwwHHb6hkAAAAB3RJTUUH3gYSAig452t/EQAAAClJREFUOMvtzkENAAAMg0A25ZU+E032AQEXoNcApCGFLX5paWlpaWl9dqq9AS6CKROfAAAAAElFTkSuQmCC", "http://localhost:5000")`

**Comment by miketaylr** [comment]
Seems like image uploads from the bug form are broken now, but image uploads from an issue are working. 

@karlcow had you tested the report issue form?

**Comment by karlcow** [comment]
Closing in favor of #1271

**Pull request closed without merging**
