### PR TITLE
Hallvors/quotefix

### PR DESCRIPTION
**Pull request by hallvors**
a very minor contribution :)

### CODE REVIEW

**Comment by miketaylr** [comment]
Thanks! :)

**Comment by miketaylr** [comment]
Oops, I just noticed there's a conflict. Can you rebase against the latest master, @hallvors?

**Comment by hallvors** [comment]
I'm confused. I just created a branch here in the Github UI to fix a couple of small issues (starting from a search) but apparently I was basing that branch on an older codebase or something..?

**Comment by miketaylr** [comment]
@hallvors it depends on when the last time you updated your fork against "upstream" (or this repo). 

I'm sure you already know how to do all this, but here's some helpful links:

https://help.github.com/articles/configuring-a-remote-for-a-fork/
https://help.github.com/articles/syncing-a-fork/

**Comment by miketaylr** [comment]
(Um, actually now I see that this wasn't from a forked repo? -- sorry, I shouldn't be looking at GitHub at the airport :airplane:)

**Comment by hallvors** [comment]
Yes, I wouldn't be surprised if I was working off a local branch or fork from a while ago. But creating a new branch from Github's UI and suddenly be working on code from several months (years?) ago was unexpected..

**Pull request closed without merging**
