### PR TITLE
Fixes #660. Move all label namespace handling to models.

### LINKED ISSUE #660: Handle label namespacing at model level
We should only make namespaced label conversions just before talking to the API or just after receiving data from it.

### PR DESCRIPTION
**Pull request by miketaylr**
I want to add some tests to this before we merge.

r? @karlcow

### CODE REVIEW

**Comment by karlcow** [comment]
Ah interesting. I would have thought of putting it on the python side more than the JS side. 
but cool! At least it's a working solution. :heart: 
Tests are to be added in #272 ?

**Comment by miketaylr** [comment]
Hitting every nail with my JS :hammer: 

> Tests are to be added in #272 ?

Yeah, we can do that. How long do you think until you can commit the first simple test? @ https://github.com/karlcow/webcompat.com/commit/5e2ae26c225653fd2ade32f9b05e8d69a8d7b1b0

I can add some more tests specific to the changes in this PR after that.

You mentioned there was a problem with Issue 100, can you explain that again? Maybe I should move the test repo to webcompat...

**Comment by karlcow** [comment]
> Yeah, we can do that. How long do you think until you can commit the first simple test? @ karlcow@5e2ae26 

You mean a Pull request? Because it is committed. :)

> You mentioned there was a problem with Issue 100, can you explain that again? Maybe I should move the test repo to webcompat...

Let me reply in #648

**Comment by miketaylr** [comment]
Yes, a PR.

**Comment by karlcow** [comment]
Here it is sir. :) https://github.com/webcompat/webcompat.com/pull/662

**Comment by karlcow** [comment]
Note for the future. I need to propose something where we handle this on the API side in the python code. More logical and less duplication of code.

**Comment by miketaylr** [comment]
@karlcow is working on tests, so let's go ahead and pull this in so he's not working against a version of the tree that is going to change.

**Pull request merged**
