### PR TITLE
Fixes #2473. Markup fixes (SVG alternatives, invalid code, unnecessary `role="button"`, account dropdown trigger)

### PR DESCRIPTION
**Pull request by patrickhlauke**
Issue #2483  - fixes incorrect/unnecessary SVG alternative text,  removes invalid `aria-role="hide"`, removes unnecessary `role="button"` on `<button>` elements, fixes up the currently broken aria on the account dropdown trigger

r? @miketaylr
---

- [x ] I have read the [Pull Request + Code Style Guidelines](https://github.com/webcompat/webcompat.com/blob/master/docs/pr-coding-guidelines.md) thoroughly.

### CODE REVIEW

**Comment by zoepage** [comment]
Thanks @patrickhlauke for your work <3

Just to give some context, the SVG title were added due to a SVG bug in Firefox nightly 59 (AFAIR).
On hover the SVG disappeared. I might be worth checking, just to be sure if this still happens.

**Comment by patrickhlauke** [comment]
worst case, `<title>` can be kept, as it would be neutralised by the `aria-hidden="true"` on the `<svg>` itself.

not sure about the failure @TravisBuddy is reporting there. is the test that fails looking for specific html that was optimized away?

**Comment by patrickhlauke** [comment]
worked out what the deal was with the failing unit test, i think...

**Comment by karlcow** [comment]
Ah cool! This replicates part of the pull request in  #2473.
Let's get rid of mine and take @patrickhlauke 's one.
@patrickhlauke long time no see. ❤️

**Comment by patrickhlauke** [comment]
:+1: ❤️

**Comment by miketaylr** [comment]
> h cool! This replicates part of the pull request in #2473.
> Let's get rid of mine and take @patrickhlauke 's one.

Cool, I'll do that.

**Comment by miketaylr** [comment]
> might be worth checking, just to be sure if this still happens.

I don't see this bug.

**Comment by miketaylr** [comment]
Oops, I linked the wrong issue. :P

**Pull request merged**
