### PR TITLE
Issue #848 - Add style to cssfixme service

### PR DESCRIPTION
**Pull request by magsout**
## Before:

capture d ecran 2015-12-29 a 17 49 00

## After:

capture d ecran 2015-12-29 a 17 40 19

We can improve it,it's a lick of paint

r? @karlcow @miketaylr @calexity @hallvors @tagawa

### CODE REVIEW

**Comment by magsout** [comment]
@miketaylr why I have to restart build each time ? if not, travis are not happy

**Comment by miketaylr** [comment]
> @miketaylr why I have to restart build each time ? if not, travis are not happy

I need to figure that out.... :( something weird about the search tests that fail every-other-time...

**Comment by miketaylr** [comment]
r+, looks so much better!

**Comment by karlcow** [comment]
r+ with minor suggestions on the prose organization. Something along these lines

Let's put the big pile of text at the end of the page. 
capture d ecran 2015-12-30 a 14 23 46

**Comment by magsout** [comment]
Nice @karlcow . What about output (résultat) ? Between Button and the text ?

**Comment by karlcow** [comment]
Yes the output should come between the button and the text. Basically the text is always at the bottom.

**Comment by magsout** [comment]
ok @karlcow good.

**Pull request merged**
