### PR TITLE
Fixes #1043. Add first parts of func test suite for image uploads.

### LINKED ISSUE #1043: Functional tests for postMessage'd screenshots from Add-on
Things to test:

- [ ] validation 
- [x]  <s>removing upload data</s> (I don't think this is possible without re-writing BugForm.js to expose `screenshotData` to the outside world. Not sure if we want to do that).
- [x] removing upload preview
- [ ] file image preview
- [x] postMessage'd data preview

### PR DESCRIPTION
**Pull request by miketaylr**
This tests showing and removing image previews of screenshots that come from add-ons.

### CODE REVIEW

**Comment by miketaylr** [comment]
(holding off on review, I want to see if this timeout failure happens again on Travis -- this passes locally for me)

**Comment by miketaylr** [comment]
I need to look at this again after the fix for #1049 lands -- things have changed.

**Comment by karlcow** [comment]
grmph

## First pass
capture d ecran 2016-05-26 a 09 58 44

```
× firefox 46.0.1 on MAC - Image Uploads (non-auth) - postMessaged dataURI image upload worked
× firefox 46.0.1 on MAC - Issues - Issue page loads
× firefox 46.0.1 on MAC - Search (auth) - Search from the homepage
× firefox 46.0.1 on MAC - Search (auth) - Search/filter interaction
```

## Second pass
Let's try another one. :)

capture d ecran 2016-05-26 a 10 10 25

```
× firefox 46.0.1 on MAC - Search (auth) - Search works
× firefox 46.0.1 on MAC - Issues - Issue page loads
× firefox 46.0.1 on MAC - Image Uploads (non-auth) - postMessaged dataURI image upload worked
```

@miketaylr `× firefox 46.0.1 on MAC - Image Uploads (non-auth) - postMessaged dataURI image upload worked` seems to fail consistently. What's happening for your when running locally.

**Comment by miketaylr** [comment]
They pass for me locally. :/

Don't worry about spending more time on this for now, I'll come back to it.

**Comment by miketaylr** [comment]
(also thanks for attempting review!)

**Comment by miketaylr** [comment]
> All checks have passed

(Also, they passed on Travis.)

**Comment by deepthivenkat** [comment]
https://gist.github.com/deepthivenkat/d3c7f36db8259a92327b5688ed5e6d12

**Comment by karlcow** [comment]
ah @deepthivenkat has a similar failure. Hypothesis. The setup we are using for working is different. Or the way we proceed for starting the tests. 

Or… another silly theory… network issues, aka @miketaylr is "local" and we are "distant".

**Comment by karlcow** [comment]
I will merge because it's working on Travis, but it would be good to figure out what's happening.

**Pull request merged**
