### PR TITLE
Fork browserstack2

### PR DESCRIPTION
**Pull request by cch5ng**
only a test to see if running travis tests using npm script works (fork nonauth)
previously, most tests were failing

### CODE REVIEW

**Comment by cch5ng** [comment]
closing because the main purpose was testing the travis-selenium-firefox non auth tests

* stuck on how to get the travis-selenium tests to run, this set was broken after I updated the intern configs => broken out to 3 files (intern.js, intern-chrome.js, and intern-firefox.js)

* the current organization is intern.js has the default configs for browserstack, because otherwise I could not run the browserstack tests from the last .travis.yml lines without exposing the travis env vars for github auth

* however this way, the intern-firefox.js file is overriding the intern.js file and I'm pretty sure the issue is the intern.tunnel property because usually the travis-selenium environment did not require a tunnel when it was the default test env (not sure if "NullTunnel" should work or not or how to reset that field value to default)
  * there's an open PR on intern/digdug for a selenium tunnel, not sure if this would resolve the issue
  * https://github.com/theintern/digdug/pull/27
  * https://github.com/theintern/digdug/issues/19

* if I make the intern.js contain the default travis-selenium-firefox environ configs, then I'm not sure how to call the browserstack tests without exposing the travis github auth vars...

**Comment by cch5ng** [comment]
@miketaylr I think I am stuck with the current scripts using intern/travis configs for browserstack. the way the intern configs were broken out was to keep the travis env vars hidden for auth tests but for some reason I am not successful now running the forked repo tests on travis. 

not sure if my script syntax is bad at the end of .travis.yml or probably my intern config override is bad (intern-firefox.js, which overrides intern.js).

**Comment by cch5ng** [comment]
this was the last version of intern.js before it was broken into environment specific versions:
(I am pretty sure with the current organization of firefox intern version overriding browserstack intern version, that the tunnel property causes an issue but am not sure how to work around it)

/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

// Learn more about configuring this file at <https://github.com/theintern/intern/wiki/Configuring-Intern>.
// These default settings work OK for most people. The options that *must* be changed below are the
// packages, suites, excludeInstrumentation, and (if you want functional tests) functionalSuites.
define(['intern/lib/args'], function(args) {
  'use strict';

  var siteRoot = args.siteRoot ? args.siteRoot : 'http://localhost:5000';

  return {
    // Configuration object for webcompat
    wc: {
      pageLoadTimeout: args.wcPageLoadTimeout ? parseInt(args.wcPageLoadTimeout, 10) : 10000,
      // user and pw need to be passed in as command-line arguments. See CONTRIBUTING.md
      user: args.user || 'some username',
      pw: args.pw || 'some password'
    },

    // The port on which the instrumenting proxy will listen
    proxyPort: 9090,

    // A fully qualified URL to the Intern proxy
    proxyUrl: 'http://127.0.0.1:9090/',
    siteRoot: siteRoot,

    // Selenium vers on BrowserStack
    capabilities: {
      'browserstack.selenium_version': '2.52.0'
      //'browserstack.selenium_version': '2.45.0'
    },

    // Required for BrowserStack, Maximum number of simultaneous integration tests allowed
    maxConcurrency: 2,

    environments: [
      //for local selenium server testing only
      //{ browserName: 'firefox'}
      // Additional environments for BrowserStack only
      //{ browser: 'firefox', browser_version: '44', os : 'OS X', os_version : 'El Capitan' }//,
      { browser: 'chrome', browser_version: '50', os : 'OS X', os_version : 'El Capitan' }//,
    ],

    // Required for BrowserStack (comment out for local testing)
    //tunnel: 'BrowserStackTunnel',

    // For local chrome driver test only (comment out for BrowserStack)
    tunnel: 'NullTunnel',
    // For local chrome driver test only (comment out for BrowserStack)
    tunnelOptions: {
      host: 'http://127.0.0.1',
      port: '4444',
      path: '/wd/hub'
    },

    // Beauty, Bob.
    reporters: 'pretty',

    // Unless you pass in a command-line arg saying otherwise, we run all tests by default.
    functionalSuites: [ 'tests/functional-all' ],

    // A regular expression matching URLs to files that should not be included in code coverage analysis
    excludeInstrumentation: /./
  };

});

**Comment by miketaylr** [comment]
> not sure if my script syntax is bad at the end of .travis.yml

Have you tried this thing? https://lint.travis-ci.org/

**Comment by cch5ng** [comment]
> Have you tried this thing? https://lint.travis-ci.org/

Thanks, I was not aware of that tool. I tried and the .travis.yml is passing. I will look again at the other project's intern file for travis tests b/c I think running the tests locally seemed to work.

**Pull request closed without merging**
