### PR TITLE
Improve layout qrCode

### PR DESCRIPTION
**Pull request by magsout**
r? @tagawa

### CODE REVIEW

**Comment by miketaylr** [comment]
It looks like this would close #651 and #649. :+1:

**Comment by magsout** [comment]
just one thing @miketaylr there is one error when I add `qrcode.js` in the linter about `    var qrDataUrl = qr.toDataURL({value: this.url, size: 8});`  `qr` is not init, if you can take a look.

**Comment by miketaylr** [comment]
Will take a look today.

**Comment by miketaylr** [comment]
@magsout just needed to add `qr` to the list of allowed globals. All good now.

**Comment by miketaylr** [comment]
One day we'll move to modules and stop leaking globals everywhere. :P

**Comment by miketaylr** [comment]
(Don't worry about failing tests here, lots of moving parts unrelated to these changes -- we'll make sure everything is passing before deploying).

**Comment by magsout** [comment]
😎

**Comment by magsout** [comment]
>One day we'll move to modules and stop leaking globals everywhere. :P

🙏

**Comment by magsout** [comment]
Ping @tagawa 👌

**Comment by tagawa** [comment]
Thanks @magsout, will try to look at it later.

**Comment by miketaylr** [comment]
LGTM. Stealing this from @tagawa, if he doesn't mind.

**Comment by tagawa** [comment]
Thanks @miketaylr. Sorry &mdash; difficult to find time at the moment.
Feel free to "Sacre bleu, les anglais!" and stuff like that.

**Comment by magsout** [comment]
:heart:

**Comment by miketaylr** [comment]
@tagawa no worries! we all have busy and less busy seasons. :gb:

**Pull request merged**
