### PR TITLE
Fix #1205: Remove unused screenshot.js

### LINKED ISSUE #1205: Remove test/screenshots.js and test/screenshots.json
I think this is unused?

@magsout do you use this?

### PR DESCRIPTION
**Pull request by haseebgit**
@miketaylr r?

### CODE REVIEW

**Comment by miketaylr** [comment]
Thanks @haseebgit! In the future, can you write a descriptive commit message and PR title?

For this one, you could write:

PR title: "Fix 1205: Remove unused screenshot.js"

And the commit message could be:

"Issue #1205. Remove unused screenshot.js"

The reason being, if someone was exploring the git commit history, it would be very hard to know what this specific commit did without inspecting the actual changes.

**Comment by miketaylr** [comment]
(if you're still using the web interface, I'm not sure if you can easily change the commit message - do you know if that's possible?)

**Comment by haseebgit** [comment]
@miketaylr I'm fixing it locally

**Comment by miketaylr** [comment]
Sweet. Then it should be as simple as `git commit --amend`, fixing the commit message, then `git push -f`

**Comment by haseebgit** [comment]
@miketaylr can you please review now? I will fix the other PR's if this is fine :)

**Comment by miketaylr** [comment]
Thank you!

**Pull request merged**
