### PR TITLE
Issue #900 - postcss-cssnext

### LINKED ISSUE #900: Move to postcss-cssnext
Grunt-cssnext is deprecated 

See http://cssnext.io/postcss/

### PR DESCRIPTION
**Pull request by magsout**
`grunt-cssnext` is depreacted, so I added `postcss-cssnext`

Instrcutions:

```console
npm uninstall grunt-cssnext
npm install
make build
```

r? @miketaylr 

Close #900

### CODE REVIEW

**Comment by miketaylr** [comment]
LGTM (everything works as expected locally)

**Comment by miketaylr** [comment]
(we might have to clear the Travis cache if the tests fail post-merge)

**Comment by magsout** [comment]
poke @webcompat/collaborators 

```
npm uninstall grunt-cssnext
npm install
make build
```

cc @webcompat/collaborators  @dstreet @StabbyMcDuck @tsah20 @deepthivenkat @cch5ng @dshgna

**Comment by miketaylr** [comment]
In theory our `checkDependencies` grunt task should catch this -- in theory with something like:

```
🐓 grunt
Loading "cssnext.js" tasks...ERROR
>> Error: Cannot find module 'postcss-cssnext'

Running "checkDependencies:default" (checkDependencies) task
>> postcss-cssnext: not installed!
>> Invoke npm install to install missing packages
Warning: Task "checkDependencies:default" failed. Use --force to continue.
```

But not a bad idea to remove `grunt-cssnext`

**Comment by magsout** [comment]
Ah yes good point

**Pull request merged**
