### PR TITLE
Fixes #1505 remove unused query-params.js

### LINKED ISSUE #1505: Remove query-params.js file
This code has never been actually used. So lets remove it.

(FTR, it has some great ideas in it, possibly something we want to revisit during a refactor).

https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/js/lib/models/query-params.js

### PR DESCRIPTION
**Pull request by cch5ng**
r? @miketaylr

### CODE REVIEW

**Comment by cch5ng** [comment]
@miketaylr I'm also currently assigned to #1565 and am still searching through the code to understand what part of the code to update (change the api request parameters or filter the api response). but I was wondering do you think I should keep any of this removed file for filtering out media-type labelled issues from the webcompat.com issues list?

I did not look closely into the contents of query-params.js for this pr but can look again.

**Comment by cch5ng** [comment]
@miketaylr nvm, I think I found in github api docs info about the question I had earlier. I think it should be ok to just review this file removal.

**Comment by cch5ng** [comment]
@miketaylr done

> Can you update the commit message to mention the query-params.js file

**Comment by miketaylr** [comment]
Thanks!

**Pull request merged**
