### PR TITLE
Fixes #1191: Fix broken link to CouchDB CONTRIBUTING file in CONTRIBUTING.md

### LINKED ISSUE #1191: Fix broken link to CouchDB CONTRIBUTING file in CONTRIBUTING.md
https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#acknowledgements

Not sure where it went, so to fix this issue, ideally we could find out where it was moved to. Or, if it's gone forever, remove the link.

### PR DESCRIPTION
**Pull request by dacharya64**
Document no longer exists, so removed link. r? @miketaylr

### CODE REVIEW

**Comment by miketaylr** [comment]
Any reason you closed this @dacharya64?

**Comment by dacharya64** [comment]
My bad -- was a mistake. :)

**Comment by miketaylr** [comment]
> My bad -- it should be good to go.

Sweet, let me see how to clean up the history a bit.

**Comment by miketaylr** [comment]
Cool, just had to rebase against your master branch with the following command:

`git pull --rebase origin master` (which replays the commits on this branch onto what got pulled in from master, which is currently up to date with webcompat.com)

And then pushed that back to the `issues/1191` branch with `git push -f`.

**Comment by miketaylr** [comment]
LGTM, thanks @dacharya64!

**Pull request merged**
