### PR TITLE
[WIP] #980 fork browserstack2 update intern/travis configs for chrome…

### PR DESCRIPTION
**Pull request by cch5ng**
(commit comment cont'd)… testing
separate intern configs by test env
add npm run scripts by test env
add timeout to login helper for manual github 2fa auth code entry
test browserstack sup fix for firefox breaking test issues-non-auth.js
update intern version because of browserstack tunnel err

### CODE REVIEW

**Comment by cch5ng** [comment]
@miketaylr hi, I have one known issue on travis-browserstack as of last test before 070416 (firefox pressing 'g' to redirect page). I'm not sure about multiple local test failures (both firefox and chrome). but I think this is mainly what is necessary for the browserstack configs.

need to update CONTRIBUTING.md but these are new test commands:
`npm test user='a user' pw='a pwd' ` (for local firefox all)
`npm run test-chrome -s user='a user' pw='a pwd' ` (for local chrome all)
`npm run test-functional-nonauth -s` (for local firefox non auth)

**Comment by cch5ng** [comment]
@miketaylr for the script conditions at the bottom of .travis.yml should I expect that

if [ "$TRAVIS_SECURE_ENV_VARS" == "false" ] ===> this case should run the tests on travis/firefox?
if [ "$TRAVIS_SECURE_ENV_VARS" == "true" ] ===> this case should run the tests on browserstack?

**Comment by cch5ng** [comment]
I need to fix the travis script pointer for non auth tests

also need to update configs for new selenium, firefox versions in readme

**Comment by cch5ng** [comment]
closing b/c this was a test to verify non auth test trigger
also needs more changes

**Comment by cch5ng** [comment]
> for the script conditions at the bottom of .travis.yml should I expect that
> if [ "$TRAVIS_SECURE_ENV_VARS" == "false" ] ===> this case should run the tests on travis/firefox?

I will double check w/ browserstack support what the expectation should be. I thought the non auth tests should run on browserstack but did not observe this in earlier logs.

**Comment by miketaylr** [comment]
> I thought the non auth tests should run on browserstack but did not observe this in earlier logs.
 
Hm, that's what I would expect as well.

**Comment by cch5ng** [comment]
> I thought the non auth tests should run on browserstack but did not observe this in earlier logs.

> Hm, that's what I would expect as well.

found: it's a travis policy not to transmit encrypted data for fork PR's so the browserstack tunnel is not getting the browserstack auth credentials. 

https://docs.travis-ci.com/user/pull-requests#Security-Restrictions-when-testing-Pull-Requests
https://docs.travis-ci.com/user/encryption-keys/#Usage

(2nd link is what was used to encrypt the browserstack auth info)

but as with the last fork test, the local firefox intern config can be used. so tests will still get run (on travis but not on chrome).

so pushes from webcompat members will go to browserstack (including the non auth tests) but community members' PR's will only go to travis (is that OK?). sorry if it was not worded clearly initially but I think you had alluded to this, I just didn't understand why this was happening.

**Pull request closed without merging**
