### PR TITLE
Fixes #1482: Fixes length and quote style issues

### LINKED ISSUE #1482: Fix missing docstrings on the python files.
On #1473 there was a discussion about the project having missing docstrings. We didn't create docstrings for all the functions.

The output on view was. 

```
`pep257 webcompat/views.py`
`webcompat/views.py:1 at module level:
        D100: Missing docstring in public module
webcompat/views.py:40 in public function `shutdown_session`:
        D103: Missing docstring in public function
webcompat/views.py:45 in public function `before_request`:
        D103: Missing docstring in public function
webcompat/views.py:54 in public function `after_request`:
        D103: Missing docstring in public function
webcompat/views.py:62 in public function `token_getter`:
        D103: Missing docstring in public function
webcompat/views.py:69 in public function `format_date`:
        D300: Use """triple double quotes""" (found '''-quotes)
webcompat/views.py:76 in public function `login`:
        D103: Missing docstring in public function
webcompat/views.py:87 in public function `logout`:
        D103: Missing docstring in public function
webcompat/views.py:97 in public function `authorized`:
        D103: Missing docstring in public function
webcompat/views.py:117 in public function `file_issue`:
        D300: Use """triple double quotes""" (found '''-quotes)
webcompat/views.py:127 in public function `index`:
        D300: Use """triple double quotes""" (found '''-quotes)
webcompat/views.py:150 in public function `show_issues`:
        D300: Use """triple double quotes""" (found '''-quotes)
webcompat/views.py:159 in public function `create_issue`:
        D401: First line should be in imperative mood ('Create', not 'Creates')
webcompat/views.py:208 in public function `show_issue`:
        D300: Use """triple double quotes""" (found '''-quotes)
webcompat/views.py:219 in public function `me_redirect`:
        D401: First line should be in imperative mood ('Thi', not 'This')
webcompat/views.py:219 in public function `me_redirect`:
        D300: Use """triple double quotes""" (found '''-quotes)
webcompat/views.py:228 in public function `show_user_page`:
        D400: First line should end with a period (not ':')
webcompat/views.py:228 in public function `show_user_page`:
        D300: Use """triple double quotes""" (found '''-quotes)
webcompat/views.py:250 in public function `show_rate_limit`:
        D103: Missing docstring in public function
webcompat/views.py:268 in public function `download_file`:
        D300: Use """triple double quotes""" (found '''-quotes)
webcompat/views.py:278 in public function `get_test_helper`:
        D300: Use """triple double quotes""" (found '''-quotes)
webcompat/views.py:278 in public function `get_test_helper`:
        D200: One-line docstring should fit on one line with quotes (found 2)
webcompat/views.py:286 in public function `about`:
        D300: Use """triple double quotes""" (found '''-quotes)
webcompat/views.py:294 in public function `privacy`:
        D300: Use """triple double quotes""" (found '''-quotes)
webcompat/views.py:302 in public function `contributors`:
        D300: Use """triple double quotes""" (found '''-quotes)
webcompat/views.py:310 in public function `cssfixme`:
        D400: First line should end with a period (not 'l')
webcompat/views.py:310 in public function `cssfixme`:
        D300: Use """triple double quotes""" (found '''-quotes)
webcompat/views.py:316 in public function `log_csp_report`:
        D300: Use """triple double quotes""" (found '''-quotes)
`
```

There are a couple of recurring issues. 

* [ ] missing docstrings
* [ ] Imperative style
* [ ] length
* [ ] quote styles

### PR DESCRIPTION
**Pull request by nj4710**
This would solve part of the issue. r? @karlcow

### CODE REVIEW

**Comment by karlcow** [comment]
@nj4710 Yes. Do you intend to do all the files or just this one `view.py`?

**Comment by nj4710** [comment]
I will try to complete all the files.

**Comment by nj4710** [comment]
Is there something wrong with this PR? @karlcow

**Comment by karlcow** [comment]
@nj4710 I didn't notice anything wrong with the PR on the `views.py` file.

**Comment by miketaylr** [comment]
@nj4710 you can use this PR to update the rest of the files for length and quote style issues (that way we avoid having a PR for a single file, etc.)

**Comment by nj4710** [comment]
Thanks @miketaylr . I will keep updating this PR

**Comment by miketaylr** [comment]
> Thanks @miketaylr . I will keep updating this PR

Sounds good! Another option is to create a check-list of files that need updating in the original issue, and open small PRs as you make progress towards that. In this case, you can leave out the "Fixes" part of the title and just have something like "Issue #1482: Part 3 - Fix foo for bar module". And once all those land, we can close the #1482 manually.

Whichever you prefer.

**Comment by nj4710** [comment]
@miketaylr I think your idea sounds better. Could you please close this PR. I will open another one for other files. Thanks :)

**Comment by karlcow** [comment]
@nj4710 do you want us to merge this one?

**Comment by nj4710** [comment]
Yes, Please.

**Pull request merged**
