### PR TITLE
Fixes #860. Enable pep8 for Travis (and make eslint task do what we want for JS)

### LINKED ISSUE #860: Enable linting via Travis
eslint + pep8 for now.

### PR DESCRIPTION
**Pull request by miketaylr**
r? @hallvors 

Mostly boring whitespace changes here.

### CODE REVIEW

**Comment by miketaylr** [comment]
Phew, passes tests. :bomb:

**Comment by karlcow** [comment]
+1 for the python part. Thanks @miketaylr

**Comment by miketaylr** [comment]
Bloops, will fix conflicts.

**Comment by miketaylr** [comment]
I'm gonna pull this in w/ @karlcow's r+, it's blocking me from fixing #868.

**Pull request merged**
