### PR TITLE
Fixes #2726 - Handle pagination when fetching labels from GitHub

### LINKED ISSUE #2726: Handle pagination when fetching labels from GitHub
In troubleshooting issue #2482, it seems like the problem may not be in the regex, but rather in the fact that we're only fetching the first 100 labels in our API call.

### PR DESCRIPTION
**Pull request by laghee**
This PR fixes issue #2726 

## Proposed PR background

Since we are not currently fetching all the existing labels with our GitHub repo call when constructing the label editor on an issue page, filtering behavior and selection is wonky. I added a pagination function to `get_issue_labels` and a test to make sure it works correctly. (I included stubs to expand into eventual testing of the other label functions as well.)

---

- [✅] I have read the [Pull Request + Code Style Guidelines](https://github.com/webcompat/webcompat.com/blob/master/docs/pr-coding-guidelines.md) thoroughly.

### CODE REVIEW

**Comment by laghee** [comment]
Hmm... OK, running lint locally (which seems weird since I didn't touch any js or css files), I'm not getting these errors. Will investigate further...

**Comment by miketaylr** [comment]
I'm not super familiar with this tools/labels.py script. Is it the right place to make these changes? (I'm not sure what it does, tbqh).

What about https://github.com/webcompat/webcompat.com/blob/master/webcompat/api/endpoints.py#L213-L219, where the JS requests all the labels?

**Comment by laghee** [comment]
@miketaylr You make an interesting point... 🤔 I picked this up mostly done from the end of AllHands, and I can't completely remember how I landed on `labels.py`. I know we had talked about server-side potentially being a better fix, but I'll need to go back and retrace my path to have a smarter answer.

**Comment by laghee** [comment]
> I'm not super familiar with this tools/labels.py script. Is it the right place to make these changes? (I'm not sure what it does, tbqh).

Oh, 💩 . I think this script -- or these label tools, anyway... update the `issues.db`, maybe? I have no idea what I was thinking (other than python , obviously).

Sorry! 🙈  Regroup...

**Comment by laghee** [comment]
OK, so I re-oriented myself, and now I have a question.

Might it be a good idea to cover more than the current labels issue with this fix (part of the problem in issue #2450 also seems to be with pagination -- whenever the total needstriage issues go over 100, an incomplete list is filtered and sent to the dashboard)?

I'm thinking of working the loop into a new helper method that can be called from `api_request`:
https://github.com/webcompat/webcompat.com/blob/4cad018bb0454720765bc4a9520bac5c21de149c/webcompat/helpers.py#L450
if that makes sense. Directly changing `api_request` would blow up the issues endpoint (which already has pagination worked out through the frontend JS), but just fixing the labels seems like it will end up being very non-DRY if other fixes are needed later.

I'm not nearly as familiar with the front end, though, so maybe it's better to fix one thing at a time and worry about scope later? 

@miketaylr @karlcow ?

**Comment by karlcow** [comment]
@laghee @miketaylr (adding @marimeireles as she discussed about labels for performances too, aka requesting labels only when we actually open the menu, like GitHub does.)

ok the current request is

```python
@api.route('/issues/labels')
@mockable_response
def get_repo_labels():
    """XHR endpoint to get all possible labels in a repo."""
    params = request.args.copy()
    path = 'repos/{0}/labels'.format(REPO_PATH)
    return api_request('get', path, params=params)
```

Let's try to run ideas (bad and good).

## walk_pagination
we could imagine to have something like

```python
def api_request(method, path, params=None, data=None, mime_type=JSON_MIME, walk_pagination=False):
```
default is `False`.

when `walk_pagination=True`, we could

1. check if there is actually more data to fetch (link http header)
2. if yes, fetch the next data
3. add it to the previous response
4. send the results back.

Possible issues:
1. we blow everything up if we forget about the way this is working and we enter in a 10 pages data set.
2. the network breaks in between the two or more requests

## parameter

The request is currently `/api/issues/labels?per_page=100`
but let's say we push it to 200. This is a request to **our API**, we could then fetch two pages and re-assemble them into one JSON that we send back.

Possible issue:
1. The network breaks in between the two requests.

## local
We do not request milestones each time we use them because we consider them stable. We could perfectly through a CRON job (for example, once a day or once a hour), have a script creating a local JSON file with the list of all labels. The JSON is then local, cached, with the appropriate ETAGs, and can be requested by the JS to build the menu without having to make any requests to GitHub. Performance++

Possible issue:
Being unsettled because the labels are not sync on webcompat.com with what exist on GitHub. Though currently… we don't have the end of the list at all… so probably an improvement. 😛

**Comment by marimeireles** [comment]
>local
>walk_pagination

Both seems like good ideas.

I couldn't think of anything else... But let me know if I can help with something!

**Comment by karlcow** [comment]
I'm closing the PR here. 
Let's start with a fresh PR.
I documented on the issue what we need to do. 
https://github.com/webcompat/webcompat.com/issues/2726#issuecomment-477005645

**Pull request closed without merging**
