### PR TITLE
Fixes #2465 - Upgrades Flask to 1.0.2

### LINKED ISSUE #2465: Test Flask 1.0 upgrade
This issue has for purpose to just test if upgrading Flask 1.0 only breaks stuff.
And eventually repairs it.

### PR DESCRIPTION
**Pull request by karlcow**
This PR fixes issue #2465

## Proposed PR background

This upgrades to the first stable release of Flask. 
It is a step that will help us improve logging and the switch to python3
Functional tests and unit tests are passing.

r? @miketaylr

### CODE REVIEW

**Comment by karlcow** [comment]
```
→ python run.py -t
Statuses Initialization…
Fetching milestones from Github…
Milestones saved in data/
Milestones in memory
Starting server in ~*TEST MODE*~
 * Serving Flask app "webcompat" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://localhost:5000/ (Press CTRL+C to quit)
 * Restarting with stat
Statuses Initialization…
Fetching milestones from Github…
Milestones saved in data/
Milestones in memory
Starting server in ~*TEST MODE*~
 * Debugger is active!
 * Debugger PIN: 195-432-804
```

Working for me locally.

**Comment by karlcow** [comment]
And this is working too. 

capture d ecran 2018-06-07 a 07 33 12

Let's kick again travis.

**Comment by karlcow** [comment]
That's better. Next will be #2463 once this one is merged.

**Comment by miketaylr** [comment]
> huh travis what did you find? 😄

Yeah, seems like Travis just fails to start tests half the time... annoying. #2375

**Pull request merged**
