### PR TITLE
Fixes #2509: Fixed race condition when image didn't get transferred from report site issue extension

### LINKED ISSUE #2509: Screenshot is not automatically added when using "Report site issue"
URL: http://www.google.com/ redirecting to www.webcompat.com  
Browser / Version: Firefox Nightly 62.0a1 (2018-06-17) 
Operating System: Samsung Galaxy S6 (Android 7.0) - Resolution 1440 x 2560 pixels (~577 ppi pixel density), Google Pixel (Android 8.1.0) - 1080 x 1920 pixels (~441 ppi pixel density)

**Prerequisites:**
    1. “webcompat.com reporter” add-on installed on Firefox.

**Steps to Reproduce:**
    1. Navigate to any site (e.g http://www.google.com/) 
    2. Tap “More” button.
    3. Tap “Report site issue”.
    4. Observe form.
       
**Expected Behavior:**
Screenshot is automatically added to “Screenshot” area.

**Actual Behavior:**
Screenshot is not available in the “Screenshot” area.

**Note**
    1. Not reproducible on Desktop. 
    2. Not reproducible on Firefox Release 60.0.2
    3. Affected area:
```html
<div class="form-upload js-image-upload js-Form-group">
	<input accept=".jpe,.jpg,.jpeg,.gif,.png,.bmp" class="form-input input-upload" id="image" name="image" type="file">
		<div class="label-icon label-upload js-label-upload">
			<svg class="icon icon-big" role="presentation" title="Upload Screenshot">
				<use class="icon-upload" xlink:href="#svg-plus">Upload Screenshot</use>
			</svg>
			<small class="label-icon-message">Upload screenshot</small>
		</div>
		<div class="label-icon label-remove is-hidden js-remove-upload">
			<svg class="icon icon-big" role="presentation" title="Remove Screenshot">
				<use class="icon-remove" xlink:href="#svg-x">Remove Screenshot</use>
			</svg>
			<small class="label-icon-message">Remove screenshot</small>
		</div>
		<div class="label-icon label-error is-hidden js-error-upload">
			<svg class="icon icon-big" role="presentation" title="An error occoured">
				<use class="icon-error" xlink:href="#svg-warning">An error occoured</use>
			</svg>
		</div>
</div>
```

screenshotnotautoadded
        
**Watchers:**
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv;

### PR DESCRIPTION
**Pull request by ksy36**
r? @miketaylr

### CODE REVIEW

**Comment by wisniewskit** [comment]
Mike, could you take a look at this as well? This change looks hefty, but if you look at the individual commits, it's not really that evil. The first commit is just us unindenting functions and putting them on the prototype of Bugform (so that they are created when the page loads, not after jQuery.ready).

The second commit is the actual interesting change, where we just change how the constructor of BugForm works so that it calls jQuery.ready at appropriate times, so the message-listener is added right away, but it only actually handles the message after jQuery.ready.

**Comment by miketaylr** [comment]
Yep, this looks good. Reviewing each commit is less scary. :)

**Comment by karlcow** [comment]
Thanks a lot @ksy36 and @wisniewskit !!!

**Comment by karlcow** [comment]
I'll deploy this next week.

**Pull request merged**
