### PR TITLE
Added link to bug report form in nav bar

### PR DESCRIPTION
**Pull request by tagawa**

### CODE REVIEW

**Comment by tagawa** [comment]
Oh no, don't think I was supposed to do that...

**Comment by karlcow** [comment]
houla. Trying to understand what is happening here. :)

**Comment by tagawa** [comment]
Sorry, I messed up. I wanted to send a PR to staging instead of master but it ended up with all these other commits. I've a feeling I've done this before but I'm not sure what else to do. Maybe I should push directly to upstream staging rather than origin?

**Comment by karlcow** [comment]
* Maybe close this one.
* Then go back to your master

```
git checkout master
git fetch upstream master
git merge upstream/master
git checkout -b  565/1
# (do your edits)
git commit -m "Fix #565 adding link to bug report in navbar"
git push origin 565/1
# (create the pull request against staging branch.)
# Once merged
git branch -d 565/1
git push origin :565/1
```

DONE. ;)

**Comment by tagawa** [comment]
Closing per Karl's advice and hoping @miketaylr will think nothing's happened.

**Comment by miketaylr** [comment]
:)~

Yeah, it's because staging doesn't always stay in sync with master. When we changed up dev processes, we decided to do all PRs against master (see https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#submission-guidelines) 

> In GitHub, send a pull request to webcompat.com:master

Staging in theory exists for us to test risky things in a shared non-production environment. So if you do want to push something there, just ping me and I'll make sure everything is up to date.

There's not a ton of risk of messing up master, since all the "releases" are tagged we can easily revert to a known working state if something breaks.

**Comment by tagawa** [comment]
Thanks for the explanation @miketaylr. Will stick to master in future.

**Pull request closed without merging**
