### PR TITLE
Fixes #1469. Handle x-www-form-urlencoded spaces in details param.

### LINKED ISSUE #1469: Handle decoding + as a space for `details` param values
(https://github.com/webcompat/webcompat.com/issues/1358#issuecomment-290627963)

The value of the `details` param will be constructed using `URLSearchParams` rather than `encodeURIComponent`, and it treats spaces differently (+ vs %20).

Something hacky like `decodeURIComponent(str.replace(/\+/g, '%20'));` would probably do the trick.

### PR DESCRIPTION
**Pull request by miketaylr**
Not ready for review, need to add a test.

### CODE REVIEW

**Comment by miketaylr** [comment]
> As said in the previous comment. This is not valid :clown_face:

Sorry, I didn't understand that's what you meant by:

> and just for the record on your proposal above mixing inadequately two things 👹

**Comment by miketaylr** [comment]
(odd error on travis:

```
127.0.0.1 - - [06/Apr/2017 18:22:32] "GET /login HTTP/1.1" 302 -

SUITE ERROR

InvalidElementState: [POST http://localhost:4444/wd/hub/session/8d0ffa25-b251-4012-827d-14b7380b7723/element/59/click / {}] Element is not enabled

Build info: version: '3.0.1', revision: '1969d75', time: '2016-10-18 09:48:19 -0700'

System info: host: 'testing-gce-900b0a4a-c246-4383-9a85-01adc4d88626', ip: '127.0.1.1', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-51-generic', java.version: '1.8.0_111'

Driver info: org.openqa.selenium.firefox.FirefoxDriver

Capabilities [{rotatable=false, raisesAccessibilityExceptions=false, marionette=true, firefoxOptions={args=[], profile=UEsDBBQACAgIAMKShkoAAAAAAAAAAAAAAAAHAAAAdXNlci5qc51WTW/bMAy971cMOW3AKqTretlOXdcBA4Z1aFDsKMgSbauRJU0fcfPvR/mjSRNHbndKbJMS+fj4yOjBUeugfLconGnxiXhWQvdf6oo0TLXMAQHNCgVi8eFtyZSH91/exJ2nYAFtrHEhudTAVKj7Z4JGG8ln/DWE1rg1qUOwxNbS19uz9Nky788U6CrU6Pjx8vK52xiwAybwR0AAHkB8l86HK4yFK0C34OJhuKbBvB4pr51pgHrupA3URU2DbJLLxXL6osAKTxAOfauvlfEwnc1oLUyrlWEC79KsSsDWpv1Tg14hWgmpaXeLQdng02W0MYKpGexhE4xRnoBzxnGjvVH7cB+n72WljUbUGmgKcKvu0edz8eC9RKtgkAsOfETcSgyUcsd8nfdVUq+JsaApPAZwmqlUzFczqExlvYt6+rIWCuHkBp8Z54DljBoz90gHysEFP4nEU6Wkt4ptQdycL1e/DDInlfbTtDG+Erf6j9RYX3++JBIvMvd3P9FjwQoTw+dCMb1eHHOuT4gypeiDRzBSnLKH/ji2RysRbrQlbS0DKOkDHvA3SneKCYkGaxnI0E0j6zC5xIUsAIphYbAB8lTzibfRkhq7xuLZtAXFUwdFl0q6OEg5VVt3rCHRYoGBaIS23N6jyat1JNrUSjfZ8IBHJ8MWmaIA/xEfnOSBGicrqak1SvJtnqoaWmw7MuSTqeazQPuTSXq5ikUju1b53b286sj4Mt2cPCab8VN3DoVJRUHLE+q160NMs+34e9yIpizRDs6YtZ4g+0xLiy0VULKowrScjLBzbwf+TEd7zIcs20Y6I/dRqYLbkl4ZO/uPc7bZo0dEbu5/XpELwnZFOk7vgW1YPyGyonpYirFH8jw6jtvBQzfEspf0NE3H5/PcQ5zFYL71SrDiSIIkOufLUxran0o1C/hIYQM6zAyIvdF4ixSbjadQhq87UXtRpTwwx+uBN3NjtyE9u4mIjc1WDVn+Ii4+I4xBhJwU04p6JEKH6nMxvfr0an02th/SKMQZyAfbE9Iy7Djzy83e5PTdXN9NTpSg2Gl1FrlErekg9nrH9KOu24F+6Ot+TTm5nQ0zi3ZqJRBGXdGk/zMkqQHHJa+Br7/1gvW1//L6cUaYEDJFzGYmweTS/L/LsjJVlV4OW1xW+/d6qcv4GrUR27WQKrFPy6oO6sS023Mdb/wfaaNjI5AG98KOiIu0Szo4wGi3yqTVE4mNC+TMLrPre1X6aPsVYLdl/ANQSwcIy87bUaYDAAC2DAAAUEsBAhQAFAAICAgAwpKGSsvO21GmAwAAtgwAAAcAAAAAAAAAAAAAAAAAAAAAAHVzZXIuanNQSwUGAAAAAAEAAQA1AAAA2wMAAAAA}, appBuildId=20161208153507, version=50.1.0, platform=LINUX, proxy={}, command_id=1, specificationLevel=0, acceptSslCerts=false, build=6efec5e1ebdd76d8a69fbbf47d817cc788aab4d2, processId=5784, browserVersion=50.1.0, platformVersion=4.4.0-51-generic, name=tests/intern, XULappId={ec8030f7-c20a-464f-9b0e-13a3a9e97384}, browserName=firefox, takesScreenshot=true, idle-timeout=60, takesElementScreenshot=true, platformName=linux}]

Session ID: c3186c73-1d78-4395-9f39-aff1fb05729a

  at Command.<anonymous>  <tests/functional/lib/helpers.js:96:24>

  at nextTickCallbackWith0Args  <node.js:489:9>

  at process._tickCallback  <node.js:418:13>

  at Command.<anonymous>  <tests/functional/lib/helpers.js:89:18>

  at nextTickCallbackWith0Args  <node.js:489:9>

  at process._tickCallback  <node.js:418:13>

  at Object.login  <tests/functional/lib/helpers.js:69:10>

  at Suite.registerSuite.setup  <tests/functional/comments-auth.js:23:34>
```

**Comment by miketaylr** [comment]
https://github.com/webcompat/webcompat.com/blob/master/tests/functional/lib/helpers.js#L96 is where the error is happening, which is how we handle with the case where GitHub thinks we're a bot. Maybe something changed on their end...

**Comment by miketaylr** [comment]
just repro'd that extra prompt locally and here is what the button looks like -- selector looks good. 😕 

```
<button data-ga-click="Oauth, oauth application authorized, oauth_application_id:89385; listing_id:; came_from_integrations_directory:false;" 
               type="submit" 
               name="authorize" 
               value="1" 
               tabindex="1" 
               id="js-oauth-authorize-btn" 
               class="btn btn-primary">Authorize application</button>
```

And it worked for me locally...

**Comment by karlcow** [comment]
I see that travis is testing with `appBuildId=20161208153507, version=50.1.0, platform=LINUX,` maybe something to watch out too. 

> how we handle with the case where GitHub thinks we're a bot. Maybe something changed on their end...

I wonder if there is a bug/feature request to open with GitHub on testing with things like travis.

**Comment by miketaylr** [comment]
I actually got the test to pass by re-triggering today (look at the green push). Which makes me think it was some kind of network (or other) issue between GitHub/Travis. 

Probably safe to review now @zoepage -- thanks!

**Comment by zoepage** [comment]
@miketaylr r+ 
Thanks!

**Pull request merged**
