### PR TITLE
Fixes: #1547; bug report form content refactor (not ready to merge)

### PR DESCRIPTION
**Pull request by cch5ng**
@zoepage R? (I will stop working on this for a while)

### CODE REVIEW

**Comment by zoepage** [comment]
That's a great start! Thanks @cch5ng :)

I'm getting errors when submitting the form. The response on the issue number is empty, so there is also no redirect. Could you push that branch to this organization as those issues are most likely caused by permission issues?

Thank you!

**Comment by cch5ng** [comment]
@zoepage thanks. I think I need to make changes to a JS file and will look into the issues you mentioned.

by pushing to this organization (webcompat) do you mean I should push the branch with something like:
`git push upstream branch_name`
where my upstream is the original repo (webcompat/webcompat.com)?

**Comment by zoepage** [comment]
@cch5ng yes.

you can also set the upstream as your origin, if this makes it easier for you by
```
git remote remove origin
git remote remove upstream
git remote add origin https://github.com/webcompat/webcompat.com.git
git remote -v
```

**Comment by cch5ng** [comment]
closing as moved pr to main repo

**Pull request closed without merging**
