### PR TITLE
Comment element

### PR DESCRIPTION
**Pull request by magsout**
- list style
- h* style
- pre / code style

r? @karlcow

### CODE REVIEW

**Comment by karlcow** [comment]
like a breeze :wind_chime: 
Thanks!

**Comment by karlcow** [comment]
There's an issue with #620

**Comment by miketaylr** [comment]
@karlcow should I hold off deploying this fix? We can wait on #620 if you want.

**Comment by karlcow** [comment]
Yes @magsout needs to add a new PR.

**Comment by karlcow** [comment]
@miketaylr everything is fine now. @magsout did an awesome job.

**Comment by miketaylr** [comment]
:sunglasses: 

Awesome, I'll tag a release and deploy at some point today.

**Pull request merged**
