### PR TITLE
#436 436/1 Preliminary pull request for reorganizing the labels

### PR DESCRIPTION
**Pull request by karlcow**
This pull request touches only the python part of the code. It requires also to modify the label in the repo to get a "status-*". see my own [labels in the test repo](https://github.com/karlcow/webcompat-test/labels) for a possible organization

### CODE REVIEW

**Comment by miketaylr** [comment]
Do we want to pull this into master? Or would it be better to put in a branch while it's not 100% working?

**Comment by karlcow** [comment]
I would be in favor of putting it in a branch. And we can explain here on how to merge that branch for testing on one's own repo. I guess something along (if the branch is `webcompat.com:436/1`) and you have setup upstream in your repo:
```
[remote "upstream"]
        url = https://github.com/webcompat/webcompat.com.git
        fetch = +refs/heads/*:refs/remotes/upstream/*
```

So that would be something like? (@miketaylr I'm happy to be slapped with a big GITrout)

``` git
git checkout -b 436/1                 # create a local new branch with name: 436/1
git reset --hard upstream/436/1 # make your local new branch the same than the upstream one.
```
Or maybe something which makes more sense? :)

**Comment by karlcow** [comment]
I'm wondering if I should have done the docs thing in a separate branch I can still do that. :)

**Comment by miketaylr** [comment]
@karlcow I made a issues/436/1 branch based off of master just now. Can you change this PR to be against webcompat:issues/436/1 instead of webcompat:master? Hopefully you can just edit that in the UI, otherwise just close this and open a new PR.

**Comment by miketaylr** [comment]
To check out a remote branch, `git fetch && git checkout -b issues/436/1 origin/issues/436/1` if you have a clone, or `git fetch && git checkout -b issues/436/1 upstream/issues/436/1` if you have a fork with an upstream pointing here.

**Comment by karlcow** [comment]
Closing without merging after opening #558 which is against branch 436/1

**Pull request closed without merging**
