### PR TITLE
Fixes #1620 - Gets all functional tests to work offline.

### LINKED ISSUE #1620: Get all functional tests to work offline
These are the tests that still need internet access:

- [x] - Issues (auth) - Closing and reopening an issue
- [x] - Search (non-auth) - Search input is loaded from q param (with dashes)
- [x] - Search (non-auth) - Search with a dash works
- [x] - Search (non-auth) - Results are loaded from the query params
- [x] - Issues (non-auth) - Pressing g goes to the github issues
- [x] - Issue List (non-auth) - Pressing g goes to the github issue page

Not a test, but related:

- [x] - Logout functional helper

### PR DESCRIPTION
**Pull request by brizental**
r? @miketaylr

### CODE REVIEW

**Comment by miketaylr** [comment]
I get some test failures: https://gist.github.com/miketaylr/4becab632120c9bf83463f2eabf1272d

Do they all pass on your machine?

**Comment by miketaylr** [comment]
> yes

**Comment by miketaylr** [comment]
oops, forgot to run in test mode. >_<

**Comment by miketaylr** [comment]
@brizental can you check out these failures, por favor?

```
FAIL: firefox on any platform - Issue-list - Pressing g goes to github issues (1ms)
TypeError: (intermediate value).end is not a function
  at Test.Pressing g goes to github issues [as test]  <tests/functional/issue-list-non-auth.js:207:15>
```

```
FAIL: firefox on any platform - Search (auth) - Search works by Return key (10289ms)
NoSuchElement: An element could not be located on the page using the given search parameters.
  at Test.Search works by Return key [as test]  <tests/functional/search-auth.js:135:12>
```

**Comment by brizental** [comment]
The first test was actually a typo, I fixed it. The second test is really failing but it's not related to this issue, probably something like #1470 I'll look into it at some point.

**Comment by miketaylr** [comment]
👍

**Pull request merged**
