### PR TITLE
Fixes #1420 - Flask-Limiter deprecated usage

### LINKED ISSUE #1420: Flask-Limiter deprecated usage
Everytime I run `python run.py` or `python run.py -t` I get this warning:

>UserWarning: Use of the default `get_ipaddr` function is discouraged. Please refer to https://flask-limiter.readthedocs.org/#rate-limit-domain for the recommended configuration

This is simple enough, just some changes to the `__init__.py` file and it's good to go. Just want to know if there is some reason this hasn't been done yet or if I can just go for it.

### PR DESCRIPTION
**Pull request by brizental**
r? @karlcow

### CODE REVIEW

**Comment by brizental** [comment]
I'm sorry for so many commits, I'm still not entirely confident in the git workflow, but I'm working on it, haha.

**Comment by karlcow** [comment]
@brizental yes this branch is including unrelated commits. 

I suggest to restart on a fresh branch. That's the cool thing with git. Sometimes a bit confusing, but it's easy to restart things properly without destroying everything.

When working on a branch like this it's always good to start from a fresh master. In the project, things you can do.

```bash
# will display which branch you are on and if there are things left to do.
git status
# Go back to master
git checkout master
# Update to the latest version of master from webcompat
git fetch upstream ; git merge upstream/master
# Create a new branch. For you, here the 2nd attempt so `1420/2`
git checkout -b 1420/2
# Do your edits and commits. Always think about your sentence like 
" if your were saying "This commit… blah". 
# For example: "This commit updates the Flask-Limiter import"
git commit -m 'Issue #1420 - updates the Flask-Limiter import'
# Then create  a pull request with the title "Fixes #1420 - explanation"
```

This is my own github workflow.
http://www.otsukare.info/2016/04/14/git-workflow

**Comment by karlcow** [comment]
@brizental Just to be clearer you are fixing two separate issues into one pull request which are not related.
#1420 and #1047. These two should be two separate pull requests.

**Comment by brizental** [comment]
Great! Thanks for giving such detailed feedback. I understand now. I have been working with git for a while, but never with forks, so that was a bit confusing. I'll try and make things the right way now.

**Pull request closed without merging**
