### PR TITLE
Fixes #2267. Document how to get the server working on Windows 10

### LINKED ISSUE #2267: Unable to start the Local Server on Windows 10
**Environment:**
Operating System: Windows 10 Pro

**Steps to Reproduce**
    1. Followed the information from [Development Environment setup](https://github.com/webcompat/webcompat.com/blob/master/docs/dev-env-setup.md#installing-virtualenv) guide.
    2. Tried to start local server http://localhost:5000/, using `npm run start` or `python run.py`.

**Expected Behavior:**
Local sever is started and Webcompat.com page is displayed.

**Actual Behavior:**
Local sever is not started and errors are revived in the console.

**Note:**
1. Not reproducible on Linux Ubuntu 16.04.
2. Attached screenshot with installed versions of programs (python, node, npm, virtualenv).
screenshot_1
3. `secrets.py` file contains the correct information:
```py
# Staging and Local instances use the same test repo
else:
    ISSUES_REPO_URI = os.environ.get('ISSUES_REPO_URI') or 'webcompat/webcompat-tests/issues'
```
Added the correct Cliend ID and Client Secret [(instructions here)](https://github.com/settings/applications/new) to:
```py
else:
    # We're running on localhost, use the test application
    GITHUB_CLIENT_ID = os.environ.get('FAKE_ID') or '  '
    GITHUB_CLIENT_SECRET = os.environ.get('FAKE_SECRET') or '  '
    GITHUB_CALLBACK_URL = 'http://localhost:5000/callback'
```
Added the correct OAUTH_TOKEN [(instructions here)](https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/) to:
```py
OAUTH_TOKEN = os.environ.get('OAUTH_TOKEN') or '  '  # nopep8
```

4. 
# Start local server using `npm run start`
Error:
```js
> webcompat@ start D:\Arbuzov Oana My Docs\Mozilla\WebcompatRepository\webcompat.com
> source env/bin/activate || . env/bin/activate && python run.py

'source' is not recognized as an internal or external command,
operable program or batch file.
'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! webcompat@ start: `source env/bin/activate || . env/bin/activate && python run.py`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the webcompat@ start script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\oana.arbuzov\AppData\Roaming\npm-cache\_logs\2018-03-20T13_43_56_404Z-debug.log
```
Attached error log.

# Start local server using `python run.py`
Error:
```js
Statuses Initialization…
Fetching milestones from Github…
It failed with 404 Client Error: Not Found for url: https://api.github.com/repos%5Cwebcompat/webcompat-tests%5Cmilestones!
We will read from data/milestones.json.

Oooops.
We can't find D:\Arbuzov Oana My Docs\Mozilla\WebcompatRepository\webcompat.com\data\milestones.json
Double check that everything is configured properly
in config/secrets.py and try again. Good luck!

Milestones are not initialized.
```
[2018-03-20T13_43_56_404Z-debug.log](https://github.com/webcompat/webcompat.com/files/1829553/2018-03-20T13_43_56_404Z-debug.log)

Watchers:
@softvision-sergiulogigan
@softvision-oana-arbuzov

### PR DESCRIPTION
**Pull request by miketaylr**
<s>Note: This contains commits from #2501. Once that lands, I'll rebase and make those commits disappear (this should come *after*).</s>
edit: done

@softvision-oana-arbuzov @softvision-sergiulogigan could one of you run through the instructions to verify they work?

I've got the local server running on my windows 10 machine after following these instructions, but it's possible I didn't document everything.

### CODE REVIEW

**Comment by miketaylr** [comment]
@softvision-oana-arbuzov https://github.com/webcompat/webcompat.com/issues/2497#issuecomment-398430939 sounds like you ran through these instructions successfully. 

Is that correct?

**Comment by softvision-oana-arbuzov** [comment]
@miketaylr , yes I did, after running again the entire guidelines on the Ubuntu terminal.

The only error I received was due to having node already installed.
Note: 
> You can install node and npm with your Windows powershell as well, so if you've done that it won't work properly for your Subsystem. That means you have to install it twice (Powershell and Subsystem) or you decide for one thing. Check more at: https://stackoverflow.com/questions/45853530/npm-install-error-not-foundram-files-nodejs-npm-3-mnt-c-program-files-nodejs 

This was fixed by uninstalling and re-installing it.
How to solve the Problem: 
Remove your current installations
```
sudo apt-get --purge remove node
("sudo apt autoremove node" if console is asking for)
sudo apt-get --purge remove nodejs
```
Install note the right way
```
curl -sL https://deb.nodesource.com/setup_6.x | sudo -E bash -
sudo apt-get install -y nodejs
sudo apt install note
```
Then install build tools so you can install addons for npm later
`sudo apt-get install -y build-essential`

**Comment by miketaylr** [comment]
Ah, thanks @softvision-oana-arbuzov -- I'll add that note to the docs, and then I think we're good to merge here.

**Comment by miketaylr** [comment]
Thanks for review @softvision-oana-arbuzov, let's go ahead and merge.

**Pull request merged**
