### PR TITLE
Fixes #1969 - Removes dead code from rate_limit

### LINKED ISSUE #1969: [Dead code] Rate limit dust to remove.
In #1437 we change the route for `/rate_limit` to send a `410`
https://github.com/webcompat/webcompat.com/blob/a9f5b7bda2ad556b2185a424f94ed37110237427/webcompat/views.py#L278-L292

Some code and modules were left around.

* [x] Remove Babel==2.3.4 from `config/requirements.txt`
* [x] remove babel import from https://github.com/webcompat/webcompat.com/blob/a9f5b7bda2ad556b2185a424f94ed37110237427/webcompat/helpers.py#L22
* [x] Remove `from datetime import datetime`
* [x] Remove `import math` 
* [x] Remove `format_delta_filter` in https://github.com/webcompat/webcompat.com/blob/a9f5b7bda2ad556b2185a424f94ed37110237427/webcompat/helpers.py#L47-L51
* [x] Remove `format_delta_seconds` in https://github.com/webcompat/webcompat.com/blob/a9f5b7bda2ad556b2185a424f94ed37110237427/webcompat/helpers.py#L86-L94
* [x] git rm https://github.com/webcompat/webcompat.com/commit/f32c53c5822f646fc7fa0c4d77383d37eaaa337e

### PR DESCRIPTION
**Pull request by karlcow**
r? @zoepage 
r? @miketaylr (as a backup)  
See issue #1969 for the details.

### CODE REVIEW

**Comment by miketaylr** [comment]
@zoepage can review this one. :)

**Comment by zoepage** [comment]
@miketaylr did you already? Otherwise can do later today :)

**Comment by zoepage** [comment]
K, LGTM. @miketaylr feel free to double check. Thanks!

**Comment by miketaylr** [comment]
> @miketaylr did you already? Otherwise can do later today :)

Nope! LGTM as well. Thanks.

**Pull request merged**
