### PR TITLE
Fixes #2526 - fixed filteringSort function

### LINKED ISSUE #2526: The sort function seems reversed -- like oldest and newest are doing the opposite of the expected:
Open issue for this comment by @laghee https://github.com/webcompat/webcompat.com/issues/2450#issuecomment-400588542

### PR DESCRIPTION
**Pull request by magsout**
This PR fixes issue #2526

## Proposed PR background

fixed `filteringSort` function. The order of issue was not stable. Every time we click on `filtered` button the order of issue changed. I created a global object to save the order and the previous select.

---

- [x] I have read the [Pull Request + Code Style Guidelines](https://github.com/webcompat/webcompat.com/blob/master/docs/pr-coding-guidelines.md) thoroughly.

### CODE REVIEW

**Comment by laghee** [comment]
**Disclaimer:** I'm not super familiar with all the code yet, and I haven't got tests back up locally yet to double-check the Travis issue (not sure if those errors are about the new milestone fetching order?), so I'm tagging in a backup reviewer ;p ... r? @miketaylr 

So [from this it seems like the milestone list of issues (`issuesNumber`) come through in order of oldest-first, ascending](https://github.com/webcompat/webcompat.com/blob/a0dde5e397290e20e9cccf81533e64c25c0ed81c/webcompat/views.py#L437). And since we're initializing on `newest`, we need to reverse that order, so that seems sensible 👍.

Saving the sort order between filters seems reasonable, too.

I'm curious about the `sort` option in the dropdown. It doesn't seem to have utility beyond explaining the function, but the user doesn't see it unless they click (which won't have any effect on filtering). Would it make sense, or make any logic simpler/easier if we were to load that as the default option?

**Comment by miketaylr** [comment]
> It failed with 403 Client Error: Forbidden for url: https://api.github.com/repos/webcompat/webcompat-tests/milestones!

Hmm... @karlcow I guess a Travis IP will hit the rate limit. I wonder if we need to hard-code milestones.json for tests?

**Comment by karlcow** [comment]
@miketaylr this is #2518

**Comment by miketaylr** [comment]
> @miketaylr this is #2518

thanks, it felt familiar.

**Comment by miketaylr** [comment]
> I'm curious about the sort option in the dropdown. It doesn't seem to have utility beyond explaining the function, but the user doesn't see it unless they click (which won't have any effect on filtering). Would it make sense, or make any logic simpler/easier if we were to load that as the default option?

@magsout ?

**Comment by magsout** [comment]
@laghee 
>I'm curious about the sort option in the dropdown. It doesn't seem to have utility beyond explaining the function, but the user doesn't see it unless they click (which won't have any effect on filtering). Would it make sense, or make any logic simpler/easier if we were to load that as the default option?

I'm not sure to understand.

What do you mean by `which won't have any effect on filtering` and `if we were to load that as the default option`?

**Comment by laghee** [comment]
Sorry, @magsout, my parentheses sometimes get the better of me!

> What do you mean by `which won't have any effect on filtering` 

Selecting `sort` in the drop down and clicking on `filter` doesn't change the order of the cards.

> and `if we were to load that as the default option`?

If we loaded the page with `Sort` selected rather than `Newest`.
(We could also consider eliminating the `sort` option altogether and have just `Oldest` and `Newest`?)

**Comment by magsout** [comment]
@laghee thanks for the explanations.

> (We could also consider eliminating the sort option altogether and have just Oldest and Newest?)

Good idea 👍

**Comment by magsout** [comment]
@laghee @karlcow https://github.com/webcompat/webcompat.com/blob/a0dde5e397290e20e9cccf81533e64c25c0ed81c/webcompat/views.py#L437 changes the Maybe, changing filter `direction` by `desc` would a good idea?

**Comment by karlcow** [comment]
I'm trying to understand. Right now we get a list where the sort is 

1. by creation date
2. from oldest to newest

The logic at the time it was designed is that the oldest ones are the more urgent.

It's how it is displayed right now.

The way the UI is working right now is that you select the parameters and you have to click "filtered" (which maybe should be "submit") which reorder the full list. 

What could be done probably is that maybe it's not necessary to have the "filtered" button and that the reordering is done with `onchange`

**Comment by magsout** [comment]
@karlcow 
>The logic at the time it was designed is that the oldest ones are the more urgent.

At the moment, the UI not reflect that.

capture d ecran 2018-06-29 a 08 57 55

I need to fix that too. It's a mistake, in this way I make logic simpler in the code.

>What could be done probably is that maybe it's not necessary to have the "filtered" button and that the reordering is done with

Yes, we could do that.

**Comment by magsout** [comment]
What I propose

- Remove default empty option `Sort`
- made by default `oldest` in the select (reflect the design)

little bonus? ;)
- removed button filter
- added an onChange event on every form element.

@karlcow @laghee @softvision-oana-arbuzov @softvision-sergiulogigan , what do you think?

**Comment by softvision-sergiulogigan** [comment]
As far as I can see, the `Sort` and the `Newest` are pretty much the same thing (at least in today's list).
Maybe we should default to `Oldest`

And as for

> added an onChange event on every form element.

I's second this.

**Comment by magsout** [comment]
@miketaylr @laghee 
updated my commits

**Comment by magsout** [comment]
@laghee 
>Looks good and works for me locally -- except the filtered button is still there (and throws a type error onClick). Maybe you forgot to remove it?

oops, too much cmd+z ;)

fixed ;)

**Comment by laghee** [comment]
🎉

**Pull request merged**
