### PR TITLE
FIXES #1881 - refactor navigation and shared links to use the new styleguide

### LINKED ISSUE #1881: refactor template: nav.html
Refactor following:
https://github.com/webcompat/webcompat.com/blob/master/webcompat/templates/shared/nav.html
https://github.com/webcompat/webcompat.com/blob/master/webcompat/templates/shared/shared-nav-links.html

with:
https://github.com/webcompat/design/blob/master/docs/index.html#L192
(if line changed, search for id="Nav")

- [x] refactor template for nav.html
- [ ] refactor template for nav-links.html

Please be aware to add the placeholders for links as they are in the old templates.

### PR DESCRIPTION
**Pull request by chaosmonster**
* add HTML markup to work with the new css
* merged issues/1902 into this branch though it is not finished, because it shares code with 1881

### CODE REVIEW

**Comment by chaosmonster** [comment]
?r @denschub

**Comment by denschub** [comment]
Aaaaaaactually, `issues/1902` needs a rebase before merging into the other branch, so we don't end up with the same commits twice!

**Comment by zoepage** [comment]
@chaosmonster would you be able to rebase? Otherwise happy to help, if you don't have time this week :)

**Comment by chaosmonster** [comment]
I can do it tomorrow evening, in fact I would love to learn it,  because I would need help. I am a noob when it comes to rebasing.

**Comment by zoepage** [comment]
@chaosmonster i probably be around, so ping me if you need help! :)

**Comment by zoepage** [comment]
@chaosmonster just a friendly ping? We'd love to merge the branch soon. :)

**Pull request merged**
