### PR TITLE
New color palette

### PR DESCRIPTION
**Pull request by magsout**
r? @andrewmcgivery  
r? @calexity

### CODE REVIEW

**Comment by andrewmcgivery** [comment]
I think it would be valuable to see this in staging so we can do a few review with the appropriate tools. :)

**Comment by magsout** [comment]
okay ;) cc @miketaylr

**Comment by calexity** [comment]
:lollipop: looks good @magsout !  You may want to add the colors in the comments like you did before like...

/* Light green */

**Comment by magsout** [comment]
dine @calexity

**Comment by miketaylr** [comment]
Deployed to staging. Note that "needs contact" doesn't really exist yet, so you won't see any light green.

**Comment by andrewmcgivery** [comment]
Sorry, to clarify, is this pull request just the about page?

If yes, looks all good. 0 color contrast errors on http://staging.webcompat.com/about :)

**Comment by miketaylr** [comment]
@andrewmcgivery  yeah it will affect the about page, as well as staging.webcompat.com/issues

**Comment by miketaylr** [comment]
Looks like everyone is on board. Will merge.

**Pull request merged**
