### PR TITLE
Fixes #1359. Add support for a problem_type param to preselect type in form.

### LINKED ISSUE #1359: Add a GET param to pre-select issue problem type
(See #1356 for discussion of Media team's needs.)

### PR DESCRIPTION
**Pull request by miketaylr**
<s>r? @karlcow </s>

### CODE REVIEW

**Comment by miketaylr** [comment]
> r? @karlcow

Hang on, I realize I didn't finish my test. 😨

**Comment by miketaylr** [comment]
OK! Test pushed, ready for review.

r? @karlcow

**Comment by karlcow** [comment]
This looks good so far.
Trying to run the tests.

```
IntegrityError: (IntegrityError) datatype mismatch u'INSERT INTO users (user_id, access_token) VALUES (?, ?)' 
```
capture d ecran 2017-02-28 a 10 42 05

**Comment by karlcow** [comment]
Let's try with

```
→ node_modules/.bin/intern-runner config=tests/intern functionalSuites=tests/functional/reporting-non-auth.js 
```

so we only test what you modified. It seems to consistently fail on the 4th test. then it gets stucked and all the other tests fail.

capture d ecran 2017-02-28 a 10 50 35

```js
"URL validation": function() {
      return FunctionalHelpers.openPage(this, url("/issues/new"), ".wc-ReportForm-actions-button")
        .findByCssSelector("#url").click()
        .end()
        .execute(function() {
          var elm = document.querySelector("#url");
          WindowHelpers.sendEvent(elm, "input");
        })
        .sleep(500)
        .findByCssSelector(".wc-Form-helpMessage").getVisibleText()
        .then(function(text) {
          assert.include(text, "A valid URL is required", "URL validation message is shown");
        })
        .end()
        .findByCssSelector("#url").type("sup")
        .end()
        .waitForDeletedByCssSelector(".wc-Form-helpMessage")
        .end();
    },
```

So I see in the window the "sup" in the URL field. but then nothing else is happening.
I guess this is not being executed.

```js
        .waitForDeletedByCssSelector(".wc-Form-helpMessage")
```

Oh and indeed it doesn't work. I will open a bug and explain.

**Comment by karlcow** [comment]
Let's move it. r+ @miketaylr

**Comment by miketaylr** [comment]
Thanks @karlcow -- and thanks for opening a bug on the bad test.

**Pull request merged**
