### PR TITLE
Fixes #1226. Un-break BugForm.copyURL

### LINKED ISSUE #1226: URL in description not updating
Regression caused by https://github.com/webcompat/webcompat.com/pull/1213. I should have caught that in review.

### PR DESCRIPTION
**Pull request by miketaylr**
And add a test.

r? @adamopenweb

### CODE REVIEW

**Comment by miketaylr** [comment]
(let's make sure the tests are green before merging, i didn't try my test locally)

**Comment by miketaylr** [comment]
TIL that `getVisibleText` apparently doesn't work for `textarea` elements, but if you get the `value` property it all works out. ☘

**Comment by miketaylr** [comment]
aight @adamopenweb, fixed the dumb test r?

**Comment by adamopenweb** [comment]
Thanks @miketaylr, looks good. r+

**Comment by miketaylr** [comment]
thx!

**Pull request merged**
