### PR TITLE
Fixes #1192 -- Fix CONTRIBUTING.md TOC links

### LINKED ISSUE #1192: Fix CONTRIBUTING.md TOC links
Not all of the TOC links are working, which means we changed headings and forgot to update the TOC links.

"Simple Setup" is an example: https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#simple-setup 

To fix this bug, please audit all the links in the TOC and make corrections where needed!

### PR DESCRIPTION
**Pull request by dacharya64**
r? @miketaylr

### CODE REVIEW

**Comment by miketaylr** [comment]
Looks good! Will hold off to merge if you want to include the fix from https://github.com/webcompat/webcompat.com/issues/1192#issuecomment-255322024.

**Comment by dacharya64** [comment]
Fix is now included.

**Comment by miketaylr** [comment]
Cool, thanks. Just FYI, when you're create a pull request to this repo, you don't need to to also send a pull request to your own, e.g., https://github.com/dacharya64/webcompat.com/pull/1 and https://github.com/dacharya64/webcompat.com/pull/2. You can just push the branch and send a PR directly to this one.

(I'll clean up the commits, nothing to worry about!)

**Comment by dacharya64** [comment]
Good to know, thanks!

**Comment by miketaylr** [comment]
OK, so since you didn't create this PR from a branch and on your master, I had to rewrite your history with `git push master -f`. That's kind of scary and will possibly create some headaches for you. In the future, be sure to submit PRs from branches, that way your master is always "safe" -- branches are super cheap, you can make as many as you want and experiment, get rid of them, etc. 

So, let's merge this one and see how I just messed up your other PRs. :)~

**Comment by miketaylr** [comment]
(Also, it's nice to include "Issue #NNN. Do this thing" style commit messages -- not the end of the world, but it creates a nice link to the original GitHub issue).

**Comment by miketaylr** [comment]
Thanks for the contribution!

**Pull request merged**
