### PR TITLE
Fixes #2031 - Updated stylelint to v8.4.0

### LINKED ISSUE #2031: Update stylelint to v8
The --fix option for the CSS linter is broken in v7, so we'd like to update to v8.
http://npmjs.com/stylelint

Please note, there were changes to the config https://github.com/stylelint/stylelint/releases/tag/8.0.0 we need to take care of too.

Updating stylelint-config-standard from v16 to v18 probably wouldn't also hurt.

### PR DESCRIPTION
**Pull request by magsout**
r @zoepage  ?

### CODE REVIEW

**Comment by zoepage** [comment]
@magsout 
I get `Exit status 2`. Which npm and node version are you running on?

(In addition: did you check, if the `--fix` option is working now?)

**Comment by magsout** [comment]
@zoepage oh weird

```
MacBook-Air:~ GuillaumeDEMESY$ node -v
v6.9.5
MacBook-Air:~ GuillaumeDEMESY$ npm -v
3.10.10
MacBook-Air:~ GuillaumeDEMESY$ 
```

>(In addition: did you check, if the --fix option is working now?)

YES ;) 
after: `npm run lint:CSS -- --fix`

capture d ecran 2018-02-05 a 11 33 01

**Comment by zoepage** [comment]
Let me update my system and see if I still get the issue. Thanks! :)

**Comment by zoepage** [comment]
Okay, after looking into it further, this looks like a feature. The exit happens as there are errors that can not be fixed automatically. But files get linted as they supposed to.

@magsout Could you please add / fix 2 last things? Then we can definitely merge.
1. Could you add the fix option for CSS and add that to the fix:lint script?

2. Could you please change the path to we basically just lint the /src folder and the webcompat.dev.css ? That would be great!

**Comment by magsout** [comment]
@zoepage done ;)

**Comment by zoepage** [comment]
Sweet! One last tiny bit. Could you also add `webcompat.dev.css` to the linter? 
Also happy to add this in a follow up issue :)

**Comment by zoepage** [comment]
Lets merge this. I have to lint the files anyway ;)

**Comment by magsout** [comment]
@zoepage why do you want to lint webcompat.dev.css ? If alla files are lint the final file will be also lint? nah ?

**Comment by zoepage** [comment]
The dev file is not the min, which is gets compiled. The dev one contains the imports and helper classes. So, it might be good to also lint this one. But I already added that to the bug (referenced in #2031)

**Pull request merged**
