### PR TITLE
Fixes #2280 - Add default value 'None' to access_token argument

### LINKED ISSUE #2280: Add None default argument value for authorized method in views.py
To fix this bug, we should add a default value of `None` to the `access_token` argument:

`def authorized(access_token=None)`

https://github.com/webcompat/webcompat.com/blob/7cc40a31b33b6ca565e6872dc9f57dd2e4a2e4e1/webcompat/views.py#L108

### PR DESCRIPTION
**Pull request by aryanshar**

### CODE REVIEW

**Comment by aryanshar** [comment]
@miketaylr How do I check where did my build failed ?

**Comment by miketaylr** [comment]
> @miketaylr How do I check where did my build failed ?

@aryanshar if you right-click on "Details" it will take you to https://travis-ci.org/webcompat/webcompat.com/builds/356900512?utm_source=github_status&utm_medium=notification.

But the failure there is totally unrelated to your change, I think it's a chromedriver/coverage bug. Probably something we'll fix in #1714 or related bug.

**Comment by aryanshar** [comment]
@miketaylr I want to contribute more to this repository but the problem I'm facing is understanding this large codebase. Can you reference me some links as to where I can read stuffs from and get working and get things done !

**Comment by miketaylr** [comment]
@aryanshar cool!

I would recommend looking at https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md first, then looking at some of the other "good first bugs" or "good next bugs":

https://github.com/webcompat/webcompat.com/labels/prio%3A%20good%20next%20bug
https://github.com/webcompat/webcompat.com/labels/good%20first%20bug

**Comment by karlcow** [comment]
@aryanshar This might help a bit too. 
https://github.com/webcompat/webcompat.com/wiki

And if you think a part of the code is obscure it's a good opportunity for us to document it in a better way.

**Comment by aryanshar** [comment]
Thanks a heap. I'll try to help as much as I can :)

**Pull request merged**
