### PR TITLE
Fixes #1280 - removed cursor pointer

### LINKED ISSUE #1280: Cursor on div instead of input / label
This is a very minor issue. You can hover the mouse out in the white space and the cursor switches to pointer, as if you can click a category for "What seems to be the trouble?", but selection isn't possible.

sc

The div for these items contains:
```css
.wc-Form-radio {
  cursor: pointer;
}
```

Maybe we should move this to the radio input and label?

### PR DESCRIPTION
**Pull request by magsout**
Closed #1280

### CODE REVIEW

**Comment by zoepage** [comment]
As #1280 was closed, I modified the title.
https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by magsout** [comment]
>As #1280 was closed

???

**Comment by karlcow** [comment]
@zoepage the issue #1280 is not closed. It will be closed by merging this pull request if it contains indeed the keyword Fixes, Fix, Resolves etc. Once @adamopenweb has reviewed the Pull request.

**Comment by zoepage** [comment]
@magsout @karlcow weird. I was 100% sure it was closed this morning. 0_o

Anyway, changed the title so it contains a keyword.

**Comment by zoepage** [comment]
@magsout right. 

As far as I understood before, there is a process that should be followed, right?
https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#submission-guidelines - Step 9. (Just to clarify for myself, b/c I am still trying not to make mistakes all the time.)

**Comment by karlcow** [comment]
@magsout  @zoepage is right and I have been strict with her on it too. We are trying to enforce a convention of writing for the messages. This should help us to avoid surprises.

**Comment by adamopenweb** [comment]
LGTM r+
Thanks @magsout! 😀

**Pull request merged**
