### PR TITLE
Fixes #2422 - Add autogrow to bugform steps to reproduce field

### LINKED ISSUE #2422: The bug reporting/comments area is not automatically expanded
**Environment:**
Browser / Version: Chrome 66 (Desktop), Firefox Nightly 61.0a1 (Desktop)
Operating System: Windows 10

**Steps to Reproduce:**
1. Go to https://webcompat.com/issues/new
2. Type a lot of text in the "What steps did you take before this problem occurred?" field.

**Expected Behavior:**
The bug reporting/comments area is automatically expanded to accomodate the text typed.

**Actual Behavior:**
The bug reporting/comments area is not automatically expanded.

**Notes:**
1. Screen capture attached.
2. Reproducible both on Chrome and Firefox.

Watchers:
@softvision-sergiulogigan
@softvision-oana-arbuzov

sv;

image

### PR DESCRIPTION
**Pull request by Regaddi**
r? @zoepage 

I decided to expand and reduce the textarea based on the text rows. I set the maximum height to `window.innerHeight / 2` as a first best guess, but I'm open to other opinions. If needed we can also make this configurable (e.g. by using a data-attribute on the field).

I also pushed these bits of code into the `bugform.js` file, but maybe the functionality should be extracted later on (comparable issue like #2268).

### CODE REVIEW

**Comment by karlcow** [comment]
This was tested on http://localhost:5000/issues/new
Let's try on the comments.
Same thing. not working.

capture d ecran 2018-05-09 a 08 36 42


```
→ git status
On branch review-2422
Your branch is up-to-date with 'webcompat/issues/2422'.
```

`npm install` and `grunt` were performed before testing.

**Comment by Regaddi** [comment]
@karlcow: Have you deleted your cache? I needed to force clear my browser caches.

**Comment by Regaddi** [comment]
Aha! It's not working as expected, when pasting in longer text. Will check that immediately!

**Comment by miketaylr** [comment]
Sorry, I've been swamped with other stuff. Will try to find the time for review tomorrow!

**Comment by Regaddi** [comment]
So I made a few adjustments to have everything set up and calculated correctly.
I use the elements `dataset` to store some data dynamically, especially the initial `rows` attribute value and the height per row in pixels (since I don't want to calculate this on each event trigger).

From my side it should be good now: entering text manually and pasting text in increases the text fields height.

Are there any more opinions on @zoepage's [comment](https://github.com/webcompat/webcompat.com/pull/2442#discussion_r186862856)?
If not, I'd go with her suggestion and decrease the maximum height of the textfield to 1/3 of the screen height.

**Comment by karlcow** [comment]
@Regaddi Speaking to myself, and creating long comments all the time, the more I can maximize, the better for me. So limiting to an height is not a very good fit for me. Having real estate for working out the prose is good.

**Comment by karlcow** [comment]
Reading again carefully @zoepage comment to be sure I don't misinterpret it.

> i think half of it might be too much, especially on big screens. Maybe 1/3 should be enough?

Maybe the criteria is not the screen height. Probably the thing which matters is the browser height. For example, this is me right now for a comment I have not yet finished.

capture d ecran 2018-05-22 a 17 05 16

The height of this screenshot is 3162px and if the comment is getting longer I will probably stretch it even more depending if it helps me to understand visualize my comments with the code.

Hope it helps. So to rephrase my habits: 

I maximize the textarea for the current browser height when having long comments of code.
I can see how it would become difficult when the textarea is higher than the viewport and for this, probably limiting to 90% of the **browser height** would be good.

**Comment by miketaylr** [comment]
Ping @karlcow. Any objections to merging now?

**Comment by karlcow** [comment]
ah missed it. Not tested yet. but let's merge and learn from it.

**Pull request merged**
