### PR TITLE
Issue #2681 - Fixes lists and nested lists display in webcompat.com 

### PR DESCRIPTION
**Pull request by rafia95**
This PR fixes issue #2681 

Please provide enough information so that others can review your pull request:
The css code added to issues.css displays the bullet points for lists in issues page on the site webcompat.com

- [Yes ] I have read the [Pull Request + Code Style Guidelines](https://github.com/webcompat/webcompat.com/blob/master/docs/pr-coding-guidelines.md) thoroughly.

### CODE REVIEW

**Comment by rafia95** [comment]
@magsout can you review this please? I had to do it this way so now it is one commit with one message.  Thank you!

**Comment by karlcow** [comment]
Thanks a lot @rafia95 for making the modifications.
Could you edit your commit message :)
1. It is too long
2. No need for 'webcompat.com' in `Fixes lists and nested lists display in issues`

I can do it during the merge if you prefer. :)
in case you want to do it.

```bash
git rebase -i HEAD~1
# replace pick with r
# edit the commit line
# save/close
# rebase message is successful.
git push -f origin 2681/1 
```

As for the review by @magsout. This has already been done in #2692

Tell me if you want to edit the commit message :)

**Comment by karlcow** [comment]
@rafia95 Let me kick it again. :)

**Comment by karlcow** [comment]
@rafia95 This is working. Thanks a lot. 🎉

**Comment by rafia95** [comment]
@karlcow thank you so much for your help. Sorry for all the mess with git rebase, happy that I have learned about git rebase now :)

**Comment by magsout** [comment]
awesome @rafia95 👍

Thanks @karlcow ❤️

**Pull request merged**
