### PR TITLE
Fixes #2757 - Adds missing lib to issues on concat.js

### LINKED ISSUE #2757: [v15.4.0] [broken release] MarkdownSanitizerMixin
@miketaylr @marimeireles 

We are not out yet of the woods. :) #2727 is not completely over. :)
```
 ReferenceError: MarkdownSanitizerMixin is not defined[Learn More] issues.min.js:7:15902

    <anonymous> https://webcompat.com/js/dist/issues.min.js?3054c48ab8310c374912a235d2407e15:7 
```

### PR DESCRIPTION
**Pull request by marimeireles**
r? @miketaylr

### CODE REVIEW

**Comment by marimeireles** [comment]
Sorry, I think I was testing something wrong. Let me run a few more tests.

**Comment by miketaylr** [comment]
My baddddd, I should have caught this in the other review. 🙈

**Comment by marimeireles** [comment]
It's okay!
Thanks a lot for the help :)

**Comment by karlcow** [comment]
Thanks! Just a quick deploy on staging.
https://staging.webcompat.com/issues/100

**Comment by karlcow** [comment]
hmm no tests so not detected. 
but this markdown-it replacement is also breaking #2548 #1336  (which I don't mind :) but leaves us with dead code.)

https://github.com/webcompat/webcompat.com/blob/40c57d51cd033987ad92357d3dfabe48db4a32f3/webcompat/static/js/lib/issues.js#L57-L85

**Pull request merged**
