### PR TITLE
Improved design for the link "download add on" the small device, fixed #753

### LINKED ISSUE #753: Navbar Small Device
capture d ecran 2015-10-07 a 07 52 40

Maybe replace download label by an icon

### PR DESCRIPTION
**Pull request by magsout**
Before : 
capture d ecran 2015-12-09 a 09 07 46

After: 
capture d ecran 2015-12-09 a 09 06 10

r?/ @karlcow

### CODE REVIEW

**Comment by karlcow** [comment]
Wonderful @magsout !

* Commit messages with the issue number :)   #753 
* And the Pull request with a Fix #753

In git, you can edit multiple messages with rebase.
http://www.git-scm.com/book/en/v2/Git-Tools-Rewriting-History#Changing-Multiple-Commit-Messages
Apart of that perfect.

**Comment by magsout** [comment]
heu, ooops, I missed a commit ....

**Comment by magsout** [comment]
ah ah ok, I commit with 0 file add, so there is no commit.

**Comment by magsout** [comment]
@karlcow ok fixed, sorry, I missed my commit,

**Comment by karlcow** [comment]
r+ @magsout. Thanks a lot. with :heart:

**Pull request merged**
