### PR TITLE
Issue #855 - Layout broken on contributors page

### LINKED ISSUE #855: Layout broken on contributors page
Noticed by @hallvors on IRC.

The lightbulb is not on the right side anymore. Any ideas @magsout?

### PR DESCRIPTION
**Pull request by magsout**
Close #855 

r? @miketaylr

### CODE REVIEW

**Comment by miketaylr** [comment]
Seems like the tests that are failing are related to the contributors page:

```
FAIL: main - Contributors - clicking first section closes it (10563ms)
```

Maybe we need to add `js-blah` classes so we don't break them in the future. Will take a look in a bit.

**Comment by magsout** [comment]
let me fixe this

**Comment by miketaylr** [comment]
:100:

**Comment by magsout** [comment]
OK, fixed :+1:

**Comment by miketaylr** [comment]
Woohoo!

**Pull request merged**
