### PR TITLE
Fixes #1711. Ensure change event fires when same image is selected.

### LINKED ISSUE #1711: Unable to use the same attach method 2 times in a row
**Environment:**
Browser / Version: Chrome 60.0.3112.90 (Desktop), Firefox 54.0.1 Release (Desktop)
Operating System: Windows 10

**Steps to Reproduce:**
1. Navigate to: https://webcompat.com/issues/new
2. Attach a supported image (either Drag-and-drop or "Upload screenshot" link).
3. Remove the attached image.
4. Attach a supoorted image (the same method used at step 2).

**Expected Behavior:**
The image is attached.

**Actual Behavior:**
The image is not attached.

**Notes:**
1. Using the other method at step 4, attaches the image.

sv;

### PR DESCRIPTION
**Pull request by miketaylr**
r? @zoepage

### CODE REVIEW

**Comment by miketaylr** [comment]
> One test is failing:

@zoepage Did that fail for you locally? In Chrome or Firefox? Interesting that Travis passed all tests.

**Comment by miketaylr** [comment]
All tests are passing for me locally as well, in Chrome and Firefox.

`0/81 tests failed (3 skipped)`

**Comment by zoepage** [comment]
This failed locally. Ran it twice. Same result. 🤔
The branch is clean and up to date.
screen shot 2017-08-16 at 9 27 45 pm

Which npm / Node version do you have installed?
->node v6.9.2
-> npm  v3.10.9

**Comment by karlcow** [comment]
```bash
workon webcompatcom
git checkout master
git fetch webcompat
git merge webcompat/master
node -v; npm -v
# v6.10.2
# 3.10.10
git checkout -b issues/1711/1 webcompat/issues/1711/1
# Branch issues/1711/1 set up to track remote branch issues/1711/1 from webcompat.
# Switched to a new branch 'issues/1711/1'
python run.py -t
# Starting server in ~*TEST MODE*~
# * Running on http://localhost:5000/ (Press CTRL+C to quit)
# * Restarting with stat
# Starting server in ~*TEST MODE*~
```

Another window and Firefox 55.0.2 

```bash
workon webcompatcom


java -version
# java version "1.8.0_111"
# Java(TM) SE Runtime Environment (build 1.8.0_111-b14)
# Java HotSpot(TM) 64-Bit Server VM (build 25.111-b14, mixed mode)
node_modules/.bin/intern-runner config=tests/intern
```

and… lol?



capture d ecran 2017-08-17 a 10 52 24

**Comment by miketaylr** [comment]
What in the world.

**Comment by miketaylr** [comment]
If tests are passing on Travis, I'm not sure what to do about failures on y'alls local machines. We trust Travis as the main source of truth for tests...

**Comment by miketaylr** [comment]
@zoepage can you change the sleep here to like, 5000 or something and re-run this test? I wonder if we're running into timeouts based on different machines.

https://github.com/webcompat/webcompat.com/blob/master/tests/functional/comments-auth.js#L144

(either way, this test failure shouldn't block, IMO -- these changes are unrelated to the codepaths this test is testing -- issue comment screenshots have nothing to do with `change` events)

**Comment by zoepage** [comment]
> If tests are passing on Travis, I'm not sure what to do about failures on y'alls local machines. We trust Travis as the main source of truth for tests...

Never trust the humans, I agree. 
Rerunning the tests with a 5000 timeout right now, but if you want to merge.. go for it.

**Comment by zoepage** [comment]
FYI, tests are passing :tada:

**Comment by miketaylr** [comment]
> FYI, tests are passing 🎉

thanks!

**Comment by karlcow** [comment]
Unrelated to this PR, but I wonder if @andreastt would be interested by the results in comment https://github.com/webcompat/webcompat.com/pull/1718#issuecomment-322947246 aka Chrome passing all the tests and Firefox randomly failing them.

**Comment by andreastt** [comment]
@karlcow With the limited amount of information that is available here, it is impossible to say anything definite about them. I am assuming you are expecting parity in results and for the Firefox tests to pass.

* The client may not support the [WebDriver specification](https://w3c.github.io/webdriver/webdriver-spec.html)
* The tests may be utilising the API in a way that is not backwards-compatible with Selenium
* Firefox may not yet support a particular feature that is used
* Some of the failures could be systemic, i.e. an underlying problem with infrastructure could be blamed
* ∞

Without a concrete idea what you are doing and what you are expecting the result to be, and a geckodriver trace-level log (see the README on how to emit one), I can only make educated guesses what might be causing Firefox to “randomly fail them”.

**Comment by miketaylr** [comment]
(note: travis is now failing on that same test that @zoepage mentioned, lol -- i'll push a follow up fix to master)

**Comment by zoepage** [comment]
@miketaylr is the reason for the failing test the timeout for the response?

**Pull request merged**
