### PR TITLE
Fixes #2823 - Adds type-fastclick to the list of valid extra labels

### LINKED ISSUE #2823: Add type-fastclick label to EXTRA_LABELS
Report Site Issue has the ability to detect FastClick library now. 
We can add the `type-fastclick` to EXTRA_LABELS.

Purpose: more easily detect issues related to touch and mobile devices created by fastClick library.

### PR DESCRIPTION
**Pull request by karlcow**
This PR fixes issue #2823

## Proposed PR background

Report Site Issue will signal if a website has the library fastclick.
This PR grabs the signal in the report and adds a label for it.

### CODE REVIEW

**Comment by karlcow** [comment]
@laghee not sure you have seen this one.

**Comment by miketaylr** [comment]
I'm gonna steal this review from @laghee -- she has family in town. :)

**Comment by laghee** [comment]
> @laghee not sure you have seen this one.

Aaargh! Sorry -- totally missed these emails. Need better filters... ;p

**Comment by miketaylr** [comment]
@karlcow can we deploy please :)

**Comment by karlcow** [comment]
yup it's planned for today.

**Pull request merged**
