### PR TITLE
Fixes Issue #1924 make animation of bug in hero section run just once

### PR DESCRIPTION
**Pull request by deeptibaghel**
The bug now starts moving on mouse over and runs only once.

### CODE REVIEW

**Comment by miketaylr** [comment]
thanks @deeptibaghel!

r? @zoepage

**Comment by zoepage** [comment]
Thanks @deeptibaghel :)

The initial idea was different, but I actually like it more this way!
(Now you kind of have to hunt the bug towards the bulb.) Could we add a small change and remove the animation of the bug where it falls down? So it would end when it arrives at the bulb and wobble a little bit? Please let me know, if you have any questions.

Thanks for the great idea. That added the last missing piece.

**Comment by deeptibaghel** [comment]
@zoepage , i think now it's better :)

**Comment by zoepage** [comment]
Love it! Thank you!

**Comment by miketaylr** [comment]
This is very cool, thank you @deeptibaghel.

**Pull request merged**
