### PR TITLE
issue #1111. Blah blah this should be bad, so bad. Very very bad.

### PR DESCRIPTION
**Pull request by miketaylr**
(just testing, please don't merge!)

You are welcome to contribute to this project. Here are the guidelines we try to stick to in this project.
You are welcome to contribute to this project. Here are the guidelines we try to stick to in this project.
You are welcome to contribute to this project. Here are the guidelines we try to stick to in this project. You are welcome to contribute to this project. Here are the guidelines we try to stick to in this project.

### CODE REVIEW

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: fd5fe200d09a598cfdb50714f2d0c6dff0e81344
  * Your commit message body contains a line that is longer than 100 characters
  * Commits must be in the following format: **%{type} #%{scope} - %{description}**
  * Invalid type. Valid types are **Issue, Fixes, Bug**

Guidelines are available at https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#submission-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
There were the following issues with your Pull Request

 * Commit: fd5fe200d09a598cfdb50714f2d0c6dff0e81344
  * Your commit message body contains a line that is longer than 100 characters
  * Commits must be in the following format: **%{type} #%{scope} - %{description}**
  * Invalid type. Valid types are **Issue, Fixes, Bug**

 * Commit: ff0b3a7176631d50605de64a0d15abf6210053f3
  * Commits must be in the following format: **%{type} #%{scope} - %{description}**

Guidelines are available at https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#submission-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by GitCop** [comment]
Hello, thanks for your contribution! I found the following issues for you to fix:

 * Commit: fd5fe200d09a598cfdb50714f2d0c6dff0e81344
  * The commit body should not exceed 100 characters per line.
  * Your commit should look like this:  
  
`Issue #XXXX - Adds Foo to BarFactory`
  * Invalid type. Valid types are **Issue, Fixes**

 * Commit: ff0b3a7176631d50605de64a0d15abf6210053f3
  * Your commit should look like this:  
  
`Issue #XXXX - Adds Foo to BarFactory`

 * Commit: 5d46c8f59f86427332cccc19393a26f2f9d0457f
  * Your commit should look like this:  
  
`Issue #XXXX - Adds Foo to BarFactory`

Guidelines are available at https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#submission-guidelines

---
This message was auto-generated by https://gitcop.com

**Comment by miketaylr** [comment]
Updated `Your commit should look like this:` => `Your commit message should look like this:`

**Pull request closed without merging**
