### PR TITLE
Fixes issue #2203 UnboundLocalError on milestones_content

### PR DESCRIPTION
**Pull request by deeptibaghel**
Initialized variable milestones_content.

### CODE REVIEW

**Comment by karlcow** [comment]
One weird thing though… @miketaylr do you understand why all tests passed but Travis fails?

**Comment by zoepage** [comment]
@karlcow this is a known issue with Browserstack and will hopefully be fixed soon (again). I'd rather trust our local tests here.

**Comment by karlcow** [comment]
@zoepage Thanks a lot!

**Comment by miketaylr** [comment]
> this is a known issue with Browserstack and will hopefully be fixed soon (again). I'd rather trust our local tests here.

@zoepage can you link to the issue (I assume you mean Travis and not Browserstack) so I can learn more about it? I've never seen this kind of error before. Thanks.

**Pull request merged**
