### PR TITLE
Fixes #1942 - Modifies the Image saving parameters for better quality

### LINKED ISSUE #1942: Upload thumbnails are blurry
Not sure if we can tune the jpeg compression a bit -- I find the thumbnail image to be a little too blurry. 

https://staging.webcompat.com/issues/1308 as an example.

### PR DESCRIPTION
**Pull request by karlcow**
This PR fixes issue #1942

## Proposed PR background

Some  thumbnail images were blurry. 
This is an attempt at improving the quality a little bit by adjusting size and filter.
This also upgrades the library version of Pillow.

### CODE REVIEW

**Comment by karlcow** [comment]
@miketaylr if we deploy this, I would like to have it deployed on staging first. To test the performance issues with our real setup.

**Comment by miketaylr** [comment]
> I would like to have it deployed on staging first. To test the performance issues with our real setup.

@karlcow deployed to staging!

```
[webcompat.com] out: Installing collected packages: Pillow
[webcompat.com] out:   Found existing installation: Pillow 4.0.0
[webcompat.com] out:     Uninstalling Pillow-4.0.0:
[webcompat.com] out:       Successfully uninstalled Pillow-4.0.0
[webcompat.com] out: Successfully installed Pillow-5.2.0
```

**Comment by miketaylr** [comment]
(also re-kicked travis)

**Comment by miketaylr** [comment]
Changes LGTM, feel free to merge and add the changelog label if you think it's an improvement.

**Comment by karlcow** [comment]
> deployed to staging!

Thanks.
I did a last test
https://staging.webcompat.com/issues/1642
and it went well. Let's deployed this.

3.9 Mo (2222x2388) to 172K (with a 1024, HAMMING).

**Pull request merged**
