### PR TITLE
Fixes #564 - fix history navigation from issues

### LINKED ISSUE #564: Unable to go back from Issues page
### Steps to reproduce ###
1. Go to https://webcompat.com
2. Click on "New Issues" to open that page
3. Click the browser's back button

### What should happen ###
The webcompat.com front page should be displayed.

### What actually happens ###
Nothing. The spinner appears briefly but that's it. No error message in the console. Tried in Firefox and Blink/WebKit browsers.

### PR DESCRIPTION
**Pull request by miketaylr**
The problem was that I was creating an infinite `pushState` loop, more or less. Go back and push two more states on the history stack.

This changes a bunch of things, but mostly it's a simplification. A lot less circular method calls.

I'm going to push this to staging so you can play around with it. I need to file one follow up issue that's unrelated to this bug, but is about `q=blah` in the URL should be able to load that search in a fresh tab.

r? @magsout

### CODE REVIEW

**Comment by magsout** [comment]
I can't deploy on my localhost (my MBA is .... not avalaibale :( )

hum there is some trouble with staging ? bad gateway ?

**Comment by miketaylr** [comment]
Oh weird, let me debug.

**Comment by miketaylr** [comment]
oops.

```
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python2.7/dist-packages/flask/app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "./webcompat/views.py", line 142, in index
    browser=browser_name)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 128, in render_template
    context, ctx.app)
  File "/usr/local/lib/python2.7/dist-packages/flask/templating.py", line 110, in _render
    rv = template.render(context)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 969, in render
    return self.environment.handle_exception(exc_info, True)
  File "/usr/local/lib/python2.7/dist-packages/jinja2/environment.py", line 742, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/webcompat/staging.webcompat.com/webcompat/templates/index.html", line 1, in top-level template code
    {%- extends "layout.html" -%}
  File "/home/webcompat/staging.webcompat.com/webcompat/templates/layout.html", line 30, in top-level template code
    <link href="{{ url_for('static', filename='css/webcompat.min.css') }}?{{ bust_cache() }}" type="text/css" rel="stylesheet">
  File "./webcompat/views.py", line 40, in bust_cache
    return hashlib.md5(app.config['STARTUP']).hexdigest()[:14]
KeyError: 'STARTUP'
```

**Comment by miketaylr** [comment]
OK, merged in master and deployed. There were some caching changes that this branch only had part of, so it exploded. Should be working now @magsout.

**Comment by magsout** [comment]
r+

**Comment by miketaylr** [comment]
Thank you!

**Pull request merged**
