### PR TITLE
Issue #3348 - Update contributing documentation

### PR DESCRIPTION
**Pull request by ksy36**
I've updated screenshots and text a bit :)

r? @karlcow

### CODE REVIEW

**Review by karlcow — CHANGES_REQUESTED** [review]
Hi @ksy36 
That's wonderful.


Could you put the new images though [ImageOptim](https://imageoptim.com/mac)? I just did for the first one, and I save 58%.

Capture d’écran 2021-07-12 à 15 25 58

Thanks!

**Comment by ksy36** [comment]
Updated the images, thanks for the tip @karlcow

**Review by karlcow — APPROVED** [review]
Thanks a lot @ksy36 
That is a good update to the documentation.

**Comment by ksy36** [comment]
Thanks!

**Pull request merged**
