### PR TITLE
Issue #915 - fixed position and z-index FormUpload

### LINKED ISSUE #915: [functional] Upload link in comments doesn't work anymore
Since this morning, it seems the upload link for images is not working.

### PR DESCRIPTION
**Pull request by magsout**
Close #915 
r? @karlcow 

I guess it was a z-index issue.

### CODE REVIEW

**Comment by miketaylr** [comment]
Hmm, how strange. If I click anywhere *except* for the "Attach a Screenshot image" text -- it works.

BUT if I change the inner `<label>` (without the `for=''`) to a `<p>` it works. Possible Firefox bug? Or is there something magical about nested label elements that I don't know about?

**Comment by miketaylr** [comment]
Another issue, possibly related to the fix from https://github.com/webcompat/webcompat.com/pull/916/files is that now really big images are really big: https://cloudup.com/iVED0Y-qpZP

(If you're hooked up to the webcompat-tests repo, see Issue 321)

**Comment by magsout** [comment]
@miketaylr  you tried with my PR ?

**Comment by magsout** [comment]
@miketaylr 
>Another issue, possibly related to the fix from https://github.com/webcompat/webcompat.com/pull/916/files is that now really big images are really big: https://cloudup.com/iVED0Y-qpZP

ARGggggggg

**Comment by miketaylr** [comment]
> @miketaylr you tried with my PR ?

@magsout  yeah, I pulled down this branch.

**Comment by magsout** [comment]
jou739

**Comment by miketaylr** [comment]
hehehe

**Comment by magsout** [comment]
@miketaylr

it works for me http://cl.ly/2Z3O2B2t3p2J

**Comment by magsout** [comment]
>Another issue, possibly related to the fix from https://github.com/webcompat/webcompat.com/pull/916/files is that now really big images are really big: https://cloudup.com/iVED0Y-qpZP

@miketaylr fixed by https://github.com/webcompat/webcompat.com/pull/917

**Comment by karlcow** [comment]
```
→ git checkout -b deleteme upstream/url-link-upload
Branch deleteme set up to track remote branch url-link-upload from upstream.
Switched to a new branch 'deleteme'
(webcompatcom)16:14:24 ~/code/webcompat.com
→ python run.py
secrets /Users/karl/code/webcompat.com
 * Running on http://localhost:5000/ (Press CTRL+C to quit)
 * Restarting with stat
secrets /Users/karl/code/webcompat.com
```

So the uploading form for bug reporting is working r+ for this one.

I could not test the login for comment because the callback is broken on my local build right now on a clean profile.

**Comment by karlcow** [comment]
Thanks a lot @magsout

**Comment by miketaylr** [comment]
> I could not test the login for comment because the callback is broken on my local build right now on a clean profile.

Hmm, that's not good. A few random things to try:

1) delete the local session database, restart the app
2) from your github settings, revoke the app permission and do the auth dance again: https://github.com/settings/applications

**Comment by karlcow** [comment]
@miketaylr that was my bad. ^_^ sorry about the noise.

**Comment by miketaylr** [comment]
Ah, cool. Glad it's working. :fish_cake:

**Pull request merged**
