### PR TITLE
Fixes #1290 - change report bug link to new issues endpoint

### LINKED ISSUE #1290: "Report a bug" should link to /issues/new
To fix this, the link in the following template should point to `/issues/new`:

https://github.com/webcompat/webcompat.com/blob/93662e358169e7443445217fe7d2a5c6151c9b21/webcompat/templates/shared/nav.html#L11-L14

### PR DESCRIPTION
**Pull request by zoepage**
#1290 

@miketaylr ? :)

### CODE REVIEW

**Comment by miketaylr** [comment]
Sweet! Can you just update the commit message? Currently it's "Issue #1290 - change report bug link to". Something like "...link to new issue endpoint" or "...link to /issues/new"?

No need to send a new PR you can just do: 

`git commit --amend`
...change commit message...
`git push -f`

But, you probably already knew that. 😄 

(Also, ignore the test failure. Looks like the Intern 3 upgrade still has some warts. Tracking in https://github.com/webcompat/webcompat.com/issues/1324.)

**Comment by zoepage** [comment]
@miketaylr as you changed the title already, it's good or should I still change it to keep the history clean?

**Comment by miketaylr** [comment]
> @miketaylr as you changed the title already, it's good or should I still change it to keep the history clean?

Nope, no need to change the title -- but the commit should still get fixed up.

**Comment by zoepage** [comment]
@miketaylr done. I hope, it's right this time :)

**Comment by miketaylr** [comment]
Perfect, thank you!

**Pull request merged**
