### PR TITLE
1084/1 spring cleaning of syntax and imports

### PR DESCRIPTION
**Pull request by karlcow**
Nothing dramatic, juts minor and cosmetic changes. 
But a trajectory correction to avoid more discrepancies.

### CODE REVIEW

**Comment by miketaylr** [comment]
Nice. Love contributions like this. ❤️

**Comment by miketaylr** [comment]
Hm, Travis is not very happy:

```
$ nosetests

F.F..............................E....
```

I just retriggered the build, but can you locally verify that tests are passing in your branch @karlcow?
I just pulled down your code and I don't have failures here.

**Comment by karlcow** [comment]
Sure.

```
→ git status
On branch 1084/1
nothing to commit, working directory clean
(webcompatcom)18:03:08 ~/code/webcompat.com
→ nosetests
......................................
----------------------------------------------------------------------
Ran 38 tests in 7.458s

OK
```

**Comment by miketaylr** [comment]
Cool, thanks @karlcow. I think this is a rate limit issue from Travis IPs. Something for us to solve in the future.

**Pull request merged**
