### PR TITLE
Fixes #2607 - Fixes typo in secrets.py.example

### LINKED ISSUE #2607: Typo in `secrets.py.example`
Spelling of GitHub should be `GitHub` instead of `GiHub` at https://github.com/webcompat/webcompat.com/blob/master/config/secrets.py.example#L40

### PR DESCRIPTION
**Pull request by shristit**
Fixes #2607 
There was a typo in Github spelling. This PR is to fixed the same . If i need to create a issue for the same please let me know

### CODE REVIEW

**Comment by miketaylr** [comment]
> If i need to create a issue for the same please let me know

@shristit If you wouldn't mind, please create an issue before we merge. As a project, we require an issue to be associated with each pull request. Thanks!

**Comment by miketaylr** [comment]
It would also be good to rebase your commits, so we're not merging in a "merge commit". This should has some pretty good advice for learning how to do it: https://gist.github.com/ravibhure/a7e0918ff4937c9ea1c456698dcd58aa

If you get stuck, please ask in this issue. :)

**Comment by shristit** [comment]
> > If i need to create a issue for the same please let me know
> 
> @shristit If you wouldn't mind, please create an issue before we merge. As a project, we require an issue to be associated with each pull request. Thanks!

Hi @miketaylr yeah doing that , i was confused about it because it was a simple typo mistake , will create a issue for sure from next time :smiley: 

>(in the future, be sure to ping a reviewer, for example r? @miketaylr)

Yeah will do that thanks for telling me :)

**Comment by miketaylr** [comment]
We still have 2 commits here -- here's how you can get rid of the 2nd merge commit:

`git pull --rebase upstream master`

This assumes you have an upstream remote: https://help.github.com/articles/configuring-a-remote-for-a-fork/

Then you can go ahead and push your commit again:

`git push -f`

(You need the `-f`, because you've changed the hash of the commit.)

**Comment by shristit** [comment]
Hi @miketaylr thanks for the help , made the changes :)

**Comment by miketaylr** [comment]
Thanks!

**Pull request merged**
