### PR TITLE
Fixed typo in CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by haseebgit**
@miketaylr r?

### CODE REVIEW

**Comment by miketaylr** [comment]
(if it's not possible to fix from the web interface, if you're still using that, you can close this PR and submit a new one)

**Comment by haseebgit** [comment]
@miketaylr should I create a issue and then fix the commit msg?

**Comment by miketaylr** [comment]
> @miketaylr should I create a issue and then fix the commit msg?

Generally that's how we do it. But for something as simple as this you could do something like:

`No issue - fix typo in CONTRIBUTING.md`

**Comment by haseebgit** [comment]
@miketaylr r? :D

**Comment by miketaylr** [comment]
💯

**Pull request merged**
