### PR TITLE
fix #1110 - Adds explicit r+ rule for merging

### LINKED ISSUE #1110: Proposal: Not merging your own PRs without an explicit r+ or lgtm
Right now the Submission Guidelines mention asking for review explicitly:

https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#submission-guidelines

I think we should add a section about not merging your own PR unless the person reviewing has left an explicit "r+" or "lgtm" comment. Possible ways this happens:

1) Reviewee sends PR, asks for r?. Reviewer reviews, leaves r+.
2) Reviewee sends PR, asks for r?. Reviewer reviews, points out issues, asks for changes. Reviewee makes changes, asks again for r?, repeat until r+.

(admins should be able to merge w/o r+ or lgtm, in the case of fixing broken builds, etc.)

We should be able to enforce this w/ a bot: https://github.com/blog/2051-protected-branches-and-required-status-checks, but for now we can just trust each other.

Thoughts? @webcompat/core-developers

### PR DESCRIPTION
**Pull request by karlcow**
I also reorganized the prose to have a step by step list, and make a unique list instead of multiple list (markdown kung-fu)

### CODE REVIEW

**Comment by miketaylr** [comment]
(karl didn't ask for review yet, which is good because I'm about to revert master to the 2.6.1 tag state -- there shouldn't be any merge conflicts for this PR after that's done)

**Comment by karlcow** [comment]
yup. When you have reverted, I can create another branch. with all the necessary fixes. No issue.

**Comment by miketaylr** [comment]
Ah crap. I made a mess for you @karlcow. 

(Your fork was up to date, and I went back in time on you) -- sorry about that. All done with history shenanigans.

**Comment by miketaylr** [comment]
But r+ once your new branch is ready -- changes look great, thanks!

**Comment by karlcow** [comment]
Closing this PR in favor of https://github.com/webcompat/webcompat.com/pull/1112

**Pull request closed without merging**
