### PR TITLE
Fixes #945 - adding grunt lint for travis support

### LINKED ISSUE #945: Add travis lint task (grunt, webpack?)
So I don't break the stupid thing again. :sob: :person_frowning: 

https://www.npmjs.com/package/grunt-travis-lint

### PR DESCRIPTION
**Pull request by zoepage**
Test run with failing travis file

### CODE REVIEW

**Comment by zoepage** [comment]
r? @miketaylr 
Feel free to decline, if this isn't anything we need. As I was not 100% sure how to recreate your issue in #945, I am not sure if this also fits your needs (as you filed the issue). :)

**Comment by miketaylr** [comment]
(I think I just created a merge conflict for you..., but I'll clean it up)

**Comment by miketaylr** [comment]
@zoepage PR looks good, I guess we don't want to commit the "bork travis file" commit tho -- want to remove it? feel free to merge then.

**Comment by zoepage** [comment]
@miketaylr Sorry, old habits. The "bork" commit was mainly for you to see that it has been tested, so you wouldn't need to do this anymore and would see, what I've changed. I'm used to clean up the commits after r+ and then merge. 

Will try to remember next time. Thanks for cleaning up! :)

**Comment by miketaylr** [comment]
> Will try to remember next time. Thanks for cleaning up! :)

No worries!

**Comment by zoepage** [comment]
@miketaylr changed (also added info to the CONTRIBUTE.md that we also lint the travis config now).

**Comment by miketaylr** [comment]
Looks good! I removed the extra "rebase master" commit to keep history clean. Typically when I rebase from a branch I do:

`git pull --rebase origin master` (fix any conflicts...)
`git push -f`

Will merge once tests are green, thanks!

**Pull request merged**
