### PR TITLE
Fixes #583 - Check pip dependencies on starting the server

### LINKED ISSUE #583: Check the dependencies before starting the server
Sometimes we change the modules, etc. For example,

```
-WTForms==1.0.5
+WTForms==2.0.2
```

I wonder if we should add a checker before run. Where we would get a pseudo UI like:

```
python run.py

** You need first to update your python/js before starting webcompat.com
@@Instructions to do so@@
```

On the python side, probably something with `pip install --no-install`
or making a diff in between libraries installed and the ones in requirements.txt

For JavaScript, I don't know how it is checked. 
Also when do you need to run again grunt.

### PR DESCRIPTION
**Pull request by miketaylr**
I wonder if we shouldn't put this behind a command line argument, given how rarely we update a dependency.

r? @karlcow

### CODE REVIEW

**Comment by karlcow** [comment]
> I wonder if we shouldn't put this behind a command line argument, given how rarely we update a dependency.

The issue is not to ask for the check, but that the app warns you that there is an issue, because it has been updated. Specifically because it's a rare event, so you forget to check. :cactus:

**Comment by miketaylr** [comment]
@karlcow I like your version better--mine is just doing magical string comparison. Do you want to send a new PR or make your changes in this branch?

**Comment by miketaylr** [comment]
> Specifically because it's a rare event, so you forget to check. 

Yeah, good point. +1

**Comment by miketaylr** [comment]
@karlcow did you want to write a patch with your suggestions?

**Comment by karlcow** [comment]
Let me dive into this again. 
Reminder to self: finish it when it's still hot. :ramen:

**Comment by karlcow** [comment]
OK I send a new pull request. We can close this one.

**Pull request closed without merging**
