### PR TITLE
Fixes #2110: Fix image upload tests.

### LINKED ISSUE #2106: Get tests green on refactor branch
Once this is done, no more PRs into refactor will be allowed without fixing broken tests.

### LINKED ISSUE #2110: Fix image-upload-non-auth.js
Blocks #2106.

```
✓ firefox on darwin 17.4.0 - Image Uploads (non-auth) - postMessaged dataURI preview (2.17s)
✓ firefox on darwin 17.4.0 - Image Uploads (non-auth) - postMessaged blob preview (6.5s)
✓ firefox on darwin 17.4.0 - Image Uploads (non-auth) - uploaded image file preview (1.596s)
✓ firefox on darwin 17.4.0 - Image Uploads (non-auth) - postMessaged dataURI image doesn't upload before form submission (1.765s)
✓ firefox on darwin 17.4.0 - Image Uploads (non-auth) - postMessaged blob image doesn't upload before form submission (1.527s)
✓ firefox on darwin 17.4.0 - Image Uploads (non-auth) - uploaded image file doesn't upload before form submission (1.63s)
Error fetching http://localhost:5000/?open=1
× firefox on darwin 17.4.0 - Image Uploads (non-auth) - remove image upload button (10.407s)
    NoSuchElement: [POST http://localhost:4444/wd/hub/session/84faf848-424a-9049-82af-a7766c86da5d/element / {"using":"css selector","value":".remove-upload"}] Unable to locate element: .remove-upload
    For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
    Build info: version: '3.5.2', revision: '10229a9020', time: '2017-08-21T17:54:21.164Z'
    System info: host: 'omg-5', ip: '192.168.2.83', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.3', java.version: '1.8.0_144'
    Driver info: driver.version: unknown
      at Object.openPage  <tests/functional/lib/helpers.js:27:8>
      at Test.remove image upload button [as test]  <tests/functional/image-uploads-non-auth.js:138:27>
      at <src/lib/Test.ts:260:47>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:36:12>
      at Object.openPage  <tests/functional/lib/helpers.js:29:8>
      at Test.remove image upload button [as test]  <tests/functional/image-uploads-non-auth.js:138:27>
      at <src/lib/Test.ts:260:47>

Error fetching http://localhost:5000/?open=1
× firefox on darwin 17.4.0 - Image Uploads (non-auth) - double image select works (10.404s)
    NoSuchElement: [POST http://localhost:4444/wd/hub/session/84faf848-424a-9049-82af-a7766c86da5d/element / {"using":"css selector","value":".remove-upload"}] Unable to locate element: .remove-upload
    For documentation on this error, please visit: http://seleniumhq.org/exceptions/no_such_element.html
    Build info: version: '3.5.2', revision: '10229a9020', time: '2017-08-21T17:54:21.164Z'
    System info: host: 'omg-5', ip: '192.168.2.83', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.13.3', java.version: '1.8.0_144'
    Driver info: driver.version: unknown
      at Object.openPage  <tests/functional/lib/helpers.js:27:8>
      at Test.double image select works [as test]  <tests/functional/image-uploads-non-auth.js:178:32>
      at <src/lib/Test.ts:260:47>
      at Command.<anonymous>  <tests/functional/lib/helpers.js:36:12>
      at Object.openPage  <tests/functional/lib/helpers.js:29:8>
      at Test.double image select works [as test]  <tests/functional/image-uploads-non-auth.js:178:32>
      at <src/lib/Test.ts:260:47>
```

### PR DESCRIPTION
**Pull request by miketaylr**
Also fixes #2106 (last one).

I can't remember why I added this style when I was working on the form before:

https://github.com/webcompat/webcompat.com/commit/ddaf3e3bcf435791064af1c353ee8491a97bdee5

But apparently I added it to get this use case working... and removing it fixes the tests, and it still works after that. 

(I should have written a better commit message.)

r? @zoepage

### CODE REVIEW

**Comment by miketaylr** [comment]
@zoepage I'm not sure why those other tests are failing for you...

`node ./tests/functional/_intern.js functionalSuites=tests/functional/image-uploads-non-auth.js`

```
Total: [✓✓✓✓✓✓×✓✓✓✓✓✓✓×✓] 16/16
Passed: 14  Failed: 2   Skipped: 0

Fx:         [✓✓✓✓✓✓×✓] 8/8, 1 fail
Chr 64 Mac: [✓✓✓✓✓✓×✓] 8/8, 1 fail
```

But yeah, wtf. This was passing for me last night. Let me look again tonight.

**Comment by miketaylr** [comment]
> Second issue is that the upload context menu opens in Chrome, but doesn't close.

@zoepage can you clarify? What is the upload context menu?

**Comment by miketaylr** [comment]
I get different results than you, @zoepage. The only failures for me in Firefox are related to this bug.

screen shot 2018-02-21 at 11 11 29 am

(i'll investigate the chrome failures as well)

How are you invoking tests?

**Comment by zoepage** [comment]
Let me re-check tonight.

**Comment by miketaylr** [comment]
> @zoepage can you clarify? What is the upload context menu?

Ah, now I see. You mean the file upload modal. I have a fix for that -- for whatever reason Chrome is clicking the `input type=file` when we tell it to click `<main>` (the input is a child of main... it's not important, so I'll pick a different element. 

Might as well fix it in this bug.

**Comment by zoepage** [comment]
I'm running following 

```
$ npm run start:test
$ node ./tests/functional/_intern.js functionalSuites=tests/functional/image-uploads-non-auth.js
```
The output:
```
Total: [✓✓×✓✓×××✓✓✓✓✓✓×✓] 16/16
Passed: 11  Failed: 5   Skipped: 0

Fx:         [✓✓×✓✓×××] 8/8, 4 fail
Chr 64 Mac: [✓✓✓✓✓✓×✓] 8/8, 1 fail
```
Usually I run:
```
$ npm run start:test
$ npm run test
```
where `npm run test:js` translates to `node ./tests/functional/_intern.js && `

**Comment by miketaylr** [comment]
I've got a different branch where all tests are passing for me. Let me open a new PR.

**Pull request closed without merging**
