### PR TITLE
Fixes #2774 - Fixes code blocks with language identifiers

### LINKED ISSUE #2774: Fix code blocks (with language identifiers) on webcompat.com
The following is happening:

If you type something like:

```
```html
<div>
```

It'll break on webcompat.com (not upper cased, that was fixed):

screen shot 2019-01-24 at 15 51 28

If just type your code directly after the three back ticks you'll get the correct output on webcompat:
screen shot 2019-01-24 at 15 51 33

Like shown by Mike on this [issue](https://github.com/webcompat/webcompat-tests/issues/1747).

### PR DESCRIPTION
**Pull request by marimeireles**
It's working for me:

screen shot 2019-01-24 at 19 41 32

r? @miketaylr

### CODE REVIEW

**Comment by marimeireles** [comment]
Ahm... I'm not sure if 

```
/* Code blocks */
pre[class *= "language-"],
.highlight > pre {
  background-color: var(--base-background);
  border: 1px solid #ddd;
  margin: .5em 0;
  overflow: auto;
  padding: 1em;
}
```

this is the right way of adding a new style. It doesn't match the rest of the code style. What do you think @magsout ? Is there anything I could do to make it better?

**Comment by magsout** [comment]
@marimeireles 

>this is the right way of adding a new style. It doesn't match the rest of the code style. What do you think @magsout ? Is there anything I could do to make it better?

you can add this selector.

r+

**Comment by karlcow** [comment]
@marimeireles @magsout 
Deployed. https://github.com/webcompat/webcompat.com/blob/master/CHANGELOG.md#1561---2019-01-28

but I don't see any changes.
https://webcompat.com/issues/22931#issuecomment-457968495

**Comment by marimeireles** [comment]
Hi @karlcow 
I think it's because this other PR wasn't accepted https://github.com/webcompat/webcompat.com/pull/2775

**Pull request merged**
