### PR TITLE
fix #3528 - Fix CSS for description textarea

### LINKED ISSUE #3528: Textarea progress bar hides text when typing
Happens on all browsers. It makes me not able to read what I'm writing for example. See screenshots.

Screenshot_20210202-065150

### PR DESCRIPTION
**Pull request by karlcow**
This PR fixes issue #3528

## Proposed PR background

This is fixing an issue with the CSS in the textarea where the green progress bar was hiding the rest of the text.

### CODE REVIEW

**Comment by emilio** [comment]
That doesn't work on Gecko does it? Because of padding-block-end shenanigans.

**Comment by emilio** [comment]
Why not just changing `.progress-textarea .progress` to `position: relative`? That seems to fix this and as a bonus it doesn't overlap the scrollbars, etc.

**Comment by emilio** [comment]
`content: "";` in that rule is useless btw, and likely to break stuff once browsers implement css-content as per spec.

**Comment by karlcow** [comment]
> That doesn't work on Gecko does it? Because of padding-block-end shenanigans.

It worked on my local build. so that is strange it didn't work for you?

But yes the full thing would benefit of simpler CSS. I don't like very much the way it's done.

**Comment by karlcow** [comment]
Ah long line! gotcha! indeed.

**Pull request closed without merging**
