### PR TITLE
Fixes #1402 Updated join the team section on index page

### LINKED ISSUE #1402: Update "join the team" section on index page
### ToDos
- [x] replace "Join the Team" with “Help Us Improve the Web”
- [x] replace “Learn More” with “Learn more about how to contribute”
- [x]  Adding additional context under “Bug Reporting”
```
Report compatibility issues that you come across on the web.
Report Bugs (link / event is the same)
```

- [x]  Adding additional context under “Bug Diagnosis”
```
Figure out what is causing the issue and help to find a fix.  
Diagnose Bugs (link is the same)
```

- [x]  Adding additional context under “Site Outreach”
```
Locate a contact and reach out to sites to help solve the issue.
Reach out to sites (link is the same)
```
- [x] replace "Bug reporting" icon with https://thenounproject.com/search/?q=report&i=883147
- [x] replace "Bug Diagnosis" icon with https://thenounproject.com/search/?q=diagnose&i=241273
- [x] replace "Site Outreach" icon with https://thenounproject.com/search/?similar=518092&i=518087

- [x] change credentials for icons in https://github.com/webcompat/webcompat.com/blob/master/README.md#icons

---
### Context
Follow up for https://github.com/webcompat/webcompat.com/issues/1283#issuecomment-284574330 and https://github.com/webcompat/webcompat.com/issues/1374#issuecomment-283906535

@lockettm proposed following changes to the content on the "join the team" section on the index page.

> - Replacing "Join the Team" with “Help Us Improve the Web.” One user read this while scanning the page and quickly understood the mission.

> - Replacing “Learn More” with “Learn more about how to contribute.” And linking to the contribute page instead of the About page. One user selected this link to navigate to the Contribute page.

> - Adding additional context under “Bug Reporting,” “Bug Diagnosis” and "Site Outreach.” Although one user clicked one of the links without reading the text, three others read it and seemed to have a better understanding of the process.

### PR DESCRIPTION
**Pull request by nj4710**
Fixes #1402

### CODE REVIEW

**Comment by zoepage** [comment]
Cool, thank you @nj4710 for sending the PR. :)
If you did change the icon, you can request a PR with `r? @zoepage` :)

**Comment by nj4710** [comment]
`r? @zoepage`

**Comment by zoepage** [comment]
@nj4710 thank you for your PR. It's really appreciated! <3

There are a few small changes:
- [ ] The Bug report icon seems really small in comparison to the others. Could you set it to width 130px, please?
- [ ] The outreach icon appears cut off. 
screen shot 2017-03-10 at 9 23 55 pm 

- [ ] Please use SVG's not PNG's (Sorry, I should have mentioned that in the issues.) If you are not sure about the structure, just take a peak over here https://github.com/webcompat/webcompat.com/pull/1416/files

- [ ]  `Locate a contact and reach out to sites to help solve the issue` please add `.` at the end of the sentence. 

- [ ] Please delete the `<br>`s between  `<h3>`s and `<p>`s
- [ ] Please change `<p class="wc-Threesteps-item-text">` to `<div class="wc-Threesteps-item-text">` in all 3 sections. 


Thank you for all your work. You're doing a really great job.

**Comment by zoepage** [comment]
Great @nj4710! We are definitely getting there :)
We might have to change the break point for the view point too, as the content changed.
(see below for more information)

screen shot 2017-03-13 at 11 05 13 am
screen shot 2017-03-13 at 11 05 19 am

Do you want to try && find a good solution for it? Just update the PR when you are done and tested the different resolutions? Thank you <3

**Comment by karlcow** [comment]
What do you think of putting the icons on top of the box aka  `flex-start` instead of `center`

**Comment by nj4710** [comment]
I don't think I understand the meaning of 

> change the break point for the view point
but I tested the solution that karlcow suggested and this is what I got:


I think in this layout, the bug-reporting icon appears small. What do you think? @zoepage

**Comment by zoepage** [comment]
@nj4710 as far as I understand it, @karlcow 's suggestion was just an addition to the fix request comment from me (Karl if i am not correct, please let us know :) )

I think, it needs a different breakpoint in general. the width of the boxes can't become that small as we have way more content than before.

**Comment by karlcow** [comment]
@zoepage @nj4710 yup. Floating in the middle icons was a bit weird to my eye. @zoepage as a good comment on the design. I have the feeling the design would be a lot easier to solve if it was done with flexbox entirely for this part. 

There is probably an issue with the first icon, which has a different thickness or something.

The markup is a bit weird too. 

```html
<div class="wc-Threesteps-item">
    <span class="wc-Threesteps-item-number">
<img src="../img/Bugreporting.svg" alt="Report bugs" class="wc-bug-report-icon">
</span>
    <div class=".wc-Threesteps-content">
        <div class="wc-Threesteps-item-text">
            <h3 class="wc-Report"> Bug Reporting</h3> Report compatibility issues that you come across on the web.</div>
        <p><a id="report-bug-link" href="/?open=1" class="wc-Link">Report bugs</a></p>
    </div>
</div>
```

I would have done something along these lines more or less (and adjusting for breaking points):

```html
<!DOCTYPE html>
<html>

<head>
    <title></title>
    <style>

    .wc-Threesteps {
        display: flex;
        flex-direction: row;
    }

    .wc-Threesteps-item {display: flex;
      flex-direction: row;
      align-items: flex-start;}

    .wc-Threesteps-item-icon {width: 15vh;
      padding: 0 1em;}

    .wc-Threesteps-content {display: flex;
      flex-direction: column;
      align-items: flex-start;}
    h3 {margin:0;}
    </style>
</head>

<body>
    <section class="wc-Threesteps">
        <div class="wc-Threesteps-item">
            <div class="wc-Threesteps-item-icon">
                <img src="./Bugreporting.svg" alt="Report bugs" class="wc-bug-report-icon">
            </div>
            <div class="wc-Threesteps-content">
                <h3 class="wc-Report">Bug Reporting</h3>
                <p>Report compatibility issues that you come across on the web.</p>
                <p><a id="report-bug-link" href="/?open=1" class="wc-Link">Report bugs</a></p>
            </div>
        </div>
        <div class="wc-Threesteps-item">
            <div class="wc-Threesteps-item-icon">
                <img src="./Bugdiagnosis.svg" alt="Report bugs" class="wc-bug-report-icon">
            </div>
            <div class="wc-Threesteps-content">
                <h3 class="wc-Diagnose">Bug Diagnosis</h3>
                <p> Figure out what is causing the issue and help to find a fix.</p>
                <p><a id="report-bug-link" href="/?open=1" class="wc-Link">Diagnose bugs</a></p>
            </div>
        </div>
        <div class="wc-Threesteps-item">
            <div class="wc-Threesteps-item-icon">
                <img src="./Siteoutreach.svg" alt="Report bugs" class="wc-bug-report-icon">
            </div>
            <div class="wc-Threesteps-content">
                <h3 class="wc-Outreach">Site Outreach</h3>
                <p> Locate a contact and reach out to sites to help solve the issue.</p>
                <p><a id="report-bug-link" href="/?open=1" class="wc-Link">Reach out to sites</a></p>
            </div>
        </div>
    </section>
</body>

</html>

```

capture d ecran 2017-03-13 a 15 23 08

**Comment by karlcow** [comment]
@zoepage @nj4710 

I was wondering why the phone + bug icon was smaller with different thickness and size. 
I looked at the sources. I think there might be a bit of work to do on the icons for a better harmony in terms of thickness and sizes. Should be fun to fix them. I haven't yet carefully check all the path. 
Also there is a bit of cruft in the markup that can be removed to make them lighter. 

Bugreporting
```
     viewBox="0 0 64 80" 
     style="enable-background:new 0 0 64 64;" 
```

Siteoutreach
```
     viewBox="0 0 512 640" 
     enable-background="new 0 0 512 512" 
```

Bugdiagnosis
```
     viewBox="0 0 48 60" 
     enable-background="new 0 0 48 48" 
```

**Comment by karlcow** [comment]
ok understood. 
The paths are contour even for lines. Which will not easy to fix.

**Comment by zoepage** [comment]
@karlcow I love the idea, but it feels like we should open a new issue for the flex box rewrite as the scope might get too big. (As the CSS is not well documented, the side effects could be bigger than expected.)

Could you do describe it in a new issue @karlcow ? Would be really appreciated. :)

**Comment by zoepage** [comment]
@karlcow yeah, the paths should be fixed, but maybe also a follow up issue, we could fix later? :)

**Comment by zoepage** [comment]
@nj4710 So, @karlcow is right with 

> The markup is a bit weird too.

How about this... We redo the structure a bit as our needs changed as following:

join-us.html
```
<div class="r-Grid r-Grid--withGutter">
        <div class="r-Grid-cell r-all--4of12 r-maxS--12of12">
          <div class="wc-Threesteps-item">
             <div class="wc-Threesteps-item-number">
               <img src="../img/Bugreporting.svg" alt="Report bugs" class="wc-bug-report-icon">
             </div>
             <div class="wc-Threesteps-content">
                <h3 class="wc-Report"> Bug Reporting</h3>
                <p class="wc-Threesteps-item-text"> Report compatibility issues that you come across on the web. </p>
                <a id="report-bug-link"
                    href="/?open=1"
                    class="wc-Link"
                  >
                    Report bugs
                </a>
            </div>
          </div>
        </div>
```

And add a vertical align for the icons... plus change the breaking point a bit. Tested it in different resolutions && browsers. Should work properly.
threesteps.css
```
 .wc-Threesteps-item-number * {
      vertical-align: middle;
    }

@media all and (max-width: 48.12em) {

      .wc-Threesteps .r-all--4of12 {
        width: 100%;
      }

    }
```

@nj4710 would you be ok with this?

**Comment by nj4710** [comment]
Sorry my bad :) I should have thought about vertical aligning. Will fix that ASAP. @zoepage

**Comment by zoepage** [comment]
thank you @nj4710 <3

**Comment by karlcow** [comment]
Excellent. Let's open follow-up issues.

**Comment by nj4710** [comment]
I had to make a new branch and make a new pull request(as I experimented on a lot of things in that branch). Is it alright? 

Now, this solution looks better than the previous ones. The first two icons need fixing. Karl has already opened a new issue about it. If you think that anything can be improved in this one, please do let me know:) Thanks @zoepage

**Comment by miketaylr** [comment]
> I had to make a new branch and make a new pull request(as I experimented on a lot of things in that branch). Is it alright?

It sounds like this one can be closed in favor of #1402.

**Pull request closed without merging**
