### PR TITLE
Make sure UI is OK if avatar images are blocked, fixes #822

### LINKED ISSUE #822: Ensure the UI makes sense without Gravatar images
If you block tracking stuff, you may want to block Gravatar images.  We should make sure the UI still makes sense if there are no images. 

This was brought up on Twitter: https://twitter.com/oncletom/status/661587848315949056

### PR DESCRIPTION
**Pull request by hallvors**

### CODE REVIEW

**Comment by magsout** [comment]
ah ah ah ah branch's name is AWESOME :+1:

**Comment by hallvors** [comment]
That Travis failure is weird - git says there's nothing to rebase and these changes are of course utterly minimal.. :-o

**Comment by magsout** [comment]
@hallvors let met restart the build

**Comment by magsout** [comment]
@hallvors ok, travis is happy now

**Comment by miketaylr** [comment]
Let me pass off review to @magsout (trivial changes, and I don't see any complaints here, but he more or less owns CSS).

r? @magsout

**Comment by magsout** [comment]
@miketaylr LGTM

@hallvors :+1:

**Pull request merged**
