### PR TITLE
Fixes #1318 - Add the correct path for requirements.txt

### LINKED ISSUE #1318: Error message has the wrong path for requirements.txt
https://github.com/webcompat/webcompat.com/blob/master/run.py#L21

`requirements.txt` -> `config/requirements.txt`

### PR DESCRIPTION
**Pull request by zoepage**
@karlcow ? :)

### CODE REVIEW

**Comment by karlcow** [comment]
I'm fixing the syntax of the pull request. 
> The title of the PR has a specific format too. see step 9

Step 9 gives the example. (I guess we really need to fix #1134 )
`Fixes #123 - Fixes broken layout on mobile browsers`

**Comment by karlcow** [comment]
@zoepage 

nit: in the future, for asking the review `r? @karlcow` or use the button on the top right of the pull request. Why? Because some people have specific filters to catch some emails in priority ;)

**Comment by zoepage** [comment]
@karlcow you folks are way too smart :)))

**Comment by miketaylr** [comment]
(I have one of these inbox filters ^_^)
screen shot 2017-02-02 at 3 19 57 pm

**Comment by karlcow** [comment]
🤡 
capture d ecran 2017-02-03 a 10 07 22

**Comment by karlcow** [comment]
capture d ecran 2017-02-03 a 10 08 30

**Pull request merged**
