### PR TITLE
Fixed misplaced quote

### PR DESCRIPTION
**Pull request by tagawa**
Let me know if this should go to staging instead.

### CODE REVIEW

**Comment by magsout** [comment]
oups, thanks

**Comment by magsout** [comment]
Hum why travis failed... @miketaylr  ?

**Comment by miketaylr** [comment]
Thanks @tagawa!

@magsout Travis won't be able to run on pull requests sent from forks because we use secure environment variables. See http://docs.travis-ci.com/user/environment-variables/#Secure-Variables.

It's kind of lame, but you can check out the remote branch and run tests locally for non-trivial changes.

**Comment by magsout** [comment]
ahhh , ok thanks

**Pull request merged**
