### PR TITLE
replaced bot_ with oauth

### PR DESCRIPTION
**Pull request by haseebgit**

### CODE REVIEW

**Comment by karlcow** [comment]
@haseebgit Thanks for the contribution. 

A couple of things when contributing.

* Create a branch with the issue number, I guess here you are referring to #754
  So you could have done `git checkout -b 754/1`
* When doing commits, you can add the issue number for example above you could have done `#754 replaced bot_ with oauth`. That will link automatically the issue you are working on. When it's the last commit in a series of commits, you can even do `fix #754 replaced bot_ with oauth`. That will automatically close the issue when merged. 
* When finished your commits, ask for a review with the syntax `r? @miketaylr` or `r? @karlcow` for python 


See https://github.com/webcompat/webcompat.com/blob/master/CONTRIBUTING.md#submission-guidelines for details

Reviewed r+ by me.
@miketaylr be careful of updating travis.

**Comment by miketaylr** [comment]
Cool, I'll create an issue to update Travis environment variables before we deploy this change.

**Comment by miketaylr** [comment]
Oops, missed one in run.py:

```
🐓 python run.py 
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    from webcompat import app
  File "/Users/miket/dev/compat/webcompat.com/webcompat/__init__.py", line 28, in <module>
    import webcompat.views
  File "/Users/miket/dev/compat/webcompat.com/webcompat/views.py", line 29, in <module>
    from issues import report_issue
  File "/Users/miket/dev/compat/webcompat.com/webcompat/issues.py", line 19, in <module>
    BOT_TOKEN = app.config['BOT_OAUTH_TOKEN']
KeyError: 'BOT_OAUTH_TOKEN'
```

**Comment by miketaylr** [comment]
Also here:

```
Traceback (most recent call last):
  File "run.py", line 22, in <module>
    from webcompat import app
  File "/Users/miket/dev/compat/webcompat.com/webcompat/__init__.py", line 28, in <module>
    import webcompat.views
  File "/Users/miket/dev/compat/webcompat.com/webcompat/views.py", line 29, in <module>
    from issues import report_issue
  File "/Users/miket/dev/compat/webcompat.com/webcompat/issues.py", line 19, in <module>
    BOT_TOKEN = app.config['BOT_OAUTH_TOKEN']
KeyError: 'BOT_OAUTH_TOKEN'
```

**Comment by miketaylr** [comment]
I pushed a fix so we aren't stuck here:

https://github.com/webcompat/webcompat.com/commit/37efa684615c4ed8193ff0a0f5df4a47428170ac

**Pull request merged**
