### PR TITLE
Fixes #1167. Show green checkmark for os and browser fields.

### LINKED ISSUE #1167: Green check mark not used on other form fields
When submitting a report on webcompat.com, there is a green check mark when the Site URL field is populated. The other fields do not have this, users could benefit from this consistency and error prevention.

### PR DESCRIPTION
**Pull request by miketaylr**
If they're empty, we just remove it, rather than show a red X.

### CODE REVIEW

**Comment by miketaylr** [comment]
(not ready for review, debugging busted tests)

**Comment by miketaylr** [comment]
⚡️ 🚨 

```
FAIL: main - Reporting (non-auth) - (optional) browser + os validation (701ms)

AssertionError: expected 'wc-Form-group js-Form-group is-validated js-no-error' to not include 'js-no-error'

  at Function.assert.notInclude  <node_modules/intern/node_modules/chai/chai.js:2997:52>

  at CompatCommand.<anonymous>  <tests/functional/reporting-non-auth.js:117:18>

  at runCallback  <node_modules/intern/node_modules/leadfoot/Command.js:509:31>

  at CompatCommand.<anonymous>  <node_modules/intern/node_modules/leadfoot/Command.js:526:11>
...
```

To be continued.

**Comment by miketaylr** [comment]
Sweet, got last failing test to pass. Turns out it was failing because I had a bug. Imagine that!

r? @adamopenweb

**Comment by miketaylr** [comment]
@adamopenweb ping!

**Comment by adamopenweb** [comment]
LGTM. 
r+

**Pull request merged**
