### PR TITLE
Greatest hits radio select

### PR DESCRIPTION
**Pull request by magsout**
I just change the position of the form fields like [screen](http://localhost:5000/) of @calexity  . I have not touched the python or the js

cc @miketaylr

### CODE REVIEW

**Comment by calexity** [comment]
Thank you @magsout!

**Comment by miketaylr** [comment]
So this is failing because we're removing the `#summary` input and tests depend on that. Question: do the multiple choice options replace the summary (i.e., 5 words or less title) entirelly, or do they supplement it? 

My thinking is if we don't make it available it may be limiting. I wonder if we could hide it by default and give the option to write in your own summary?

We also need to come up with the best way to distinguish between small viewports (where we want the "greatest hits" and large viewports without it. It could just be that the radio options are hidden by a media query and we ignore them on the backend if there's no value.

**Comment by magsout** [comment]
@miketaylr the goal of the PR was just beginning the development around the new form and iterate on it to get an idea

**Comment by miketaylr** [comment]
Yeah, understood @magsout. It's good--cause it brings up unsolved/undefined issues. I wonder if we should have a long running branch to hack on this in. Pulling this into master as is is probably a bad idea.

**Comment by magsout** [comment]
must not merge, I should specify the beginning.

**Comment by miketaylr** [comment]
Let me see if I can rebase this branch against master. :boar:

**Comment by miketaylr** [comment]
Ahahah, rebase-fail.

**Comment by miketaylr** [comment]
Sorry to screw this up @magsout. I'm going to nuke this branch, make a new one and cherry-pick 493a4c5ba5a3dc4aee88c51e0f421b3718cd2343.

**Comment by miketaylr** [comment]
Let's continue this discussion in #432. I made a `issues/432/2` branch where we can iterate.

**Pull request closed without merging**
