### PR TITLE
Fixes #3254 - Switch over to JSON config for Intern

### LINKED ISSUE #3254: intern.json configuration file.
In December, we upgraded intern to 4.7.1 in package.json

```
    "intern": "4.7.1",
```

It seems that the way to [configure intern](https://theintern.io/docs.html#Intern/4/docs/docs%2Fconfiguration.md/config-file) now is through an `intern.json` file.

Should we do that?

### PR DESCRIPTION
**Pull request by miketaylr**
OK, ready for review!

### CODE REVIEW

**Comment by miketaylr** [comment]
(just noticed `127.0.0.1 - - [26/Mar/2020 22:57:35] "GET //login HTTP/1.1" 302 -` in the test logs -- something to fix (the double `//`))

**Comment by miketaylr** [comment]
> Mozilla Firefox 67.0.4

Looks like CircleCI isn't using the updated Firefox we tell it to install, so I will investigate how to use a child config for ci-only.

**Comment by karlcow** [comment]
> > Mozilla Firefox 67.0.4
> 
> Looks like CircleCI isn't using the updated Firefox we tell it to install, so I will investigate how to use a child config for ci-only.

https://discuss.circleci.com/t/installing-the-latest-version-of-firefox-in-circleci/1347

> This is how Mozilla (who happen to use CricleCi) do it:
```
- pip install mozdownload mozinstall
- mozdownload --version latest --destination firefox.tar.bz2
- mozinstall firefox.tar.bz2
```

**Comment by karlcow** [comment]
also https://circleci.com/orbs/registry/orb/circleci/circleci-images

**Comment by karlcow** [comment]
oh and https://github.com/mozilla/ci-docker-bases

**Comment by miketaylr** [comment]
Success

Screen Shot 2020-03-27 at 1 45 26 PM

**Comment by miketaylr** [comment]
There's a chance this creates conflicts for https://github.com/webcompat/webcompat.com/pull/3252, so we should land that first (then i'm happy to sort out any conflicts here)

**Comment by miketaylr** [comment]
Thanks @ksy36 -- I'll fix the conflicts before merging.

**Comment by miketaylr** [comment]
OK, rebased and tests are green. 💣

**Pull request merged**
