### PR TITLE
Fixes #1201. Add 'Report Site Issue' header for /issues/new form

### LINKED ISSUE #1201: Add header to /issues/new endpoint
I think something simple like "Report Site Issue".

### PR DESCRIPTION
**Pull request by miketaylr**
r? @magsout 

Whatcha think?

screen shot 2016-10-18 at 5 12 24 pm

screen shot 2016-10-18 at 5 12 02 pm

### CODE REVIEW

**Comment by miketaylr** [comment]
I think @magsout may be busy (no issue ❤️)

r? @karlcow

**Comment by magsout** [comment]
oops .......


r+ @miketaylr 👍

**Comment by miketaylr** [comment]
> oops .......

No worries. Thanks!

**Comment by karlcow** [comment]
r+ @miketaylr … 🐌 oooops ⚡️ @magsout has been fast.

**Pull request merged**
