### PR TITLE
Fixes #1263 - Fixes aria attributes typo in templates

### LINKED ISSUE #1263: [typo] ara-hidden in the topbar template
The topbar html template has two attributes `ara-hidden`. I'm still looking for the parrot in there. 🐦

https://github.com/webcompat/webcompat.com/blob/385103275f1cb86944f63578b21ac3e617cdd643/webcompat/templates/topbar.html#L26-L30

```
ara-hidden="true"
```

### PR DESCRIPTION
**Pull request by MDTsai**
Fix 2 typo from ara-hidden -> aria-hidden. @karlcow , could you please help to check this?

### CODE REVIEW

**Comment by karlcow** [comment]
I modified the title of the PR according to our guidelines. :)

**Comment by karlcow** [comment]
And thanks for the Pull Request.

**Comment by magsout** [comment]
thanks @MDTsai 👍

**Comment by karlcow** [comment]
Perfect!

**Pull request merged**
