### PR TITLE
Require higher image min, fixes #833

### LINKED ISSUE #833: Require a higher version of grunt-contrib-imagemin
To make stuff work better on Windows, we should require at least 0.9.4 where this bug was fixed:
https://github.com/gruntjs/grunt-contrib-imagemin/issues/96

### PR DESCRIPTION
**Pull request by hallvors**

### CODE REVIEW

**Comment by magsout** [comment]
@hallvors  error with travis 

>Running "imagemin:png" (imagemin) task
Fatal error: Cannot read property 'contents' of undefined
The command "grunt" failed and exited with 3 during .

**Comment by hallvors** [comment]
hm..seems that's a buggy version :/ I'm testing 1.0.0 , seems to be OK

**Comment by magsout** [comment]
travis happy now.

**Comment by magsout** [comment]
:+1:

**Pull request merged**
