### PR TITLE
Issue #2733 - Redirect Release Report Site Issue users to a landing page

### PR DESCRIPTION
**Pull request by miketaylr**
This is a hack.

### CODE REVIEW

**Comment by miketaylr** [comment]
Of course the tests would break.

**Comment by magsout** [comment]
@miketaylr the fun part..

**Comment by miketaylr** [comment]
@magsout can you do a sanity check here?

**Comment by miketaylr** [comment]
thanks tom.

**Comment by magsout** [comment]
late but r+ ;)

**Comment by karlcow** [comment]
Thanks @miketaylr

**Pull request merged**
