### PR TITLE
Fixes #718. Make helper methods for login/logout setup/tearDown methods.

### LINKED ISSUE #718: Abstract login/logout junk in setUp/tearDown into helper methods
DRY :+1:

### PR DESCRIPTION
**Pull request by miketaylr**
r? @karlcow

### CODE REVIEW

**Comment by miketaylr** [comment]
You can ignore the first push failure, the fix for the tests landed in between that and the PR.

**Comment by magsout** [comment]
ouch, needs to rebase

**Comment by miketaylr** [comment]
Oops, yes.

**Comment by karlcow** [comment]
Very cool!
:dancers: 
r+

**Comment by miketaylr** [comment]
Merci :rose:

**Pull request merged**
