### PR TITLE
Fixes #2980 - Adding correct border for Invalid form

### LINKED ISSUE #2980: [New UI] Add correct border for invalid form element state
When a user enters an invalid URL the error message "A valid URL is required." appears twice:

Screenshot 2019-10-14 at 18 07 39

Can we also include the 1px `#D81D45` border as per the design:

Screenshot 2019-10-14 at 18 07 06

### PR DESCRIPTION
**Pull request by soniasingla**
Fixes #2980

### CODE REVIEW

**Comment by miketaylr** [comment]
Cool! @soniasingla can you update your commit message to follow the PR guidelines?

https://github.com/webcompat/webcompat.com/blob/master/docs/pr-coding-guidelines.md#add-commit-message-including-issue-number

(Also update the title as well: https://github.com/webcompat/webcompat.com/blob/master/docs/pr-coding-guidelines.md#send-a-pull-request)

**Comment by miketaylr** [comment]
(before we merge, we'll want to remove those 2 commits related to #3038, which I guess if we do a squash merge it will take care of...)

r? @ksy36

**Comment by soniasingla** [comment]
hey @miketaylr , i have already reverted the 2 commits related to bug #3038, can you please check again? :)

**Comment by soniasingla** [comment]
@miketaylr , I removed those commits , ready for another look :)

**Pull request merged**
