### PR TITLE
Fixes #1150. Re-write tests to be less race-y.

### LINKED ISSUE #1150: Fix Comments (auth) tests
Too racy.

### PR DESCRIPTION
**Pull request by miketaylr**
No review request yet, want to see how Travis does.

### CODE REVIEW

**Comment by miketaylr** [comment]
Good gravy, that's a new error:

```
FAIL: main - Comments (auth) - Empty vs non-empty comment button text (open issue) (10776ms)

ScriptTimeout: [POST http://localhost:4444/wd/hub/session/e1d21731-a754-43f6-b331-ef3098edfc72/execute_async / {"script":"return (function (poller, args, timeout, pollInterval, done) {\n\t\t\t\t\t/* jshint evil:true */\n\t\t\t\t\tpoller = new Function(poller);\n\n\t\t\t\t\tvar endTime = Number(new Date()) + timeout;\n\n\t\t\t\t\t(function poll() {\n\t\t\t\t\t\tvar result = poller.apply(this, args);\n\n\t\t\t\t\t\t/*jshint evil:true */\n\t\t\t\t\t\tif (result != null) {\n\t\t\t\t\t\t\tdone(result);\n\t\t\t\t\t\t}\n\t\t\t\t\t\telse if (Number(new Date()) < endTime) {\n\t\t\t\t\t\t\tsetTimeout(poll, pollInterval);\n\t\t\t\t\t\t}\n\t\t\t\t\t\telse {\n\t\t\t\t\t\t\tdone(null);\n\t\t\t\t\t\t}\n\t\t\t\t\t})();\n\t\t\t\t}).apply(this, arguments);","args":["return (function (selector, options) {\n      var $matchingEl = $(selector);\n\n      if ($matchingEl.length === 0) {\n        return null;\n      }\n\n      if ($matchingEl.length > 1) {\n        throw new Error('Multiple elements matched. Make a more precise selector - ' + selector);\n      }\n\n      if (!$matchingEl.is(':visible')) {\n        return null;\n      }\n\n      if ($matchingEl.is(':animated')) {\n        // If the element is animating, try again after a delay. Clicks\n        // do not always register if the element is in the midst of\n        // an animation.\n        return null;\n      }\n\n      return true;\n    }).apply(this, arguments);",[".js-Issue-comment:nth-of-type(3)",{}],10000,67]}] Timed out waiting for async script result after 10002ms

Build info: version: '2.53.1', revision: 'a36b8b1', time: '2016-06-30 17:37:03'

System info: host: 'testing-worker-linux-docker-806fe478-3457-linux-15', ip: '172.17.5.193', os.name: 'Linux', os.arch: 'amd64', os.version: '3.13.0-40-generic', java.version: '1.7.0_76'

Driver info: driver.version: unknown
```

**Comment by miketaylr** [comment]
Sooo, all these failures are just about reading the DOM too quickly before the update has actually applied. 💭

**Comment by miketaylr** [comment]
> Sooo, all these failures are just about reading the DOM too quickly before the update has actually applied.

And no, they don't fail on my machine. >_>

**Comment by karlcow** [comment]
hehe. :) DOM latency? (🔫 before it becomes green)

**Comment by miketaylr** [comment]
OK, cool. Rebasing fixed the specific test failures related to these changes from before.

**Comment by miketaylr** [comment]
I'm gonna fix more tests and use this PR before requesting review.

**Comment by miketaylr** [comment]
Oops.

**Comment by miketaylr** [comment]
Getting closer!

screen shot 2016-08-03 at 10 20 45 pm

Got this one more pesky one that just popped up:

```
FAIL: main - Reporting (non-auth) - Report button shows via GitHub (367ms)

AssertionError: expected '' to include 'Report via'
```

I also realized the pattern I've been using can be made more DRY:

```
.then(FunctionalHelpers.visibleByQSA('.wc-IssueList:nth-of-type(1) .wc-Link'))
.findByCssSelector('.wc-IssueList:nth-of-type(1) .wc-Link').getVisibleText()
```

Maybe something like `findByCssSelectorWhenVisible`.... but I'm happy to do that in a follow-up bug.

**Comment by miketaylr** [comment]
So.... there's not much to review here. I'm tempted to `r=me` and merge, since I'm just fixing test races here/recent perma-test failures. 

But I'll leave it for the evening because there's no rush.

**Comment by miketaylr** [comment]
> I'm tempted to r=me and merge

Nevermind. :)

r? @deepthivenkat

**Comment by miketaylr** [comment]
My general theory as to why things were breaking:

A lot of things we're asking selenium to find are in the DOM, `but display:none`, waiting for data + render() before being visible. selenium is happy to find display:none stuff, so it's like, oh hey i found this thing, let's continue and try to click on this other thing that hasn't rendered yet.

Before I guess we were just lucky, maybe due to bugs in Firefox's webdriver implementation or Firefox itself. But in the past few releases these tests have been super intermittent because of this, I think.

**Comment by deepthivenkat** [comment]
r+

**Comment by miketaylr** [comment]
Thanks!

**Pull request merged**
