### PR TITLE
Issue #652: Account for new label scheme in the API endpoints.

### PR DESCRIPTION
**Pull request by miketaylr**
Existing tests should be OK now.

### CODE REVIEW

**Comment by miketaylr** [comment]
Hmm no. There's more broken stuff here. For some reason an issue with a "status-contactready" label has a status of "New".

**Comment by miketaylr** [comment]
I'll probably just merge this myself so the site isn't broken over the weekend. But I'll give it a few hours. ^_^

**Comment by karlcow** [comment]
This looks good to me. sorry for the delay.

**Comment by miketaylr** [comment]
Thanks Karl!

**Pull request merged**
