### PR TITLE
Fix the dependencies checking. Fix #583

### LINKED ISSUE #583: Check the dependencies before starting the server
Sometimes we change the modules, etc. For example,

```
-WTForms==1.0.5
+WTForms==2.0.2
```

I wonder if we should add a checker before run. Where we would get a pseudo UI like:

```
python run.py

** You need first to update your python/js before starting webcompat.com
@@Instructions to do so@@
```

On the python side, probably something with `pip install --no-install`
or making a diff in between libraries installed and the ones in requirements.txt

For JavaScript, I don't know how it is checked. 
Also when do you need to run again grunt.

### PR DESCRIPTION
**Pull request by karlcow**

### CODE REVIEW

**Comment by karlcow** [comment]
r? @miketaylr 
a second proposal after the discussion in #586

**Comment by miketaylr** [comment]
This looks good, I'm going to pull it in. :smile: 

One small issue is that if we're missing a package we'll hit the `IMPORT_ERROR` at https://github.com/karlcow/webcompat.com/blob/583/2/run.py#L24, and never see `DEPS_NOTFOUND_HELP`. It's not really a blocker, because either way we get an informative message which solves the problem. But maybe something to fix in a follow up commit.

Also it would be cool to replace `name` with the actual package and show the right version in the install command as well. Looks like it wouldn't be too hard.

```
(env)mtaylor at omg in ~/dev/compat/webcompat.com on karlcow-583/2
🐓 python run.py 

The following required versions do not match your locally installed versions:

  (GitHub-Flask 0.3.3 (/Users/mtaylor/dev/compat/webcompat.com/env/lib/python2.7/site-packages), Requirement.parse('GitHub-Flask==0.3.4'))

Install the correct versions using the commands below before continuing:

pip uninstall name
pip install name==1.2.1
```

**Comment by karlcow** [comment]
hehe for the install command. Yeah I thought about it. I was sure it will come up in the discussion. 
Need to find a clever way for doing it, if multiple incompatibilities. :)

**Comment by karlcow** [comment]
Working!

```→ python run.py 

The following required versions do not match your locally installed versions:

  (WTForms 1.0.5 (/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages), Requirement.parse('WTForms==2.0.2'))

Install the correct versions using the commands below before continuing:

pip uninstall name
pip install name==1.2.1

(webcompatcom)18:28:23 ~/code/webcompat.com
→ pip install WTForms==2.0.2
Downloading/unpacking WTForms==2.0.2
  Downloading WTForms-2.0.2-py27-none-any.whl (128kB): 128kB downloaded
Installing collected packages: WTForms
  Found existing installation: WTForms 1.0.5
    Uninstalling WTForms:
      Successfully uninstalled WTForms
Successfully installed WTForms
Cleaning up...
(webcompatcom)18:28:57 ~/code/webcompat.com
→ python run.py 

The following required versions do not match your locally installed versions:

  (Flask-Limiter 0.6.6 (/Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages), Requirement.parse('Flask-Limiter==0.7.4'))

Install the correct versions using the commands below before continuing:

pip uninstall name
pip install name==1.2.1


(webcompatcom)18:30:11 ~/code/webcompat.com
→ pip install Flask-Limiter==0.7.4
Downloading/unpacking Flask-Limiter==0.7.4
  Downloading Flask-Limiter-0.7.4.tar.gz (79kB): 79kB downloaded
  Running setup.py (path:/Users/karl/.virtualenvs/webcompatcom/build/Flask-Limiter/setup.py) egg_info for package Flask-Limiter
    
Downloading/unpacking limits (from Flask-Limiter==0.7.4)
  Downloading limits-1.0.4.tar.gz
  Running setup.py (path:/Users/karl/.virtualenvs/webcompatcom/build/limits/setup.py) egg_info for package limits
    
Requirement already satisfied (use --upgrade to upgrade): Flask>=0.8 in /Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages (from Flask-Limiter==0.7.4)
Requirement already satisfied (use --upgrade to upgrade): six>=1.4.1 in /Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages (from Flask-Limiter==0.7.4)
Requirement already satisfied (use --upgrade to upgrade): Werkzeug>=0.7 in /Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages (from Flask>=0.8->Flask-Limiter==0.7.4)
Requirement already satisfied (use --upgrade to upgrade): Jinja2>=2.4 in /Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages (from Flask>=0.8->Flask-Limiter==0.7.4)
Requirement already satisfied (use --upgrade to upgrade): itsdangerous>=0.21 in /Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages (from Flask>=0.8->Flask-Limiter==0.7.4)
Requirement already satisfied (use --upgrade to upgrade): markupsafe in /Users/karl/.virtualenvs/webcompatcom/lib/python2.7/site-packages (from Jinja2>=2.4->Flask>=0.8->Flask-Limiter==0.7.4)
Installing collected packages: Flask-Limiter, limits
  Found existing installation: Flask-Limiter 0.6.6
    Uninstalling Flask-Limiter:
      Successfully uninstalled Flask-Limiter
  Running setup.py install for Flask-Limiter
    got version from file /Users/karl/.virtualenvs/webcompatcom/build/Flask-Limiter/flask_limiter/_version.py {'version': '0.7.4', 'full': '3efe0f5f8418f9cbc34abec137289f8a0cebcacc'}
    UPDATING build/lib/flask_limiter/version.py
    
  Running setup.py install for limits
    got version from file /Users/karl/.virtualenvs/webcompatcom/build/limits/limits/_version.py {'version': '1.0.4', 'full': '7dd4ff9c1c310d97903435beb241bf8bd516603d'}
    UPDATING build/lib/limits/version.py
    
Successfully installed Flask-Limiter limits
Cleaning up...
```

**Comment by miketaylr** [comment]
\o/

**Pull request merged**
