### PR TITLE
Issue #2681 - Fix to display lists and nested lists on webcompat.com

### PR DESCRIPTION
**Pull request by rafia95**
This PR fixes issue #2681 

## Proposed PR background

Please provide enough information so that others can review your pull request:

I have modified the reset.css. I removed the padding: 0, because it did not leave any space for the list bullets to appear. I removed list-style:none because it sets the style of list to none. Any other style such as 'disc' displays the filled bullets and the issue stated that the bullets needs to be exactly same as on GitHub.

- [ Yes ] I have read the [Pull Request + Code Style Guidelines](https://github.com/webcompat/webcompat.com/blob/master/docs/pr-coding-guidelines.md) thoroughly.

### CODE REVIEW

**Comment by rafia95** [comment]
@magsout Thank you for the review :) 

I will implement the changes you suggested. 

Do I need to use the CSS compiler cssnext after making the changes? 
I noticed that cssnext is deprecated in favor of postcss-preset-env  as mentioned here https://github.com/MoOx/postcss-cssnext

**Comment by magsout** [comment]
@rafia95 

>Do I need to use the CSS compiler cssnext after making the changes?

no need, we handle that when we build or dist the static files.

>I will implement the changes you suggested.

awesome

**Comment by magsout** [comment]
@rafia95 I saw that you have send new commits, do you want a new review from me?

**Comment by rafia95** [comment]
@magsout Yes please. 
Thank you

**Comment by magsout** [comment]
@rafia95 Using the className `issue-comment` is a good thing beacause it targets `<ul><li>` elements in comments. Good point 👍 

But you missed In the main comment of the issue, there is no `issue-comment` so you can keep your css and double it with `issue-details`. 

It's better to put all this css in https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/css/src/issue.css

What do you think?

**Comment by rafia95** [comment]
@magsout sorry for the delay.  I have added the changes you suggested.  Can you review it please? 

The indentation I used was incorrect that's why you will see more than one commit. The last one with the commit message " Added list styling and correct spacing for issue-detail " is the one which passed all the tests and needs the review.

**Comment by magsout** [comment]
@rafia95 looks good 👍  , thanks a lot for you job.

If you could squash your commits  please then we can merge after that.

**Comment by magsout** [comment]
@rafia95 commits lloks good, just one last thing. Could you edit your message within the commit?

capture d ecran 2018-11-21 a 14 02 30

**Comment by karlcow** [comment]
@rafia95 I think you forced pushed too many things. :)
Given that your change is simple. I would recommend to start with another branch.

```bash
git checkout master
git fetch upstream 
git merge upstream/master
git branch -b 2681/2
# Make the file changes
# from https://github.com/webcompat/webcompat.com/pull/2692/commits/dd240bc510ea3f9f53c67a3596d846fb8a0a9e6e#diff-512592b68a9f03f6c7aeef296d15eeaf
git commit -m "#2681 - Adds better CSS handling of lists" webcompat/static/css/src/issue.css
git push origin 2681/2
```

Create a **new** pull request.

Then @magsout and I will approve it. 

I will close this pull request here. Thanks.

**Pull request closed without merging**
