### PR TITLE
Fixes #612 - Remove duplicate issue update after a search.

### LINKED ISSUE #612: Search results are different in webcompat.com and github
1. Go to github and [search `'country: jp' `](https://github.com/webcompat/web-bugs/issues?utf8=%E2%9C%93&q=%27country%3A+jp%27+). Only the list with the occurences appear.
2. Go to webcompat.com and [search `'country: jp' `](https://webcompat.com/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc&q=%27country%3A+jp%27). A long list appears.

I didn't dive deep into it, but my hunch is that it is partly URI encoding.

### PR DESCRIPTION
**Pull request by miketaylr**
OK, I don't really remember why this extra `issues:update` event was in here--probably made sense at one point. :8ball: 

r? @magsout

### CODE REVIEW

**Comment by miketaylr** [comment]
O_o

```
Running "cssnext:dist" (cssnext) task

Warning: Cannot find module 'color-convert' Use --force to continue.

Aborted due to warnings.

The command "grunt" failed and exited with 3 during .
```

**Comment by miketaylr** [comment]
Strange. Grunt runs fine over here.

**Comment by miketaylr** [comment]
```
🐓 npm ls | grep color-convert
│ │ │ │ │ ├── color-convert@0.5.3
│ │ │ │ │ ├── color-convert@0.5.3
│ │ │ │ ├── color-convert@0.5.3
│ │ │ │ ├── color-convert@0.5.3
│ │ │ │ ├── color-convert@0.5.3
│ │ │ │ ├── color-convert@0.5.3
```

I wonder if somehow the Travis cache is wonky.

**Comment by miketaylr** [comment]
I just nuked the cache, let's see how the rebuild goes: https://travis-ci.org/webcompat/webcompat.com/builds/65320308

**Comment by miketaylr** [comment]
@magsout might be busy right now. @karlcow, can you take a look?

**Comment by magsout** [comment]
Oh sorry. I'll take a look tomorrow morning if it's ok for you.

**Comment by miketaylr** [comment]
@magsout yep, no problem! :cool:

**Pull request merged**
