### PR TITLE
Refactoring class for new form report

### PR DESCRIPTION
**Pull request by magsout**
Merged after https://github.com/webcompat/webcompat.com/pull/579

But maybe before, rebase ...

r? @miketaylr

### CODE REVIEW

**Comment by miketaylr** [comment]
Yeah, let me see if I can rebase after pulling in #579. If it doesn't work I'll just cherry pick 069316a.

**Comment by miketaylr** [comment]
Heh, think I just made it messier.

**Comment by miketaylr** [comment]
I'm gonna close this and open a new one when I fix the failing test.

**Comment by magsout** [comment]
My bad. 

I didn't know in this case what was the better way ? Push in your branch or create another branch and Make a PR ?

**Comment by miketaylr** [comment]
I think pushing to the same branch would have been fine. But it's not a big deal--more important is the awesome CSS work you did, not the process of getting it merged. :)

**Comment by magsout** [comment]
>I think pushing to the same branch would have been fine.

ok, good to know

**Pull request closed without merging**
