### PR TITLE
Fixes #1185 - make form.get_metadata

### LINKED ISSUE #1185: Make form.get_metadata string concatenation more idiomatic
See @karlcow's comment at https://github.com/webcompat/webcompat.com/issues/355#issuecomment-250619637

To fix this, update the `get_metadata` method as Karl suggests. When that's done, make sure that the tests still pass! (run `nosetests` from the project root).

### PR DESCRIPTION
**Pull request by sunakshi96**
fix #1185

### CODE REVIEW

**Comment by sunakshi96** [comment]
r? @miketaylr there are two commits, which failed the travis:
The first one, [1f6ef2a](https://github.com/webcompat/webcompat.com/pull/1444/commits/1f6ef2afb3e3f76d747ecfdff3269060f4118b06) generates webcompat/form.py:113:11: E225 missing whitespace around operator
and is fixed in the second [b78699e](https://github.com/webcompat/webcompat.com/pull/1444/commits/b78699e313e1c628b4774296dcdbfedd4572ab69), which generates a log of errors , may be related to python errors.

**Comment by karlcow** [comment]
@sunakshi96 could you squash these 3 commits into one. :)

```
git rebase -i HEAD~3
```

and then 

```
git push -f…
```

**Comment by miketaylr** [comment]
This looks really good! We pass the relevant tests after this change (`test_metadata_wrapping`), so once you squash the 3 commits we're ready to merge. Let me know if I can help!

**Comment by sunakshi96** [comment]
Seems like I re-based twice, and the previous commits are also merged, Need time to correct it !

**Comment by karlcow** [comment]
So I guess you want to close this one in profit of #1460

**Pull request closed without merging**
