### PR TITLE
Fixes #2051: Remove type-stylo from EXTRA_LABELS allow-list

### LINKED ISSUE #2051: Remove type-stylo from EXTRA_LABELS
We no longer need to send it from Firefox:

https://reviewboard.mozilla.org/r/205210/diff/2#index_header

### PR DESCRIPTION
**Pull request by tanay1337**
Fixes https://github.com/webcompat/webcompat.com/issues/2051.

### CODE REVIEW

**Comment by miketaylr** [comment]
Awesome, thank you @tanay1337! 👍 

Would you mind adding a more descriptive commit message like:

`Fix #2051. Remove type-stylo from EXTRA_LABELS allow-list`?

The easiest way to do this is, from your current branch do the following:

`git commit --amend`
(add new commit message, save your editor)
`git push -f`

**Comment by miketaylr** [comment]
Oops, I spoke too soon. :)

We need to fix a test as well:

```
................F........................................................
======================================================================
FAIL: HTML comments need the right values depending on the keys.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/webcompat/webcompat.com/tests/unit/test_form.py", line 144, in test_get_metadata
    self.assertEqual(actual, expected)
AssertionError: u'<!-- @browser: Firefox 59.0 -->\n<!-- @ua_header: Mozilla/5.0...Firefox 59.0 - [truncated]... != u'<!-- @browser: Firefox 59.0 -->\n<!-- @ua_header: Mozilla/5.0...Firefox 59.0 - [truncated]...
  <!-- @browser: Firefox 59.0 -->
  <!-- @ua_header: Mozilla/5.0...Firefox 59.0 -->
  <!-- @reported_with: desktop-reporter -->
- <!-- @extra_labels: type-webrender-enabled -->
+ <!-- @extra_labels: type-stylo, type-webrender-enabled -->
?                    ++++++++++++
```

Let me explain what needs to change in the next comment, if you want to tackle it. :)

**Comment by miketaylr** [comment]
https://github.com/webcompat/webcompat.com/blob/4e9568c3591626007b369a64bbea4d680eea7d1a/tests/unit/test_form.py#L137

We need to remove `type-stylo` there, as well as the next line:

https://github.com/webcompat/webcompat.com/blob/4e9568c3591626007b369a64bbea4d680eea7d1a/tests/unit/test_form.py#L143

The end of that string looks like:

`<!-- @extra_labels: type-stylo, type-webrender-enabled -->\n`

It should be 
`<!-- @extra_labels: type-webrender-enabled -->\n` instead.

For those changes, a commit message like `Issue #2051. Update tests` (or similar) would be good.

**Comment by karlcow** [comment]
Opened a followup issue for the test dependency on the config. #2053

**Comment by karlcow** [comment]
To make it clearer, the suggestion by @miketaylr still needs to be done. The followup issue is to avoid the same thing in the future. :)

**Comment by miketaylr** [comment]
@tanay1337 do you need any help making the suggested changes? I'm happy to pitch in (or be patient. :))

**Comment by tanay1337** [comment]
@miketaylr It should be fine, thanks though! I will work on it in the weekend.

**Comment by miketaylr** [comment]
> @miketaylr It should be fine, thanks though! I will work on it in the weekend.

Cool, thanks!

**Comment by miketaylr** [comment]
@tanay1337 still interested in working on this issue?

**Comment by miketaylr** [comment]
I'm gonna go ahead and close this PR due to inactivity, but if/when you get time to work on this again, we can re-open!

**Pull request closed without merging**
