### PR TITLE
Fixes #1069 - update CONTRIBUTING.md to make ISSUES_REPO_URI point to …

### LINKED ISSUE #1069: Update contributing.md to add webcompat-tests repository to ISSUES_REPO_URI for running functional tests
This should be possible only if the person is a member of webcompat organization.

### PR DESCRIPTION
**Pull request by deepthivenkat**
…webcompat/webcompat-tests/issues for functional testing

r? @miketaylr @karlcow

### CODE REVIEW

**Comment by deepthivenkat** [comment]
#1076

**Comment by miketaylr** [comment]
nit: Can we fix the typo in the commit message? COTRIBUTING -> CONTRIBUTING?

**Comment by miketaylr** [comment]
Other than that, looks fine to me.

**Comment by deepthivenkat** [comment]
:+1: done!

**Comment by miketaylr** [comment]
Thanks!

**Pull request merged**
