### PR TITLE
fixes #2090 #2158 #2076 - added sticky position to the right side menu on issue, fixed position of label editor

### LINKED ISSUE #2076: Label /widget editor icon moves when opening
STR:

1. go to https://staging.webcompat.com/issues/1368
2. login
3. click on the label or milestone editor to open it
4. click in the same spot to close it

depending on where you were for 3, 4 is not possible because it shifts location. We should make sure that doesn't happen.

jumping-button

### LINKED ISSUE #2090: [design] right side menu on issue doesn't stick
1. Go to https://staging.webcompat.com/issues/1368
2. Scroll a bit. The right side context is going away.

capture d ecran 2018-02-16 a 08 48 47

This is a regression. We had won this feature in the past, to keep the context around on desktop so it's faster to change labels and status.

capture d ecran 2018-02-16 a 08 53 12

### LINKED ISSUE #2158: Menu with all available labels/status is displayed truncated on Firefox Mobile
URL: https://staging.webcompat.com/issues/1378
Browser / Version: Firefox Nightly Mobile 60.0a1 (2018-02-18)
Operating System: Google Pixel (Android 8.0.0) - 1080 x 1920 pixels (~441 ppi pixel density)

**Prerequisites:**
1. Github account available and signed in.

**Steps to Reproduce:**
1. Navigate to https://staging.webcompat.com/issues/1378
2. Scroll down the page to "Labels" and "Status" section.
3. Tap the "Edit" (labels/status) button. 

**Expected Behavior:**
Menu with all available labels/status is fully visible.

**Actual Behavior:**
Menu with all available labels/status is displayed truncated on the left side.

**Note**
1. Affected area:
```html
<div class="label-editor js-CategoryEditor">
	<div class="label-editor-header">
		<input class="form-field text-field" placeholder="Filter labels">
			<button class="nav-button js-CategoryEditor-close" tabindex="0">
				<svg class="nav-text icon nav-icon" viewBox="0 0 30 30" role="presentation">
					<title>Save &amp; close</title>
					<use href="#svg-sliders">Save &amp; close</use>
				</svg>
			</button>
		</div>
		<div class="label-editor-list" tabindex="-1">
			<label class="label-editor-list-item label-browser-android" tabindex="0">
				<input class="label-editor-list-item-checkbox" name="android" data-color="f7c6c7" data-remotename="browser-android" tabindex="-1" type="checkbox">
					<span class="small">android</span>
				</label>
				<label class="label-editor-list-item label-browser-chrome" tabindex="0">
					<input class="label-editor-list-item-checkbox" name="chrome" data-color="006b75" data-remotename="browser-chrome" tabindex="-1" type="checkbox">
						<span class="small">chrome</span>
					</label>
<!---not needed-->
	</div>
<div>
```

Watchers:
@softvision-sergiulogigan
@softvision-oana-arbuzov

screenshot-1519049391060

### PR DESCRIPTION
**Pull request by magsout**
r @zoepage 
  @karlcow   ?

fixes #2090 

edit: This PR corrects more issue than originally

fixes #2090 
fixes #2158
fixes #2076

### CODE REVIEW

**Comment by magsout** [comment]
@zoepage ah yes... I'll add a mq for height, thanks ;)

**Comment by magsout** [comment]
For this issue we need a little javascript to calculate the height of the aside to add or not sticky

**Comment by karlcow** [comment]
the aside content could be scrollable too.

**Comment by zoepage** [comment]
What if we make the label box container sticky & the inner scrollable from a specific height?

**Comment by magsout** [comment]
@zoepage sounds a good idea.

**Comment by magsout** [comment]
I tried something, but it doesn't work, so I get stuck. I don't know how to handle this idea..

**Comment by zoepage** [comment]
Where did you get stuck @magsout ?
Maybe rubber ducking or a chat could help? :)

**Comment by magsout** [comment]
@zoepage if am I right, we let the position sticky all the time for the aside element but we add a scroll bar in the aside from a specific height. 

I get stuck about this scrollbar. Adding a scrollbar without a max-height or a height doesn't works, right? We can't add `height :100%` because we don't get any context around the aside. So how we can add this scrollbar?

**Comment by Regaddi** [comment]
Just an idea: maybe it's safe to use some combination of [calc()](https://developer.mozilla.org/de/docs/Web/CSS/calc) and [vh](https://caniuse.com/#feat=viewport-units)?

**Comment by magsout** [comment]
@Regaddi I like your approach. Let me try something.

Thanks ;)

**Comment by magsout** [comment]
@Regaddi your idea is smart so I implemented it and it seems to work like a charm, thanks a lot

@zoepage what do you think about my last commit? maybe we can manage value for the MQ.

**Comment by zoepage** [comment]
Wooho! 
We are totally getting closer :D :tada:



We just need to take care of the overlay:
screen shot 2018-03-13 at 11 02 33 am

**Comment by magsout** [comment]
@zoepage cool. next step. thanks for the review.

**Comment by magsout** [comment]
r @zoepage  ?

**Comment by magsout** [comment]
@zoepage I pushed another commit fixing this issue https://github.com/webcompat/webcompat.com/issues/2076

It's a different issue, but I was fixing the label-editor so I tell myself, I can fixe this issue too

**Comment by zoepage** [comment]
Uhhhhhhh, I'll check later :)))

**Comment by zoepage** [comment]
Gosh, I LOVE this! :D
You rock @magsout!



Just one small thing... on mobile we still have the jump of the icon. Otherwise LGTM!

**Comment by zoepage** [comment]
I was a bit too quick 🤔
Does clicking the icon work for you in Chrome?

**Comment by karlcow** [comment]
@magsout @zoepage which issue should I check for the review requested by @magsout.
I tried this branch but with no luck.

```
→ git status
On branch issues/2090
Your branch is ahead of 'webcompat/issues/2090' by 106 commits.
  (use "git push" to publish your local commits)
nothing to commit, working directory clean
```

Tried the localhost, and the issue doesn't seem to be fixed. I probably do something incorrect.

**Comment by magsout** [comment]
@karlcow it's weird, it's a good branch that you jump to. do you rebuild the assets?

**Comment by karlcow** [comment]
capture d ecran 2018-03-15 a 15 16 34

Ah wait I probably misunderstood what you were trying to do. :)

This is working for a `min-height > 550px` but as soon it is under it reverts to the previous behavior.

Ah understood.

```css
@media all and (min-width: 893px) and (min-height: 550px) {
  .label-box {
    position: sticky;
    top: 50px;
    max-height: calc(100vh - 44px - 30px);
    overflow-y: auto;
  }
}
```

Any reasons for keeping the `550px`?

**Comment by karlcow** [comment]
Apart of that +1 it addresses the comment I had in #2090 and my suggestion in https://github.com/webcompat/webcompat.com/pull/2133#issuecomment-367506232

> the aside content could be scrollable too.

That's exactly what I meant. Thanks @zoepage, @Regaddi, @magsout . Awesome work.

**Comment by magsout** [comment]
@karlcow the content is scrollable if the height of aside is highter than the height of visible screen try with the issue 1367.

**Comment by karlcow** [comment]
@magsout Yes understood that :) 
But it's not what I'm saying, make your browser `window.innerHeight` at `510px` for example.

**Comment by magsout** [comment]
@karlcow you're right, the min-height is not useful, we can remove it, thanks for your review.

**Comment by magsout** [comment]
on more time :D r @zoepage  ?

**Comment by zoepage** [comment]
@magsout All good things come to an end :D GREAT WORK! <3

**Comment by magsout** [comment]
@zoepage thanks ;)

ah ah I love this TV-show

**Comment by zoepage** [comment]
good to know for future gifs :D 👯

**Pull request merged**
