### PR TITLE
Fixes #813. Replace JSHint with ESLint

### LINKED ISSUE #813: JS style guide enforcement
We don't really have a style guide, and writing one seems like a lot of work.

It would be cool to hook up some tooling to do the checks for us:

http://eslint.org/docs/rules/ (eslint can also replace jshint)

OR

http://jscs.info/ (to be used in conjunction with jshint).

Mainly I'd like us to have consistent use of quoting and whitespace, and not have to think about these boring things during code review.

Thoughts? @magsout @hallvors

### PR DESCRIPTION
**Pull request by miketaylr**
This add the equivalent linting rules we had before plus a handful of style checks, mostly around whitespace.

Running `grunt` will still run the eslint task, or you can run `grunt eslint` for only that.

One cool thing is you can tell it to "fix" the errors for you (for certain simple ones, like whitespace or indentation):

`eslint webcompat/static/js/lib/user-activity.js --fix`, for example.

r? @magsout

### CODE REVIEW

**Comment by magsout** [comment]
cooool. Good job @miketaylr 

>One cool thing is you can tell it to "fix" the errors for you (for certain simple ones, like whitespace or indentation):

I don't like a linter modifies files, I think it's better to display an error or warning.

**Comment by miketaylr** [comment]
> I don't like a linter modifies files, I think it's better to display an error or warning.

That's fair. By default it only displays errors. But if you have 10,000,000,000 whitespace errors, you have the option of manually using that `--fix` option. :smile:

**Comment by miketaylr** [comment]
OK cool, tests are passing (we had some weird timeout thing). Let's pull it in.

**Comment by miketaylr** [comment]
Ooops haha.

**Comment by magsout** [comment]
>That's fair. By default it only displays errors. But if you have 10,000,000,000 whitespace errors, you have the option of manually using that `--fix` option. :smile: 

Sounds good. Good job 👍

**Pull request merged**
