### PR TITLE
Revert "Fixes #2873 - Add AB testing plumbing"

### LINKED ISSUE #2873: Add support for AB testing in webcompat.com
As part of our (Open Innovation) experiments to test some UX changes in the reporting flow, it would be useful to be able to use some sort of AB testing capabilities in webcompat.com.

### PR DESCRIPTION
**Pull request by karlcow**
Reverts webcompat/webcompat.com#2874

### CODE REVIEW

**Comment by karlcow** [comment]
Let me revert master to its state before AB. No need to deploy AB testing in master without first having a way to really test it.

**Comment by miketaylr** [comment]
So is the plan to re-merge once we have another UI we can test on staging?

Once that's on staging, we can change `extensions.webcompat-reporter.newIssueEndpoint` to https://staging.webcompat.com and go from there.

**Comment by miketaylr** [comment]
(@karlcow i'll let you merge this one)

**Comment by karlcow** [comment]
> So is the plan to re-merge once we have another UI we can test on staging?

yes and something that will work with on HTTP post.

**Pull request merged**
