### PR TITLE
Issue #2809 - Add fonts to our server

### PR DESCRIPTION
**Pull request by marimeireles**
Hey @karlcow can you please review my code and if it's everything alright send these changes to Staging?

What I'm trying to do here is to measure how much we'd improve our font loading fetching from the server comparing to fetching from Google. 

(I already have the tests for fetching on Google.)

### CODE REVIEW

**Comment by marimeireles** [comment]
Our linter tool has a bug:

screen shot 2019-02-27 at 14 25 59

If I add a space it tells me to remove the space if I remove the space it tells me to add a space :p
There is an issue filled here https://github.com/stylelint/stylelint/issues/3270, but I don't think it's fixed.

I've fixed it adding an ugly css.

**Comment by karlcow** [comment]
So I'm not merging (for now) just pushing the branch to stagiing.

**Comment by karlcow** [comment]
@marimeireles this branch is currently deployed on staging.

**Comment by marimeireles** [comment]
Thanks @karlcow.

The way this is working now is not worth it. We spend a really long time stuck waiting for other process to happening. But one thing surprised me: we're able to download the fonts approximately as fast as we used to download them from Chrome.

screen shot 2019-02-28 at 16 12 47

I'd like to test how much we can improve by pushing the fonts. I researched all around the web and I don't think there is a way to do it other than UA sniffing what's the browser the person is using. What do you think @miketaylr? Can we do that? If we don't do it than I don't think we should serve our own fonts because they represent a significantly drop in performance. We could use the `link=preload` thing but it only works for newer versions of Chrome, so it's not worth it either.

**Comment by marimeireles** [comment]
ping @miketaylr

**Comment by marimeireles** [comment]
I'm going to undo the changes I did here. It's not worth it to host our fonts and I think UA sniffing is something we shouldn't use.
We can try to use this solution once [preload](https://bugzilla.mozilla.org/show_bug.cgi?id=1222633) is added to FIrefox. But I don't think it's worth it otherwise.

**Comment by marimeireles** [comment]
@karlcow Can you please undo the changes this PR makes?
(Once you're back from PTO!)

**Comment by karlcow** [comment]
@marimeireles not that the branch has been approved and not merged. So we can just safely close it. and redeploy staging.

Thanks a lot for exploring this path. It was cool to be working with you in the context of this project.

**Pull request closed without merging**
