### PR TITLE
Fixes #1609 - remove logic for validating problem type from description…

### LINKED ISSUE #1609: add functional test for bug form Description field
dependency on #1547 

a test that validates expected required field error message display for the new Description text input should be added (reporting-non-auth.js). this was not included in the original issue because of challenges getting the correct selector (for the error message) to work on travis.

complications arose from the current Description input event listeners (which trigger 2 error messages currently)

ref:
* https://stackoverflow.com/questions/27609327/intern-functional-test-iterating-on-set-of-items
~~https://stackoverflow.com/questions/32272598/intern-loop-on-promise-array-leadfoot-element~~

~~https://github.com/theintern/leadfoot/issues~~
~~(see if there is any documented occurrence of selector patterns that would fail on travis or give problems)~~

### PR DESCRIPTION
**Pull request by cch5ng**
… field interaction

tests: #1609; remove test for problem type validation; add test for description validation

### CODE REVIEW

**Comment by cch5ng** [comment]
@miketaylr R?

**Comment by miketaylr** [comment]
> @miketaylr R?

oops. my fail filters are looking for "r? @miketaylr" -- sorry i missed this!

**Comment by cch5ng** [comment]
@miketaylr oh, sorry. didn't realize that was case sensitive but I'll remember for the future. thanks!

**Comment by miketaylr** [comment]
Cool, thanks @cch5ng!

**Pull request merged**
