### PR TITLE
Fixes #749. Add a "My Activity" page.

### LINKED ISSUE #749: Make a "My Activity" page
From #442.

This issue is more specific. We want a page that shows:

1) Bugs that @mention you
2) Bugs that you reported.

### PR DESCRIPTION
**Pull request by miketaylr**
We haven't heard feedback yet on design, but let's try to land this anyways. Design can be incrementally improved.

(I also probably need to rebase, but uh... let's see if there's any conflicts first).

@magsout who do you think we should ping for review? Eachother? ^_^

### CODE REVIEW

**Comment by miketaylr** [comment]
> This branch has conflicts that must be resolved

:hankey: 

I'll do that, and then probably squash/rebase a bunch of the (messy) history. Let's hold off on review until then.

**Comment by magsout** [comment]
@miketaylr 

>@magsout who do you think we should ping for review? Eachother? ^_^

hum, maybe @karlcow for python, @hallvors for JS

and sent to staging for the pre-design ?

**Comment by miketaylr** [comment]
Sounds good. Working on merge right now.

**Comment by miketaylr** [comment]
OK, I rebased and merge fixed and squashed and did a bunch of other junk. I pushed it to another branch (issues/749/2), so let's close here and I'll open a new PR.

**Pull request closed without merging**
