### PR TITLE
Issue #624: Add webapp manifest

### PR DESCRIPTION
**Pull request by miketaylr**
So uh, I don't know who supports this yet. But @marcoscaceres asked for some live examples to test out his Gecko parser.

r? @magsout

### CODE REVIEW

**Comment by miketaylr** [comment]
I suppose I need to configure nginx to serve `.webmanifest` files as `application/json` too.

**Comment by magsout** [comment]
@miketaylr 
>So uh, I don't know who supports this yet

you're talking about browser ?

**Comment by miketaylr** [comment]
Yeah.

**Comment by magsout** [comment]
http://caniuse.com/#search=manifest

**Comment by magsout** [comment]
Maybe we can add css and js and font ?

**Comment by miketaylr** [comment]
Ah, oops. This is actually a little different than a cache.manifest. The spec is here: https://w3c.github.io/manifest/

(and yes, offline is still a goal ^_^)

**Comment by magsout** [comment]
aaaaahh

**Comment by magsout** [comment]
LGTM even if I can't test ;p

**Comment by miketaylr** [comment]
Thanks! I guess Marcos will be testing for us. :smile:

**Comment by marcoscaceres** [comment]
> http://caniuse.com/#search=manifest
that's a different thing, btw ^_^

**Comment by marcoscaceres** [comment]
Ah, should read the whole thread before commenting... :sweat_smile:

**Pull request merged**
