### PR TITLE
Issue #2320 - Adds wc-Comment-content-nsfw to new CSS

### PR DESCRIPTION
**Pull request by marimeireles**
This PR fixes issue #2320

It's necessary to add a `nsfw` label to the github repository in order for these changes to work.

r? @magsout 

---

- [x] I have read the [Pull Request + Code Style Guidelines](https://github.com/webcompat/webcompat.com/blob/master/docs/pr-coding-guidelines.md) thoroughly.

### CODE REVIEW

**Comment by magsout** [comment]
@marimeireles thanks. The logic of nsfw is back.

In the issue #2320 there are two purposes.
1) Logic back
2) Consistency in naming

You did the first step, but no the second step.  

So you have to update the className in the css file and the js file to be consistency with the classNames

**Comment by miketaylr** [comment]
> consistency with the classNames

Is the style we should be using documented somewhere @magsout? I'm not sure I even know. :))

**Comment by magsout** [comment]
>Is the style we should be using documented somewhere @magsout? I'm not sure I even know. :))

Good question @miketaylr and I would say, no.

It's just about feeling wanted kind of component you're coding and/or where you're adding properties.

It's very subjective so I think it would be nice to document that.

For this issue, I would say something like :  `.issue-details-nsfw` ?

**Comment by marimeireles** [comment]
@miketaylr Thanks for the question.
@magsout Sorry for that. When you said I should adapt it to css atomic I read a little bit about it on the internet and I thought I was fine. 

I followed your recommendation in this new pr.

**Comment by magsout** [comment]
@marimeireles 

>@magsout Sorry for that. When you said I should adapt it to css atomic I read a little bit about it on the internet and I thought I was fine.

My bad,  I should have been more specific.

Perfect for the css part 👍 good job.

Just one thing and after that i think we can merge, we need to update className in JS files : 
https://github.com/webcompat/webcompat.com/blob/cc26a9153cbd3d0c600cc7278bea027850b72645/webcompat/static/js/lib/issues.js#L176
https://github.com/webcompat/webcompat.com/blob/173d09289eac42c6aa2b679850204663dd3b2f02/webcompat/static/js/lib/issues.js#L334
https://github.com/webcompat/webcompat.com/blob/173d09289eac42c6aa2b679850204663dd3b2f02/webcompat/static/js/lib/issues.js#L515

then same thing for all className `wc-Comment-content-nsfw"` in the functional test 

https://github.com/webcompat/webcompat.com/blob/cfebc90608bbb4892ee1a257c7101561caf79e8d/tests/functional/issues-non-auth.js#L85
https://github.com/webcompat/webcompat.com/blob/cfebc90608bbb4892ee1a257c7101561caf79e8d/tests/functional/issues-non-auth.js#L97
https://github.com/webcompat/webcompat.com/blob/cfebc90608bbb4892ee1a257c7101561caf79e8d/tests/functional/issues-non-auth.js#L98
https://github.com/webcompat/webcompat.com/blob/cfebc90608bbb4892ee1a257c7101561caf79e8d/tests/functional/issues-non-auth.js#L105
https://github.com/webcompat/webcompat.com/blob/cfebc90608bbb4892ee1a257c7101561caf79e8d/tests/functional/issues-non-auth.js#L106
https://github.com/webcompat/webcompat.com/blob/cfebc90608bbb4892ee1a257c7101561caf79e8d/tests/functional/issues-non-auth.js#L113
https://github.com/webcompat/webcompat.com/blob/cfebc90608bbb4892ee1a257c7101561caf79e8d/tests/functional/issues-non-auth.js#L114

**Comment by marimeireles** [comment]
Sorry for taking so long and forgetting to change on the other files! :(

**Comment by magsout** [comment]
@marimeireles awesome. Good job, and thanks a lot.

capture d ecran 2018-10-16 a 16 15 40

**Pull request merged**
