### PR TITLE
fixes #2244 - fixed position of label box on small screen

### LINKED ISSUE #2244: Label Box header in /issues on mobile
The header of the label box needs to be visible above the issue on mobile.

Expected:
https://webcompat.com/issues/16036

Actual:
Header stays visible above the label box that jumps below the issue content and comments.

@magsout would this be something you'd be interested in working on?

### PR DESCRIPTION
**Pull request by magsout**
r @zoepage ?

### CODE REVIEW

**Comment by Regaddi** [comment]
This might collide with https://github.com/webcompat/webcompat.com/issues/2247

**Comment by zoepage** [comment]
> This might collide with #2247
Yeah, I think so too. 

@magsout we changed a few things at #2247 to clean up the grid a bit. Is it ok, if we wait for this to land and then re-check your PR? <3

**Comment by magsout** [comment]
@zoepage I'll try to resolve conflicts asap

**Comment by magsout** [comment]
@zoepage done

**Comment by zoepage** [comment]
LGTM!

**Pull request merged**
