### PR TITLE
Issue Improvements - Dynamic Information about reporter

### PR DESCRIPTION
**Pull request by magsout**
@miketaylr we need to add dynamic information about reporter

### CODE REVIEW

**Comment by magsout** [comment]
Ouch, I need to rebase

**Comment by miketaylr** [comment]
^_^

**Comment by miketaylr** [comment]
> @miketaylr we need to add dynamic information about reporter

Where at? Just the reporters name?

(also these test failures look weird--I'll run them locally at some point today/tomorrow)

**Comment by magsout** [comment]
Hum need to push some code

**Comment by magsout** [comment]
>Where at? Just the reporters name?

@miketaylr : I add `@todo something`  where you need to add information

**Comment by magsout** [comment]
Hum, I don't know why travis failed. any idea @miketaylr  ?

**Comment by karlcow** [comment]
I'm not sure I understand the issue and where it's happening. Is it visual or something else?

**Comment by magsout** [comment]
@karlcow issue page https://github.com/webcompat/webcompat.com/issues/617

**Comment by magsout** [comment]
So There are only two test failures

```
× firefox 34.0 on LINUX - issues - issue comments load

AssertionError: Commenter name displayed.: expected '@todo autor' to equal 'miketaylr'
```

it's ok, when you add @miketaylr the reel author, test will be ok

But for this, I don"t know why.
```
× firefox 34.0 on LINUX - issues - posting an empty comment fails

AssertionError: Comment was not successfully left.
```

**Comment by miketaylr** [comment]
Oops, missed these emails. Let me take a look @magsout.

**Comment by miketaylr** [comment]
I added the info, but still not sure how that's related to the failing tests. Looking at that now.

Also I needed a container to hold the new template (since we rearranged things a bit) so I made a `.wc-IssueDetail-report`. Feel free to change that to something else @magsout -- just need to change it in the issue.html as well as issues.js.

**Comment by miketaylr** [comment]
OK, there we go. There was a `.js-issue-comment` class that we use to count comment elements. The issue body isn't technically a comment, it just shares some styles so I removed it. That fixed the failures. ^_^

**Comment by magsout** [comment]
Nice 👍

**Comment by magsout** [comment]
What do you think @calexity @karlcow @tagawa  @hallvors ?

**Comment by magsout** [comment]
poke @webcompat/owners

**Comment by tagawa** [comment]
Good idea to highlight the reporter details @magsout - a bit of psychological reward.

**Comment by magsout** [comment]
Quick view:

Before / after

issue

**Comment by karlcow** [comment]
cool. Thanks for the screenshots. 
It gives more balance. Suggestions for the Labels
What if, we just remove the label "Labels" and we put it just above the comment box. 

The reason is that I often need to go up and down when refreshing the state of the bug, and I see people forgetting about changing the state.

**Comment by miketaylr** [comment]
> The reason is that I often need to go up and down when refreshing the state of the bug, and I see people forgetting about changing the state.

Another option is to mimic GitHub and have the labels on the right and have them be "sticky". Scroll this PR/bug up and down, for example.

**Comment by miketaylr** [comment]
@magsout massive improvements. ^_^

**Comment by magsout** [comment]
Good idea @miketaylr . I'm concerned about small device and @karlcow's idea is easier for it.

**Comment by miketaylr** [comment]
@magsout any reason to not pull this in now?

**Comment by magsout** [comment]
About label ? Just wainting about what We have to do..

**Comment by miketaylr** [comment]
It might be good to ship this (if it's in a merge-able state), and then open a bug for label improvements?

**Comment by magsout** [comment]
So GO ;)

**Comment by miketaylr** [comment]
Sweet.

**Comment by miketaylr** [comment]
Just filed #637 to follow up with labels. Will try to deploy later today/tonight!

**Comment by magsout** [comment]
:+1:

**Pull request merged**
