### PR TITLE
Fixes #1763 - Add template watching to Grunt watch task

### LINKED ISSUE #1763: Add template watching to Grunt watch task
something like this would do it:

```
    templates: {
      files: "<%= tmplPath %>/**/*.jst",
      tasks: ["jst"]
    }
```

Bonus points for fixing the script task, it throws an error due to a missing `jshint` var (which we don't use anymore).

### PR DESCRIPTION
**Pull request by Obtin**

### CODE REVIEW

**Comment by zoepage** [comment]
Look good to me and works.
Adding r? @miketaylr as he suggested the change.

**Comment by miketaylr** [comment]
(to fix the commit message, something like this should work, from your branch:)

`git commit --amend`
`(edit the commit message in the editor, and save)`
`git push -f`

**Comment by Obtin** [comment]
https://github.com/webcompat/webcompat.com/pull/2004
r? @miketaylr @zoepage

**Comment by Obtin** [comment]
r ? @miketaylr , i guess the required changes are done

**Comment by miketaylr** [comment]
Awesome, thanks @Obtin!

**Pull request merged**
