### PR TITLE
Added SearchBar to HomePage

### PR DESCRIPTION
**Pull request by magsout**
r? @miketaylr

### CODE REVIEW

**Comment by magsout** [comment]
@miketaylr when we click on button `js-SearchBarOpen`just add `is-active` to `js-SearchBar` and remove it when we click on `js-SearchBarClose`

**Comment by miketaylr** [comment]
@magsout did we accidentally break the `/issues` top bar?

**Comment by magsout** [comment]
ooops :-1:

**Comment by magsout** [comment]
arg sorry @miketaylr

**Comment by magsout** [comment]
forced update ... :sob:

**Comment by magsout** [comment]
:dancers:

**Comment by magsout** [comment]
hbgtv4y

**Comment by miketaylr** [comment]
This is awesome. I just need to figure out why only the `?q` param appears on the `/issues` page once you do a search--but I'll open a new bug for that.

**Pull request merged**
