### PR TITLE
Fixes #3351 - Moves the analytics comment

### LINKED ISSUE #3351: "End Google Analytics" comment in wrong place
This is a good first bug, because it does not affect functionality at all - just view source.

```
<!-- Google Analytics -->
<script src="/dist/ga.js"></script>
<script async src='https://www.google-analytics.com/analytics.js'></script>
<script nomodule src="/dist/vendor.es5.js?37c3f356637c7f63a991b6bddeefb3fe"></script>
<script nomodule src="/dist/webcompat.es5.js?5270a9fe17db823cadab89672c2d3dfa"></script>
<!-- End Google Analytics -->
<script type="module" src="/dist/vendor.js?ff6d7fd6b7a5a7bf64b9d7b6c540af79"></script>
<script type="module" src="/dist/webcompat.js?d633938f16ba8e2f9d85e2de85054f4b"></script>
```

To fix this, the comment should be moved up 2 lines just after the Google Analytics script:

https://github.com/webcompat/webcompat.com/blob/6478d111db4dfd8d66202447ff21774fcf922a0d/webcompat/templates/layout.html#L26

(an alternate fix would be to delete the comment in addition to `<!-- Google Analytics -->` lol)

### PR DESCRIPTION
**Pull request by apsychogirl**
Fixes - #3351

### CODE REVIEW

**Comment by karlcow** [comment]
@apsychogirl you might want to adjust the PR, to just modify what needs to be modified. I have the feeling you got a formater which changed everything in the initial code.

**Comment by ksy36** [comment]
Thanks for looking into this @apsychogirl . Looks good to me, though you might want to check Karl's comment

**Comment by karlcow** [comment]
@apsychogirl yes! that's it. one last thing.

Could you do 

```
git rebase -i HEAD~3
```

1. replace `pick` by `f` in front of the last two lines 
2. changes the message of the first line by `issue #3351 - moves the Google Analytics comment` after the pick and the sha1

Then 

```
git push -f
```

Thanks.

**Comment by apsychogirl** [comment]
> @apsychogirl yes! that's it. one last thing.
> 
> Could you do
> 
> ```
> git rebase -i HEAD~3
> ```
> 
>     1. replace `pick` by `f` in front of the last two lines
> 
>     2. changes the message of the first line by `issue #3351 - moves the Google Analytics comment` after the pick and the sha1
> 
> 
> Then
> 
> ```
> git push -f origin 3351/1
> ```
> 
> Thanks.

image

Just a doubt, if I change the message of the first line, won't that merge the commit with issue #3354 ?

**Comment by karlcow** [comment]
hmmm not the right git rebase. Yup DO NOT DO that :)

**Comment by karlcow** [comment]
@apsychogirl could you tell me what 

```
git log --oneline
``` 

returns for the first 5 lines.

**Comment by apsychogirl** [comment]
```
dfc27405 (HEAD -> 3351/1) Removed the google analytics comment
b9ba8a96 Issue #3354 - fixes syntax
3f8d764d Issue #3354 - complete the template tests
5c1d1a8a issue #3354 - convert fully to pytest
5e5b7d6b Issue #3354 - Handles FileNotFoundError for assets

**Comment by karlcow** [comment]
@apsychogirl I'm confused.

```
dfc27405 (HEAD -> 3351/1) Removed the google analytics comment
```

but your latest commit says:

```
2dcdf7a Fixes #3351 - moves the Google Analytics comment 
```

oh wait… you are not committing into your branch.

Capture d’écran 2020-06-24 à 12 50 13

**Comment by karlcow** [comment]
ah no that's not it. Sorry about that. 
How come the local log doesn't reflect the latest two commits?

**Comment by karlcow** [comment]
@apsychogirl you should see these 3 commits 
https://github.com/apsychogirl/webcompat.com/commits/3351/1

**Comment by karlcow** [comment]
@apsychogirl do you want to try to fix it? or do you want me to fix your pull request?

**Comment by apsychogirl** [comment]
I'll try to find the error and will let you know

**Comment by apsychogirl** [comment]
@karlcow , does this seems fine?

**Comment by karlcow** [comment]
Thanks a lot @apsychogirl 
congratulations on making the PR square!

**Pull request merged**
