### PR TITLE
Fixes #511- make pagination buttons into links and update hrefs accordingly

### LINKED ISSUE #511: Next/Prev Links in issues list are not links
The next/prev buttons are not real links.

``` html
<div class="r-Grid-cell r-all--1of2 wc-Pagination js-pagination-controls">
            <button class="r-ResetButton wc-Pagination-link js-pagination-previous">previous</button>
            <button class="r-ResetButton wc-Pagination-link js-pagination-next">next</button>
          </div>
```

We can't navigate them.

Suggestion: Replace these by populated `a href`

### PR DESCRIPTION
**Pull request by miketaylr**
r? @magsout

### CODE REVIEW

**Comment by magsout** [comment]
ooooops

**Comment by magsout** [comment]
some bug about history

->http://localhost:5000/
-> Click `All issues`
-> Click `next`
-> Click `Site contacted`

`Sorry, no results were found.`

You keep `page` init to `2` : http://localhost:5000/issues?page=2&per_page=50&state=open&stage=sitewait

I think if we click on any state, we have to reset `page`

**Comment by miketaylr** [comment]
Ah. Yeah. That's a bug. ^_^

**Comment by miketaylr** [comment]
It's a bug unrelated to this PR, but I'll make the fix in here and we can pull them both in at the same time. Thanks for catching that @magsout.

**Comment by miketaylr** [comment]
OK, should be good to merge. :confetti_ball:

**Comment by magsout** [comment]
:+1:

**Pull request merged**
