### PR TITLE
Fixes #1872. Update dev-env-setup.md.

### LINKED ISSUE #1872: Review dev-env-setup.md
Noticed a few things that are out of date.

### PR DESCRIPTION
**Pull request by miketaylr**
r? @zoepage

### CODE REVIEW

**Comment by zoepage** [comment]
@miketaylr just one question. Otherwise :+1: .

Thank you :)

**Comment by miketaylr** [comment]
> @miketaylr just one question. Otherwise 👍 .

I think the question maybe got swallowed!

@zoepage if not, go ahead and merge so the docs are in better shape for your sprint.

**Comment by zoepage** [comment]
@miketaylr 

> I was just thinking, this is accurate if you first fork the repository, but might get confused as a first time contributor.
Shall we add this step here?

**Comment by zoepage** [comment]
Gonna merge this and if you feel like we need it, we can create a follow up issue.

**Pull request merged**
