### PR TITLE
Fixes #3685 - Automatically add labels for issues reopened after ML triage

### LINKED ISSUE #3685: Automatically add labels for issues reopened after ML triage
For easier tracking of false positives of `needsdiagnosis` model, let's add the following labels temporarily: 

- `bugbug-reopened` label for issues that have been reopened after ML bot closed them; 
- `bugbug-valid` to issues that have `bugbug-reopened` label AND has been moved to `needsdiagnosis` or `moved` milestone;

### PR DESCRIPTION
**Pull request by ksy36**
This will help with analytics to determine the false-positive rate of the model using our Elastic search data: how many issues ML bot closed per week/ how many were reopened / how many of those ended up being "valid" ( i.e. milestoned to needsdiagnosis/moved).
    

- `bugbug-reopened` label for issues that have been reopened after ML bot closed them;
- `bugbug-valid` to issues that have `bugbug-reopened label` AND has been moved to `needsdiagnosis` or `moved` milestone;

### CODE REVIEW

**Comment by ksy36** [comment]
The build tests are failing with these errors:

```python
  if request is None:
>           builder = EnvironBuilder(*args, **kwargs)
E           TypeError: __init__() got an unexpected keyword argument 'as_tuple'

env/lib/python3.9/site-packages/werkzeug/test.py:1081: TypeError
```

This is probably because of the change in werkzeug:
https://stackoverflow.com/questions/71661851/typeerror-init-got-an-unexpected-keyword-argument-as-tuple

I'll address this in a separate PR.

**Review by karlcow — APPROVED** [review]
Thanks @ksy36

**Comment by ksy36** [comment]
Thanks!

**Pull request merged**
