### PR TITLE
Fixes #1491 - Fixed  overflow SVG, causing a scroll on all the page

### LINKED ISSUE #1491: The page can be scrolled left/right
**Environment:**
Browser / Version: Firefox 52.0 Release (Mobile), Firefox Mobile Nightly 55.0a1 (2017-04-07) (Mobile), Chrome (Mobile) 56.0.2924.87.
Operating System: Android

**Steps to Reproduce:**
1. Navigate to: https://webcompat.com
2. Swipe right and left.

**Expected Behavior:**
Nothing happens.

**Actual Behavior:**
The page can be scrolled.

**Notes:**
1. Screenshot attached.

sv;
screenshot_2017-04-07-11-49-06

### PR DESCRIPTION
**Pull request by magsout**
r? @zoepage

### CODE REVIEW

**Comment by zoepage** [comment]
@magsout review needs to sit for another 2-3 days. really sorry :( 
But saved it and will check ASAP!

**Comment by magsout** [comment]
@zoepage don't worry,  take your time  ❤️

**Comment by magsout** [comment]
@zoepage good catch 👍

**Comment by magsout** [comment]
@zoepage fixed, thanks for your review.

**Comment by zoepage** [comment]
LGTM! Thanks @magsout! :)

**Pull request merged**
