### PR TITLE
fixes #2163 - fixed position of dropdon on small screen

### LINKED ISSUE #2163: "My activity" and "Logout" drop-down menu is not visible on Mobile
URL: https://staging.webcompat.com/
Browser / Version: Chrome Desktop 64.0.3282.167, Chrome Mobile 64.0.3282.137
Operating System: Google Pixel (Android 8.0.0) - 1080 x 1920 pixels (~441 ppi pixel density)

**Prerequisites:**
1. Github account available and signed in.

**Steps to Reproduce:**
1. Navigate to https://staging.webcompat.com/
2. Tap the arrow on the right side of the Github user.
3. Observe behavior.

**Expected Behavior:**
Menu with "My activity" and "Logout" option is displayed.

**Actual Behavior:**
Menu with "My activity" and "Logout" option is not visible.

**Note**
1. Not reproducible on Desktop.
2. Affected area:
```html
<button class="nav-button nav-link" aria-pressed="false">
	<img class="login-avatar-img" src="https://avatars0.githubusercontent.com/u/12184325?v=40" alt="User Avatar">
		<svg class="icon nav-icon" viewBox="0 0 30 30" role="presentation">
			<use href="#svg-chevron-right">dropdown</use>
		</svg>
</button>
```

Watchers:
@softvision-sergiulogigan
@softvision-oana-arbuzov

screenshot-1519051946376

### PR DESCRIPTION
**Pull request by magsout**
closed #2163 

r @zoepage and @softvision-oana-arbuzov

### CODE REVIEW

**Comment by zoepage** [comment]
I can still reproduce. 🤔

**Comment by magsout** [comment]
hum

**Comment by magsout** [comment]
@zoepage  ?

What I see, no?
screen recording 2018-02-21 at 06 34 pm

**Comment by zoepage** [comment]
Interesting! Looks like it was a caching issue as it works now. Sorry! 😅

Good job!

**Comment by magsout** [comment]
@zoepage cooool 👍

Ah ah love your gifs ;)

**Pull request merged**
