### PR TITLE
Fixes #589 - display username in Report as button when logged in

### LINKED ISSUE #589: "Report via GitHub" could display username.
When opening a new bug: I get two choices whatever my status being logged or not. 

capture d ecran 2015-03-10 a 09 29 01

"Report Anonymously" seems fine. Maybe two choices:
* When logged in: "Report as [username]"
* When not logged: "Report (via login)" or something better.

The goal is to encourage login for being able to have a discussion when information is missing. To keep anonymous is important even when logged in. Some people might not want their name associated with some Web sites. That's a cool feature.

### PR DESCRIPTION
**Pull request by miketaylr**
r? @karlcow

### CODE REVIEW

**Comment by miketaylr** [comment]
Huh, OK. That test is not happy... looking at why.

**Comment by miketaylr** [comment]
Tests are fixed, ready for review.

**Comment by magsout** [comment]
:+1:

**Comment by miketaylr** [comment]
Hmm, maybe a merge conflict? Updating.

**Comment by miketaylr** [comment]
Conflict resolved. :cool:

**Comment by karlcow** [comment]
yoohoo :mount_fuji:

**Pull request merged**
