### PR TITLE
Fixes #1535 - added Pagination below the list

### LINKED ISSUE #1535: add pagination in "all issues" list at bottom of list
http://localhost:5000/issues?page=1&per_page=50&state=open&stage=all&sort=created&direction=desc 

Pagination `prev` && `next` is above the list.
screen shot 2017-04-26 at 11 50 25 am

We should also add it below the list, so you do not have to scroll up when you want to see the next 50 issues.
screen shot 2017-04-26 at 11 50 35 am

### PR DESCRIPTION
**Pull request by magsout**
r? @zoepage

### CODE REVIEW

**Comment by zoepage** [comment]
@magsout You are on 🔥 right now! Wow! Good job! :)

The change looks good. There is just one tiny thing I was wondering about. 

When I click for example `next`, it gets a highlight. But just the one I've clicked (clicked the upper one). Wanna take a look at that? :)

screen shot 2017-06-10 at 11 49 50 am
screen shot 2017-06-10 at 11 49 55 am

**Comment by magsout** [comment]
@zoepage 

Hum, it's because of the :focus https://github.com/webcompat/webcompat.com/blob/master/webcompat/static/css/development/components/pagination.css#L28

Remove that line fixes the issue, but don't know about accessibility..

**Comment by zoepage** [comment]
@magsout I see. Focus should have an outline when we talk about accessibility standards... 🤔

**Comment by magsout** [comment]
@zoepage so we can remove it?

**Comment by zoepage** [comment]
@magsout +1

**Comment by magsout** [comment]
@zoepage done

**Comment by zoepage** [comment]
Cool! Thanks for your work @magsout <3

**Pull request merged**
