### PR TITLE
Fixes #2017 - post refactor tasks

### LINKED ISSUE #2017: Post-refactor tasks
- [x] move CSS from design/docs to webcompat.com repository and replace old
- [x] change link to CSS in index
- [x] revert CSP and exclude github pages from white list
- [x] lint all files (+ #2031)
- [x] add back pre-linter (after #2031 was fixed)
- [x] move SVG folder after cleaning it out from unused SVG's
- [x] move SVG import script (and dependencies) to package.json and edit paths 
- [x] fix watch-grunt task for CSS (diff against master, jshint is undefined)
- [x] add `webcompat.dev.css` to linter (#2049)

### PR DESCRIPTION
**Pull request by zoepage**
Linting is based on #2060. This needs to be merged first.

r? @miketaylr

### CODE REVIEW

**Comment by miketaylr** [comment]
> Linting is based on #2060. This needs to be merged first.

This PR contains all the same commits (plus some more) as https://github.com/webcompat/webcompat.com/pull/2060. Is this a rebase gone wrong? So if you need to merge this first, please address the review comments from that PR over here.

**Comment by miketaylr** [comment]
r+ on the stylelint changes, but either this PR's history needs to be fixed, or the requested changes from #2060 need to be addressed before merging.

**Comment by zoepage** [comment]
> r+ on the stylelint changes, but either this PR's history needs to be fixed, or the requested changes from #2060 need to be addressed before merging.

+1 on second suggestion

**Comment by miketaylr** [comment]
r+

**Pull request merged**
