### PR TITLE
Improving the readability of bugs and the meta information

### PR DESCRIPTION
**Pull request by magsout**
Do not merge yet. I made this PR that @webcompat/owners can test this idea.

Maybe @calexity if you have ideas to make it beautiful :heart: 

Any suggestion are welcome @webcompat/owners

### CODE REVIEW

**Comment by miketaylr** [comment]
I think we might end up having some "fun" conflicts here.

How should we move forward on this one @magsout?

**Comment by magsout** [comment]
Hum ouch,yeah all conflicts are fun. Maybe close or wait until #749 was merged. Because there is lot file import and export now.

**Comment by miketaylr** [comment]
Yeah, let's wait on #749. I've had a few painful merges myself (trying to keep that up to date).

**Comment by miketaylr** [comment]
OK, #749 is pulled in. It might just be easier to re-create the PR  -- there's a number of places in `IssueDetail-labels.html` that have been changed.

**Comment by magsout** [comment]
Let's close and reopen new one

**Pull request closed without merging**
