### PR TITLE
Fixes #981 - adding a link for the labels in individual issue page

### LINKED ISSUE #981: [bug] non clickable labels
capture d ecran 2016-03-25 a 13 49 32

On issue individual pages, the labels are non clickable 

1. Go to https://webcompat.com/issues/707
2. Click on ie

Nothing happens. All the ie issues should pop up.

### PR DESCRIPTION
**Pull request by deepthivenkat**
r? @miketaylr

### CODE REVIEW

**Comment by miketaylr** [comment]
Functionally, this is great!

I think we need to tweak the design though,

Default:
screen shot 2016-06-09 at 1 19 45 pm

Hover:
screen shot 2016-06-09 at 1 19 34 pm

We can override the opacity 0.7 that's getting inherited, I think it would be better as 1. And probably the underline can just be white instead of black.

Can you also add an Intern test to this PR, so we don't break this in a refactor at some point in the future?

**Comment by magsout** [comment]
@deepthivenkat good 👍 

But I think, you can keep the default className and replace `<span>` by the <a>` like :

```html
<a 
  href="/issues?q=label:<%= label.remoteName %>"
  class="wc-Label wc-Label--badge js-Label" 
  data-remotename="<%= label.remoteName %>"
  title="Labels : <%= label.name %>"
  style="background-color:#<%=label.color%>"
>
  <%= label.name %>
</a>
```

We need to add `text-decoration: none` in `wc-Label`

**Comment by miketaylr** [comment]
@deepthivenkat ping

**Comment by deepthivenkat** [comment]
@miketaylr  @magsout I have to make the underline color as white. This is normally done by adding text-decoration-color property which is deprecated.

Instead I have made use of border-bottom-color property for hover event.

**Comment by miketaylr** [comment]
> This is normally done by adding text-decoration-color property which is deprecated.

So it turns out this isn't deprecated, but is only supported in Firefox and Safari (with a prefix).

**Comment by deepthivenkat** [comment]
Attaching a gif to show the css changes
label

r? @magsout

**Comment by miketaylr** [comment]
I don't think we want the labels to change size when they're hovered over, it's sort of jarring. 

Also the gray and yellow text doesn't look very good (it's hard for me to read).

**Comment by deepthivenkat** [comment]
label2

@miketaylr how about now?

**Comment by miketaylr** [comment]
Much better! Why are we changing the text color from white to gray?

**Comment by deepthivenkat** [comment]
animation
Now?

**Comment by deepthivenkat** [comment]
@miketaylr Grey was the default color. The CSS property used for font color:

color: inherit

**Comment by miketaylr** [comment]
> @miketaylr Grey was the default color. The CSS property used for font color:

Ah, gotcha. This looks better to me -- let's let @magsout review. :)

**Comment by deepthivenkat** [comment]
Oki!

**Comment by miketaylr** [comment]
Ah, I'm sorry -- I goofed here. We intentionally changed the color from white in https://github.com/webcompat/webcompat.com/pull/1094. >___<

**Comment by deepthivenkat** [comment]
No problem! changed it back to grey

**Comment by magsout** [comment]
@miketaylr @deepthivenkat 

I think he previous style is better:

http://cl.ly/170o3B2Y4122

`Hover` with opacity is much better IHMO.

I have remove, border and decrease font-size:

```css
.wc-Labels {
    display: inline-block;
    font-size: .8rem;
    font-weight: 700;
    border-color: transparent;
    opacity: .7;
    text-decoration: none;
    color: inherit;
    margin-left: .5em;
    padding: 0.2em;
    border-radius: 4px;
}
```

**Comment by miketaylr** [comment]
@magsout agreed, seems nicer.

**Comment by miketaylr** [comment]
Let's go ahead and merge this, thanks @deepthivenkat!

**Pull request merged**
