### PR TITLE
Fixes #1906 - added formatting + new content

### LINKED ISSUE #1906: refactor template: about.html
Refactor following:
https://github.com/webcompat/webcompat.com/blob/master/webcompat/templates/about.html

with:
.grid > .grid-row > .grid-cell.x3

Please be aware to add the placeholders for links as they are in the old templates. 
Especially for the JS.

### PR DESCRIPTION
**Pull request by zoepage**

### CODE REVIEW

**Comment by miketaylr** [comment]
I assume this needs rebasing, mind doing that @zoepage?

**Comment by miketaylr** [comment]
Ah, I can review https://github.com/webcompat/webcompat.com/pull/1945/commits/4775b5d8b65830743b41174e29f7dfb33f150060 before you rebase, I assume that's what this PR is for.

**Comment by miketaylr** [comment]
Actually... this might be easier to review content in a google doc or etherpad. Can we do that instead? It's hard to point out a smartquote vs a apostrophe in a giant line of HTML.

**Comment by zoepage** [comment]
Rebased. Going to add suggested content changes to the next commit and ping again.

**Comment by miketaylr** [comment]
> Rebased. Going to add suggested content changes to the next commit and ping again.

Cool, thanks!

**Pull request merged**
