### PR TITLE
Fixes #2811 - Fixes mime type for some endpoints

### LINKED ISSUE #2811: Image being downloaded on webcompat's pages
It's happening something similar to https://github.com/webcompat/webcompat.com/issues/2802 but this time I don't think it's related to fetching images from issues.

screen shot 2019-02-22 at 12 18 01

It's happening only on the home page and only on Staging.

### PR DESCRIPTION
**Pull request by marimeireles**
Hey @karlcow this problem is similar to #2802.

The problem here is that untriaged.js uses a different endpoint that I hadn't fixed: `/api/issues/category/needstriage?per_page=5`

### CODE REVIEW

**Comment by marimeireles** [comment]
The same issue was also happening to when you make a request to this route: `@api.route('/issues/<username>/<parameter>')`. I fixed the same way.
You think I should open a new issue and PR for that or we can do this in this one?

**Comment by miketaylr** [comment]
@marimeireles I still see a request when testing out this branch on localhost:

screen shot 2019-02-22 at 1 45 44 pm

**Comment by marimeireles** [comment]
Thanks @miketaylr. I hadn't noticed that. 
I'll keep looking for a solution.

**Comment by marimeireles** [comment]
>@marimeireles I still see a request when testing out this branch on localhost:

@miketaylr have you tested on a clean profile? I've tested on firefox and chrome and both of them don't show the images anymore.

**Comment by miketaylr** [comment]
Yes, new profile in Nightly:

screen shot 2019-02-22 at 3 36 00 pm

And same results from my regular profile in DevEdition. 

And from Chrome:

screen shot 2019-02-22 at 3 37 02 pm

**Comment by miketaylr** [comment]
`getDescription` is the initiator of the request, so our approach of parsing the body into the DOM to get the description is the culprit.

**Comment by miketaylr** [comment]
It's a dumb hack, but what if we inserted the body content into an inert element.. maybe `<script type=whatever>`, or `<pre>`? I would guess the browser wouldn't bother fetching image sources.

**Comment by marimeireles** [comment]
That's weird.
Do you think running `npm run build` could make any difference here?

My firefox release version:
screen shot 2019-02-22 at 18 39 59

And chrome:
screen shot 2019-02-22 at 18 40 48

**Comment by marimeireles** [comment]
@miketaylr maybe I could also try https://developer.github.com/v3/media/#text

**Comment by miketaylr** [comment]
No, `npm run build` makes no difference -- the JS is served unminified on localhost anyways. @marimeireles which test repo are you pointing at? If it's not webcompat/webcompat-tests, I would point it to that and see if it reproduces.

**Comment by marimeireles** [comment]
Good point!
Ok. Now I can reproduce it.
I'll try to request text only.

**Comment by marimeireles** [comment]
Putting stuff inside a `<pre>` tag didn't work, neither the request for text only.
That's super weird.. I thought my answer here https://github.com/webcompat/webcompat.com/issues/2811#issuecomment-466558161 would be correct because it was happening something really alike #2802 and the HTML request was causing it.

**Comment by marimeireles** [comment]
The images on the requests are the images from the first comment of the issue, aka, the description of the issue.
And this is happening for the home page and the sort by user page see https://staging.webcompat.com/activity/marimeireles for instance...
I was thinking about trying to clean the body issue object that the files `untriaged.js` and `user-activity.js` receives. Is this a terrible idea?

**Comment by miketaylr** [comment]
> I was thinking about trying to clean the body issue object that the files `untriaged.js` and `user-activity.js` receives. Is this a terrible idea?

I'm not sure it's terrible. What if we just added the `title` to the issue model and used that to populate the description? Isn't it the same thing?

**Comment by miketaylr** [comment]
Currently we do:

```
title: this.getTitle(
        this.getDomain(response.title),
        this.getDescription(response.body_html),
        response.title
      )
```

Ah, I see why not.

However, why don't we just fix this on the python side of things on issue creation and make what we want the real title? @karlcow is there any reason we don't do that now?

**Comment by marimeireles** [comment]
This solution Mike proposed didn't work. :/

**Comment by karlcow** [comment]
so let's summarize here :)

1. We removed the markdown thing for improving performance on client side and get the html directly
2. Having the HTML, made it harder to parse the body
3. Parsing the html body to convert the body into DOM, grab the images… (Why on earth there is no plain_text->html_nodes without downloading secondary resources. See below `DOMParser()`)
4. We are trying to jungle around it.

So that's an interesting conundrum.

When we [discussed about the Content type](https://github.com/webcompat/webcompat.com/pull/2731#discussion_r245166251), I pointed out to the [comments API](https://developer.github.com/v3/media/#comment-body-properties)

In there, there is the `application/vnd.github.VERSION.full+json` which returns both JSON and HTML: `body`, `body_text`, and `body_html`.

If I do `http GET https://api.github.com/repos/webcompat/web-bugs/issues/15000 "Accept: application/vnd.github.v3.full+json"`

I get in return (I removed the other parts of the issue):

```
    "body": "<!-- @browser: Firefox 59.0 -->\n<!-- @ua_header: Mozilla/5.0 (Windows NT 6.1; Win64; x64; rv:59.0) Gecko/20100101 Firefox/59.0 -->\n<!-- @reported_with: desktop-reporter -->\n<!-- @extra_labels: type-stylo -->\n\n**URL**: https://www.prudential.com.sg/en/our-solutions/products/prushield/\n\n**Browser / Version**: Firefox 59.0\n**Operating System**: Windows 7\n**Tested Another Browser**: Yes\n\n**Problem type**: Design is broken\n**Description**: Text rendering missing\n**Steps to Reproduce**:\n\r\nlayout.css.servo.enabled: true\r\n[![Screenshot Description](https://webcompat.com/uploads/2018/1/69865e31-89f0-4c24-a40d-f26dfcbf2d16-thumb.jpg)](https://webcompat.com/uploads/2018/1/69865e31-89f0-4c24-a40d-f26dfcbf2d16.jpg)\n\n\n\n_From [webcompat.com](https://webcompat.com/) with ❤️_", 
    "body_html": "\n\n\n\n<p><strong>URL</strong>: <a rel=\"nofollow\" href=\"https://www.prudential.com.sg/en/our-solutions/products/prushield/\">https://www.prudential.com.sg/en/our-solutions/products/prushield/</a></p>\n<p><strong>Browser / Version</strong>: Firefox 59.0<br>\n<strong>Operating System</strong>: Windows 7<br>\n<strong>Tested Another Browser</strong>: Yes</p>\n<p><strong>Problem type</strong>: Design is broken<br>\n<strong>Description</strong>: Text rendering missing<br>\n<strong>Steps to Reproduce</strong>:</p>\n<p>layout.css.servo.enabled: true<br>\n<a href=\"https://webcompat.com/uploads/2018/1/69865e31-89f0-4c24-a40d-f26dfcbf2d16.jpg\" rel=\"nofollow\"><img src=\"https://camo.githubusercontent.com/c2797655bd8d6452c61f922cfb3c0bfc87afebd5/68747470733a2f2f776562636f6d7061742e636f6d2f75706c6f6164732f323031382f312f36393836356533312d383966302d346332342d613430642d6632366466636266326431362d7468756d622e6a7067\" alt=\"Screenshot Description\" data-canonical-src=\"https://webcompat.com/uploads/2018/1/69865e31-89f0-4c24-a40d-f26dfcbf2d16-thumb.jpg\" style=\"max-width:100%;\"></a></p>\n<p><em>From <a href=\"https://webcompat.com/\" rel=\"nofollow\">webcompat.com</a> with <g-emoji class=\"g-emoji\" alias=\"heart\" fallback-src=\"https://github.githubassets.com/images/icons/emoji/unicode/2764.png\">❤️</g-emoji></em></p>", 
    "body_text": "URL: https://www.prudential.com.sg/en/our-solutions/products/prushield/\nBrowser / Version: Firefox 59.0\nOperating System: Windows 7\nTested Another Browser: Yes\nProblem type: Design is broken\nDescription: Text rendering missing\nSteps to Reproduce:\nlayout.css.servo.enabled: true\n\nFrom webcompat.com with ❤️", 
``` 


## DOMParser
So indeed this doesn't show image download, you can query the html, but unfortunately you can't convert to text.

```js
var myText = "<p><img src='http://localhost:5000/uploads/2019/2/36b4786d-da2a-41f6-9646-4662794c8aaa.jpeg'> </p>";
var myparser = new DOMParser();
var myfragment = myparser.parseFromString(myText , "text/html");
myfragment.body.innerHTML
// "<p><img src=\"http://localhost:5000/uploads/2019/2/36b4786d-da2a-41f6-9646-4662794c8aaa.jpeg\"> </p>"
myfragment.body.getElementsByTagName('p')
// HTMLCollection [ p ]
 myfragment.body.getElementsByTagName('img')
// HTMLCollection [ img ]
myfragment.body.textContent
// " "
myfragment.body.innerText
// " "
```

**Comment by karlcow** [comment]
@miketaylr 

> However, why don't we just fix this on the python side of things on issue creation and make what we want the real title? @karlcow is there any reason we don't do that now?

Let's rewind a bit the history of this:

1. we were asking for the title
2. then we added the possibility to get the description instead if it's there, and fallback on the title (cut at 75)
3. then we are trying to reparse the html body as text to get the description.

Now we have on the python side access to

1. The body_html `"body_html": "…………"`
2. the title `    "title": "www.prudential.com.sg - design is broken", `

Some ideas:

* We could parse the html, then extract the text on the python side. This will have a CPU cost for html parsing. Then convert to text. Then parse the text.
* We could request the 3 bodies then extract the text directly on the python side. This will have a bytes cost for transfert. no need to convert to text. then parse the text.

**Comment by karlcow** [comment]
Ah I had missed about the context of @miketaylr asking
**on issue creation** and make what we want the real title? 

We can for the future. :) But that doesn't change we need to address the past. :)
And that's partly already what is proposed in #2629. By creating a limit there, we can reuse that directly as a title.

**Comment by karlcow** [comment]
another funny thing, we could be less constraint if we had `-webkit-line-clamp` ;)

**Comment by miketaylr** [comment]
> another funny thing, we could be less constraint if we had `-webkit-line-clamp` ;)

that's coming in the not too distant future. :)

**Comment by marimeireles** [comment]
Thanks for trying to parse the content on DOM @karlcow.
I'll try to extract the text on the python side!

**Comment by marimeireles** [comment]
This new change fixed the issue for me...
I forgot to erase one mime_type that was inside an `if` 🙈

**Comment by marimeireles** [comment]
Can you please test @miketaylr ? If it works for you. -when you have the time
Thanks!

**Comment by miketaylr** [comment]
> Can you please test @miketaylr ? If it works for you. -when you have the time

Yep! Working here.

**Comment by marimeireles** [comment]
Oh, so. What do we do @karlcow ?
You still think it's a better idea to extract the text on python?
I think we could leave it as it is and we can fix this https://github.com/webcompat/webcompat.com/issues/2629 in a different way.

**Comment by marimeireles** [comment]
@karlcow does it look good to merge?

**Comment by karlcow** [comment]
Ah missed this one. Soory. I will check tonight in ~12h.

**Pull request merged**
