### PR TITLE
Fixes #2762 - Removes the autolinking on adding contact

### LINKED ISSUE #2762: Consider not @-linking github username field
```
<sergiu> heya!
karlcow, looks like we have some people who abuses the GitHub handle field: https://github.com/webcompat/web-bugs/issues/24074#issuecomment-454776680
7:58 AM some time ago I got another complaint from a mentioned user, saying that he/she did not log that issue in the first place, and doesn't kno how the github handle ended up in our bug report
8:00 AM did not pay too much attention at the time
8:01 AM 
— sergiu remembered that karl is on STO...
8:02 AM 
<oana> https://github.com/webcompat/web-bugs/issues/23442
8:02 AM this is another one 
```

https://github.com/webcompat/web-bugs/issues/23442
https://github.com/webcompat/web-bugs/issues/24074

This would be less spammy if we wrote `foo` instead of `@foo`.

### PR DESCRIPTION
**Pull request by karlcow**
This PR fixes issue #2762 and #2791

## Proposed PR background

The intent here is to avoid the auto-notification for people having their names added into the issue being reported.
It also slighly modifies the text to make it clear that it's not necessary reported by this person.

### CODE REVIEW

**Comment by patrickpehsoonchai** [comment]
获取 Outlook for Android<https://aka.ms/ghei36>



发件人: Karl Dubost
发送时间: 4月4日星期四 07:22
主题: [webcompat/webcompat.com] Fixes #2762 - Removes the autolinking on adding contact (#2833)
收件人: webcompat/webcompat.com
抄送: Subscribed


This PR fixes issue #2762<https://github.com/webcompat/webcompat.com/issues/2762> and #2791<https://github.com/webcompat/webcompat.com/issues/2791>
Proposed PR background
The intent here is to avoid the auto-notification for people having their names added into the issue being reported.
It also slighly modifies the text to make it clear that it's not necessary reported by this person.
You can view, comment on, or merge this pull request online at:
  https://github.com/webcompat/webcompat.com/pull/2833
Commit Summary
Issue #2762 - Remove the autolinking on adding contact
File Changes
M webcompat/form.py<https://github.com/webcompat/webcompat.com/pull/2833/files#diff-0> (3)
Patch Links:
https://github.com/webcompat/webcompat.com/pull/2833.patchhttps://github.com/webcompat/webcompat.com/pull/2833.diff
―

**Comment by adamopenweb** [comment]
I agree it could be confusing the way it's written now. But I'm struggling to come up with an easy way to describe that, while keeping it short.

**Comment by karlcow** [comment]
Maybe something like
This might have be reported by `@miketaylr` (maybe)

We could even make the maybe a link to the issue and/or an additional docs item in webcompat.com

**Comment by karlcow** [comment]
@miketaylr @adamopenweb on wording above.

**Comment by adamopenweb** [comment]
I'm good with that. It's possibly still confusing for some, but I think is an improvement. 😄

**Comment by karlcow** [comment]
ok cool! Let's merge then. We can improve moar later.

**Pull request merged**
