### PR TITLE
Fixes #821: Add Tablet info to browser name

### LINKED ISSUE #821: Add Tablet info to browser name
See https://github.com/webcompat/webcompat.com/issues/819#issuecomment-153974462.

The idea would be if we have `device.model == 'Tablet'`, we add a `(Tablet)` after the browser name. Just need to investigate how other tablet browsers are currently displayed so we don't do something silly like `Chrome Tablet (Tablet)`.

### PR DESCRIPTION
**Pull request by dshgna**
Initial commit.

### CODE REVIEW

**Comment by miketaylr** [comment]
Looks like you're on the right track, yes!

It might be good to add a few tests to https://github.com/webcompat/webcompat.com/blob/master/tests/test_helpers.py to make sure the right UA strings get the Tablet treatment and some non-Tablet ones don't.

**Comment by karlcow** [comment]
hehe @miketaylr ping.

But to help. The science of UA strings is black magic. So basically there's no perfection. But we want to make sure that indeed we get the right label when there is a tablet hitting webcompat.

So currently get_browser_name is used in
https://github.com/dshgna/webcompat.com/blob/issue/821/webcompat/views.py#L129-L133

which calls itself the templating engine for the index page and prepopulate the form:

capture d ecran 2016-03-08 a 12 39 13

```html
<div class="wc-Form-group js-Form-group">
            <label class="wc-Form-label" for="browser">Browser / Version</label> <input class="wc-Form-item" id="browser" name="browser" value="Firefox 47.0" type="text">
          </div>
```

When we actually submit the form we get the value of the UA from 

```python
    form['ua_header'] = request.headers.get('User-Agent')
```
https://github.com/dshgna/webcompat.com/blob/issue/821/webcompat/views.py#L162

Then we head to `report_issue`

https://github.com/dshgna/webcompat.com/blob/issue/821/webcompat/issues.py#L19

which is using `build_formdata`
https://github.com/dshgna/webcompat.com/blob/issue/821/webcompat/form.py#L139

which is reading the `browser` parameter
https://github.com/dshgna/webcompat.com/blob/issue/821/webcompat/form.py#L181

but also triggers the labels:
https://github.com/dshgna/webcompat.com/blob/issue/821/webcompat/form.py#L178

aka `get_labels()`
https://github.com/dshgna/webcompat.com/blob/issue/821/webcompat/form.py#L106

SO I guess the final question is what type of labels do we want in the bug reporting system when there is a tablet :)

**Comment by miketaylr** [comment]
> hehe @miketaylr ping.

Oh! So sorry @dshgna, this mention escaped me. :see_no_evil:

**Comment by miketaylr** [comment]
@dshgna if you click on the Details link of the travis-ci build (see https://cloudup.com/cy5FSvXC0WB), you'll see the following error (scroll down and look for the red text):

`The command "pep8 --ignore=E402 webcompat/ tests/ config/secrets.py.example" failed and exited with 1 during .`

Can you re-run pep8 and fix any errors there (and push the fixes)?

**Comment by miketaylr** [comment]
@karlcow do you think it makes sense to have "firefox mobile tablet" label in addition to "firefox mobile"? Or is the name in the bug report "Firefox Mobile (Tablet)" sufficient? I don't have any strong feelings, I'm sort of leaning towards just one "firefox mobile" label...

**Comment by miketaylr** [comment]
@dshgna a few commit nits to take care of if you don't mind:

When you fix up pep8 errors, can you add "Issue #821. " to the beginning of the commit message (for the test commit)? Likewise, for the first commit -- can you add a hash mark in front of the issue number, e.g., "Fixes #821"?

That will help link all the commits to the issue. If you need help on how to re-write a commit message just let me know!

**Comment by karlcow** [comment]
@miketaylr  about

>@karlcow do you think it makes sense to have "firefox mobile tablet" label in addition to "firefox mobile"? 

I would rather have two differents labels such as:

* browsername-tablet
* browsername-mobile

and/or an information about the screen size. The reason it has happen often that I didn't know if the bug reporter was talking about tablets and was testing on a small viewport device. In some cases, Web sites choose to send desktop sites to the tablet form factor.

I suspect you guess the form factor by looking at the UA in general and because you spent most of your time in github instead of webcompat ;) :p (Use the force, mike, it helps to improve the product hmm no laser sabre in emojis. Maybe this will do ⚡️🗡🐸)

**Comment by miketaylr** [comment]
> I would rather have two differents labels such as:

OK, that's what this should do. :+1: 

> and/or an information about the screen size. The reason it has happen often that I didn't know if the bug reporter was talking about tablets and was testing on a small viewport device. In some cases, Web sites choose to send desktop sites to the tablet form factor.

Sounds like a good feature request. File a bug? This would be good info to put in the bug body.

> I suspect you guess the form factor by looking at the UA in general and because you spent most of your time in github instead of webcompat ;)

Yes and no. :p

**Comment by dshgna** [comment]
@miketaylr Just a bit confused here on the merge :) 

> I would rather have two different labels such as:

I got the understanding that I had to change the 'browser mobile tablet' to 'browser tablet' and just made a [commit](https://github.com/dshgna/webcompat.com/commit/aa99978839e723072c088690023d8269aa2931cb) as such. 

So, is this okay as is?

**Comment by miketaylr** [comment]
Personally I think "firefox mobile tablet" is ok! Let's see how it feels and we can change it up as needed.

**Comment by dshgna** [comment]
@miketaylr sure thanks! :+1:

**Pull request merged**
