### PR TITLE
Fixes #1358: Add a details param to put info in description textarea.

### LINKED ISSUE #1358: Add a GET param to pre-populate extra details inside issue description
(See #1356 for discussion of Media team's needs.)

### PR DESCRIPTION
**Pull request by miketaylr**
r? @zoepage

### CODE REVIEW

**Comment by zoepage** [comment]
@miketaylr 
The tests related to the changes pass. Code matches the requests in the issue.
Just one question: Why did you remove the check in bugform.js? 
Otherwise it looks good to me.  👍 



General:
Locally 28 tests fail. In the Travis build 7.
But that's probably a different bug.
https://gist.github.com/zoepage/f4e07f5bcb544d124fe4d626c0de6e3c

**Comment by miketaylr** [comment]
> Just one question: Why did you remove the check in bugform.js?

If you mean https://github.com/webcompat/webcompat.com/pull/1379/files#diff-ce241059c28a13e03bcd0829da8d4eb7L142, we don't use the `?open=1` param in the addons/browser button anymore (we send users to `/issues/new` instead) so the code in `checkParams` would never run.

> Locally 28 tests fail. In the Travis build 7.

Yeah, different bugs. That's the point of the next Outreachy round -- figure out what's up with intermittents (they all pass on my machine).

**Comment by miketaylr** [comment]
> Otherwise it looks good to me. 👍

Based on that comment, let's merge!

**Comment by miketaylr** [comment]
Thanks for review @zoepage!

**Pull request merged**
