### PR TITLE
fix #902 - 902/1 Update python module dependencies in the project.

### LINKED ISSUE #902: Update Python deps
Just discovered https://requires.io/github/webcompat/webcompat.com/requirements/?branch=master, and we could update some stuff. (After testing).

### PR DESCRIPTION
**Pull request by karlcow**
- Nosetest ran after each individual module upgrade.
- a sequence of monkey testing for each install. 
- Proposed to push this into staging for tests

### CODE REVIEW

**Comment by miketaylr** [comment]
Oh man, sorry @karlcow -- I somehow missed this review request. :cry:

**Comment by miketaylr** [comment]
Locally it seems good. Let me push it to staging.

**Comment by miketaylr** [comment]
Seems good, let's merge. :+1:

**Comment by karlcow** [comment]
Yoohooo!

**Pull request merged**
