### PR TITLE
Issue #929 - Generic error handler based on status code for status 40…

### PR DESCRIPTION
**Pull request by deepthivenkat**
…0,401,403,404

### CODE REVIEW

**Comment by miketaylr** [comment]
r? @karlcow 

(I can review too, but Karl suggested this approach -- would be interested in his feedback).

**Comment by miketaylr** [comment]
@deepthivenkat can you run pep8 and fix up any lint errors there?

`The command "pep8 --ignore=E402 webcompat/ tests/ config/secrets.py.example" failed and exited with 1 during .`

**Comment by deepthivenkat** [comment]
Sure..checking

**Comment by karlcow** [comment]
@deepthivenkat Thanks for starting working on this.

Let's discuss a bit more. ^_^

So in my approach I realized that I mixed two ways of making it more DRY, and it's probably over-doing it.
There's room for discussions on how to improve in a step by step.

* If we are sure that all `4**` HTTP codes follow the same pattern. We do not to abstract the two functions (`api_call(request)`, `api_message(code)`). We just need to have the appropriate decorators on top of one generic function.
* If we have different treatments in between the `4**` HTTP codes then the abstraction of the two methods is worth. 

We still need a dictionary for error messages. We also need to figure out if we want to have separate messaging for HTML (Human calls) and JSON (API calls).

Opinions? If what I say above is not clear enough, I can go a bit more in details. :)

**Comment by karlcow** [comment]
There's a need to clean this pull request with the input of #958 and also it removes some data. etc.
Maybe easier would be to restart with a clean branch and delete this pull request and the #958 
If you need guidance tell us.

**Comment by deepthivenkat** [comment]
I accidentally deleted requirements.txt. there were few more issues. So I deleted the repository and cloned it again and started with a clean branch(the one I submitted yesterday is from this new branch). Is it okay if we continue with the new pull request?

**Comment by magsout** [comment]
@deepthivenkat so let's closed this issue in favor of https://github.com/webcompat/webcompat.com/pull/958, sound good ?

**Comment by deepthivenkat** [comment]
Yes..Thanks :)

**Pull request closed without merging**
